// GENERATED by tools/python/extract_bindings.py + bindgen.backends.lua_sol2 -- DO NOT EDIT.
// Source of truth: tools/bindings/ir/bindings.ir.json (from VBIND_* annotations).

#include "vultra/function/scripting/bindings/script_script_binding.hpp"

#include "vultra/function/scripting/bindings/script_binding_common.hpp"
#include "vultra/function/scripting/script_context.hpp"
#include "vultra/function/scripting/script_types.hpp"
#include "vultra/function/services/script_service.hpp"

#include <cstdint>
#include <string>

namespace vultra
{
    void registerScriptScriptBindings(sol::state& lua, ScriptContext& ctx)
    {
        (void)ctx;
        {
            auto ns = script_binding::getOrCreateTable(lua, "Script");
            ns.set_function("reloadEntity",
                [&ctx](const ScriptEntity& e) {
                    return ctx.scriptService && ctx.isValid(e.value) ? ctx.scriptService->reloadEntityScript(e.value) : false;
                });
            ns.set_function("reloadAll",
                [&ctx]() {
                    return ctx.scriptService ? ctx.scriptService->reloadAllScripts() : false;
                });
            ns.set_function("hasInstance",
                [&ctx](const ScriptEntity& e) {
                    return ctx.scriptService && ctx.isValid(e.value) ? ctx.scriptService->hasScriptInstance(e.value) : false;
                });
            ns.set_function("destroyInstance",
                [&ctx](const ScriptEntity& e) {
                    if (ctx.scriptService && ctx.isValid(e.value)) ctx.scriptService->destroyScriptInstance(e.value);
                });
            ns.set_function("setPlaybackState",
                [&ctx](bool playing, bool paused) {
                    if (ctx.scriptService) ctx.scriptService->setPlaybackState(playing, paused);
                });
            ns.set_function("isPlaybackPlaying",
                [&ctx]() {
                    return ctx.scriptService ? ctx.scriptService->isPlaybackPlaying() : false;
                });
            ns.set_function("isPlaybackPaused",
                [&ctx]() {
                    return ctx.scriptService ? ctx.scriptService->isPlaybackPaused() : false;
                });
            ns.set_function("runString",
                [&ctx](const std::string& code) {
                    return ctx.scriptService ? ctx.scriptService->runString(code) : false;
                });
        }

    }
} // namespace vultra
