// GENERATED by tools/python/extract_bindings.py + bindgen.backends.lua_sol2 -- DO NOT EDIT.
// Source of truth: tools/bindings/ir/bindings.ir.json (from VBIND_* annotations).

#include "vultra/function/scripting/bindings/script_physics_binding.hpp"

#include "vultra/function/scripting/bindings/script_binding_common.hpp"
#include "vultra/function/scripting/script_context.hpp"
#include "vultra/function/scripting/script_types.hpp"
#include "vultra/function/world/world.hpp"
#include "vultra/function/scripting/bindings/script_physics_shim.hpp"

#include <cstdint>
#include <string>

namespace vultra
{
    void registerScriptPhysicsBindings(sol::state& lua, ScriptContext& ctx)
    {
        (void)ctx;
        lua.new_usertype<ScriptPhysicsRaycastHit>(
            "PhysicsRaycastHit",
            "hit",
            &ScriptPhysicsRaycastHit::hit,
            "entity",
            &ScriptPhysicsRaycastHit::entity,
            "point",
            &ScriptPhysicsRaycastHit::point,
            "normal",
            &ScriptPhysicsRaycastHit::normal,
            "fraction",
            &ScriptPhysicsRaycastHit::fraction,
            "distance",
            &ScriptPhysicsRaycastHit::distance);

        lua.new_usertype<ScriptPhysicsContactPair>(
            "PhysicsContactPair",
            "a",
            &ScriptPhysicsContactPair::a,
            "b",
            &ScriptPhysicsContactPair::b);

        lua.new_usertype<ScriptRigidBodyRef>(
            "RigidBody",
            "valid",
            script_binding::readonlyProperty([&ctx](const ScriptRigidBodyRef& self) {
                auto* world = ctx.world();
                return world && world->registry().all_of<RigidBodyComponent>(self.entity);
            }),
            "linearVelocity",
            script_binding::property([&ctx](const ScriptRigidBodyRef& self) { return rbGetLinearVelocity(ctx, self); },
            [&ctx](const ScriptRigidBodyRef& self, ScriptVec3 value) { rbSetLinearVelocity(ctx, self, value); }),
            "angularVelocity",
            script_binding::property([&ctx](const ScriptRigidBodyRef& self) { return rbGetAngularVelocity(ctx, self); },
            [&ctx](const ScriptRigidBodyRef& self, ScriptVec3 value) { rbSetAngularVelocity(ctx, self, value); }),
            "motionType",
            script_binding::property([&ctx](const ScriptRigidBodyRef& self) { return rbGetMotionType(ctx, self); },
            [&ctx](const ScriptRigidBodyRef& self, std::uint32_t value) { rbSetMotionType(ctx, self, value); }),
            "objectLayer",
            script_binding::property([&ctx](const ScriptRigidBodyRef& self) { return rbGetObjectLayer(ctx, self); },
            [&ctx](const ScriptRigidBodyRef& self, std::uint32_t value) { rbSetObjectLayer(ctx, self, value); }),
            "isSensor",
            script_binding::property([&ctx](const ScriptRigidBodyRef& self) { return rbGetIsSensor(ctx, self); },
            [&ctx](const ScriptRigidBodyRef& self, bool value) { rbSetIsSensor(ctx, self, value); }),
            "motionQuality",
            script_binding::property([&ctx](const ScriptRigidBodyRef& self) { return rbGetMotionQuality(ctx, self); },
            [&ctx](const ScriptRigidBodyRef& self, std::uint32_t value) { rbSetMotionQuality(ctx, self, value); }),
            "allowSleeping",
            script_binding::property([&ctx](const ScriptRigidBodyRef& self) { return rbGetAllowSleeping(ctx, self); },
            [&ctx](const ScriptRigidBodyRef& self, bool value) { rbSetAllowSleeping(ctx, self, value); }),
            "mass",
            script_binding::property([&ctx](const ScriptRigidBodyRef& self) { return rbGetMass(ctx, self); },
            [&ctx](const ScriptRigidBodyRef& self, float value) { rbSetMass(ctx, self, value); }),
            "overrideMass",
            script_binding::property([&ctx](const ScriptRigidBodyRef& self) { return rbGetOverrideMass(ctx, self); },
            [&ctx](const ScriptRigidBodyRef& self, bool value) { rbSetOverrideMass(ctx, self, value); }),
            "friction",
            script_binding::property([&ctx](const ScriptRigidBodyRef& self) { return rbGetFriction(ctx, self); },
            [&ctx](const ScriptRigidBodyRef& self, float value) { rbSetFriction(ctx, self, value); }),
            "restitution",
            script_binding::property([&ctx](const ScriptRigidBodyRef& self) { return rbGetRestitution(ctx, self); },
            [&ctx](const ScriptRigidBodyRef& self, float value) { rbSetRestitution(ctx, self, value); }),
            "linearDamping",
            script_binding::property([&ctx](const ScriptRigidBodyRef& self) { return rbGetLinearDamping(ctx, self); },
            [&ctx](const ScriptRigidBodyRef& self, float value) { rbSetLinearDamping(ctx, self, value); }),
            "angularDamping",
            script_binding::property([&ctx](const ScriptRigidBodyRef& self) { return rbGetAngularDamping(ctx, self); },
            [&ctx](const ScriptRigidBodyRef& self, float value) { rbSetAngularDamping(ctx, self, value); }),
            "gravityFactor",
            script_binding::property([&ctx](const ScriptRigidBodyRef& self) { return rbGetGravityFactor(ctx, self); },
            [&ctx](const ScriptRigidBodyRef& self, float value) { rbSetGravityFactor(ctx, self, value); }),
            "maxLinearVelocity",
            script_binding::property([&ctx](const ScriptRigidBodyRef& self) { return rbGetMaxLinearVelocity(ctx, self); },
            [&ctx](const ScriptRigidBodyRef& self, float value) { rbSetMaxLinearVelocity(ctx, self, value); }),
            "maxAngularVelocity",
            script_binding::property([&ctx](const ScriptRigidBodyRef& self) { return rbGetMaxAngularVelocity(ctx, self); },
            [&ctx](const ScriptRigidBodyRef& self, float value) { rbSetMaxAngularVelocity(ctx, self, value); }),
            "activate",
            [&ctx](const ScriptRigidBodyRef & self) {
                return rbActivate(ctx, self);
            },
            "addForce",
            [&ctx](const ScriptRigidBodyRef & self, const ScriptVec3 & force) {
                return rbAddForce(ctx, self, force);
            },
            "addImpulse",
            [&ctx](const ScriptRigidBodyRef & self, const ScriptVec3 & impulse) {
                return rbAddImpulse(ctx, self, impulse);
            },
            "setPosition",
            [&ctx](const ScriptRigidBodyRef & self, const ScriptVec3 & position, sol::optional<bool> activate) {
                return rbSetPosition(ctx, self, position, activate);
            });

        {
            auto ns = script_binding::getOrCreateTable(lua, "Physics");
            ns.set_function("enabled",
                [&ctx]() {
                    return physicsEnabled(ctx);
                });
            ns.set_function("setEnabled",
                [&ctx](bool enabled) {
                    physicsSetEnabled(ctx, enabled);
                });
            ns.set_function("bodyCount",
                [&ctx]() {
                    return physicsBodyCount(ctx);
                });
            ns.set_function("hasBody",
                [&ctx](const ScriptEntity & entity) {
                    return physicsHasBody(ctx, entity);
                });
            ns.set_function("fixedTimeStep",
                [&ctx]() {
                    return physicsFixedTimeStep(ctx);
                });
            ns.set_function("setFixedTimeStep",
                [&ctx](float seconds) {
                    physicsSetFixedTimeStep(ctx, seconds);
                });
            ns.set_function("addForce",
                [&ctx](const ScriptEntity & entity, const ScriptVec3 & force) {
                    return physicsAddForce(ctx, entity, force);
                });
            ns.set_function("addImpulse",
                [&ctx](const ScriptEntity & entity, const ScriptVec3 & impulse) {
                    return physicsAddImpulse(ctx, entity, impulse);
                });
            ns.set_function("setPosition",
                [&ctx](const ScriptEntity & entity, const ScriptVec3 & position, sol::optional<bool> activate) {
                    return physicsSetPosition(ctx, entity, position, activate);
                });
            ns.set_function("raycast",
                [&ctx](const ScriptVec3 & origin, const ScriptVec3 & direction, float maxDistance, sol::optional<bool> activeOnly, sol::optional<std::uint32_t> layerMask) {
                    return physicsRaycast(ctx, origin, direction, maxDistance, activeOnly, layerMask);
                });
            ns.set_function("raycastAll",
                [&ctx](sol::this_state luaState, const ScriptVec3 & origin, const ScriptVec3 & direction, float maxDistance, sol::optional<bool> activeOnly, sol::optional<std::uint32_t> layerMask) {
                    return physicsRaycastAll(ctx, luaState, origin, direction, maxDistance, activeOnly, layerMask);
                });
            ns.set_function("sphereCast",
                [&ctx](sol::this_state luaState, const ScriptVec3 & origin, const ScriptVec3 & direction, float radius, float maxDistance, sol::optional<bool> activeOnly, sol::optional<std::uint32_t> layerMask) {
                    return physicsSphereCast(ctx, luaState, origin, direction, radius, maxDistance, activeOnly, layerMask);
                });
            ns.set_function("overlapSphere",
                [&ctx](sol::this_state luaState, const ScriptVec3 & center, float radius, sol::optional<bool> activeOnly) {
                    return physicsOverlapSphere(ctx, luaState, center, radius, activeOnly);
                });
            ns.set_function("overlapBox",
                [&ctx](sol::this_state luaState, const ScriptVec3 & center, const ScriptVec3 & halfExtents, sol::optional<bool> activeOnly) {
                    return physicsOverlapBox(ctx, luaState, center, halfExtents, activeOnly);
                });
            ns.set_function("overlapCapsule",
                [&ctx](sol::this_state luaState, const ScriptVec3 & center, float halfHeight, float radius, sol::optional<bool> activeOnly, sol::optional<std::uint32_t> layerMask) {
                    return physicsOverlapCapsule(ctx, luaState, center, halfHeight, radius, activeOnly, layerMask);
                });
            ns.set_function("contactPairs",
                [&ctx](sol::this_state luaState, sol::optional<bool> activeOnly) {
                    return physicsContactPairs(ctx, luaState, activeOnly);
                });
            ns.set_function("contactEvents",
                [&ctx](sol::this_state luaState) {
                    return physicsContactEvents(ctx, luaState);
                });
            ns.set_function("addTorque",
                [&ctx](const ScriptEntity & entity, const ScriptVec3 & torque) {
                    return physicsAddTorque(ctx, entity, torque);
                });
            ns.set_function("addAngularImpulse",
                [&ctx](const ScriptEntity & entity, const ScriptVec3 & impulse) {
                    return physicsAddAngularImpulse(ctx, entity, impulse);
                });
            ns.set_function("setRotation",
                [&ctx](const ScriptEntity & entity, const ScriptVec3 & eulerDegrees, sol::optional<bool> activate) {
                    return physicsSetRotation(ctx, entity, eulerDegrees, activate);
                });
            ns.set_function("gravity",
                [&ctx]() {
                    return physicsGravity(ctx);
                });
            ns.set_function("setGravity",
                [&ctx](const ScriptVec3 & gravity) {
                    physicsSetGravity(ctx, gravity);
                });
            ns.set_function("setLayerCollision",
                [&ctx](std::uint32_t a, std::uint32_t b, bool enabled) {
                    physicsSetLayerCollision(ctx, a, b, enabled);
                });
            ns.set_function("layerCollision",
                [&ctx](std::uint32_t a, std::uint32_t b) {
                    return physicsLayerCollision(ctx, a, b);
                });
            ns.set_function("addFixedConstraint",
                [&ctx](const ScriptEntity & bodyA, sol::optional<ScriptEntity> bodyB) {
                    return physicsAddFixedConstraint(ctx, bodyA, bodyB);
                });
            ns.set_function("addPointConstraint",
                [&ctx](const ScriptEntity & bodyA, sol::optional<ScriptEntity> bodyB, const ScriptVec3 & point) {
                    return physicsAddPointConstraint(ctx, bodyA, bodyB, point);
                });
            ns.set_function("addDistanceConstraint",
                [&ctx](const ScriptEntity & bodyA, sol::optional<ScriptEntity> bodyB, float minDistance, float maxDistance) {
                    return physicsAddDistanceConstraint(ctx, bodyA, bodyB, minDistance, maxDistance);
                });
            ns.set_function("addHingeConstraint",
                [&ctx](const ScriptEntity & bodyA, sol::optional<ScriptEntity> bodyB, const ScriptVec3 & point, const ScriptVec3 & axis, float minAngleDegrees, float maxAngleDegrees) {
                    return physicsAddHingeConstraint(ctx, bodyA, bodyB, point, axis, minAngleDegrees, maxAngleDegrees);
                });
            ns.set_function("addSliderConstraint",
                [&ctx](const ScriptEntity & bodyA, sol::optional<ScriptEntity> bodyB, const ScriptVec3 & point, const ScriptVec3 & axis, float minDistance, float maxDistance) {
                    return physicsAddSliderConstraint(ctx, bodyA, bodyB, point, axis, minDistance, maxDistance);
                });
            ns.set_function("addConeConstraint",
                [&ctx](const ScriptEntity & bodyA, sol::optional<ScriptEntity> bodyB, const ScriptVec3 & point, const ScriptVec3 & twistAxis, float halfAngleDegrees) {
                    return physicsAddConeConstraint(ctx, bodyA, bodyB, point, twistAxis, halfAngleDegrees);
                });
            ns.set_function("removeConstraint",
                [&ctx](std::uint32_t constraintId) {
                    return physicsRemoveConstraint(ctx, constraintId);
                });
            ns.set_function("isConstraintValid",
                [&ctx](std::uint32_t constraintId) {
                    return physicsIsConstraintValid(ctx, constraintId);
                });
            ns.set_function("setConstraintMotor",
                [&ctx](std::uint32_t constraintId, bool enabled, float targetVelocity, float maxForce) {
                    return physicsSetConstraintMotor(ctx, constraintId, enabled, targetVelocity, maxForce);
                });
        }

        {
            auto ns = script_binding::getOrCreateTable(lua, "Character");
            ns.set_function("has",
                [&ctx](const ScriptEntity & entity) {
                    return characterHas(ctx, entity);
                });
            ns.set_function("move",
                [&ctx](const ScriptEntity & entity, const ScriptVec3 & horizontalVelocity) {
                    return characterMove(ctx, entity, horizontalVelocity);
                });
            ns.set_function("jump",
                [&ctx](const ScriptEntity & entity, sol::optional<float> speed) {
                    return characterJump(ctx, entity, speed);
                });
            ns.set_function("isGrounded",
                [&ctx](const ScriptEntity & entity) {
                    return characterIsGrounded(ctx, entity);
                });
            ns.set_function("velocity",
                [&ctx](const ScriptEntity & entity) {
                    return characterVelocity(ctx, entity);
                });
            ns.set_function("groundNormal",
                [&ctx](const ScriptEntity & entity) {
                    return characterGroundNormal(ctx, entity);
                });
            ns.set_function("setPosition",
                [&ctx](const ScriptEntity & entity, const ScriptVec3 & position) {
                    return characterSetPosition(ctx, entity, position);
                });
        }

    }
} // namespace vultra
