// GENERATED by tools/python/extract_bindings.py + bindgen.backends.lua_sol2 -- DO NOT EDIT.
// Source of truth: tools/bindings/ir/bindings.ir.json (from VBIND_* annotations).

#include "vultra/function/scripting/bindings/script_timing_binding.hpp"

#include "vultra/function/scripting/bindings/script_binding_common.hpp"
#include "vultra/function/scripting/script_context.hpp"
#include "vultra/function/scripting/script_types.hpp"
#include "vultra/core/services/timing_service.hpp"

#include <cstdint>
#include <string>

namespace vultra
{
    void registerScriptTimingBindings(sol::state& lua, ScriptContext& ctx)
    {
        (void)ctx;
        {
            auto ns = script_binding::getOrCreateTable(lua, "Time");
            ns.set_function("deltaTime",
                [&ctx]() {
                    return ctx.timingService ? ctx.timingService->updateDeltaTime() : 0.0f;
                });
            ns.set_function("fixedDeltaTime",
                [&ctx]() {
                    return ctx.timingService ? ctx.timingService->fixedDeltaTime() : 0.0f;
                });
            ns.set_function("unscaledDeltaTime",
                [&ctx]() {
                    return ctx.timingService ? ctx.timingService->unscaledDeltaTime() : 0.0f;
                });
            ns.set_function("smoothedDeltaTime",
                [&ctx]() {
                    return ctx.timingService ? ctx.timingService->smoothedDeltaTime() : 0.0f;
                });
            ns.set_function("totalTime",
                [&ctx]() {
                    return ctx.timingService ? ctx.timingService->totalTime() : 0.0f;
                });
            ns.set_function("unscaledTotalTime",
                [&ctx]() {
                    return ctx.timingService ? ctx.timingService->unscaledTotalTime() : 0.0f;
                });
            ns.set_function("averageFrameTime",
                [&ctx]() {
                    return ctx.timingService ? ctx.timingService->averageFrameTime() : 0.0f;
                });
            ns.set_function("framesPerSecond",
                [&ctx]() {
                    return ctx.timingService ? ctx.timingService->framesPerSecond() : 0.0f;
                });
            ns.set_function("timeScale",
                [&ctx]() {
                    return ctx.timingService ? ctx.timingService->timeScale() : 1.0f;
                });
            ns.set_function("fixedAlpha",
                [&ctx]() {
                    return ctx.timingService ? ctx.timingService->fixedAlpha() : 0.0f;
                });
            ns.set_function("fixedStepsThisFrame",
                [&ctx]() {
                    return ctx.timingService ? ctx.timingService->fixedStepsThisFrame() : 0u;
                });
            ns.set_function("frameIndex",
                [&ctx]() {
                    return ctx.timingService ? ctx.timingService->frameIndex() : 0ull;
                });
            ns.set_function("maxDeltaTime",
                [&ctx]() {
                    return ctx.timingService ? ctx.timingService->maxDeltaTime() : 0.0f;
                });
            ns.set_function("setFixedDeltaTime",
                [&ctx](float dt) {
                    if (ctx.timingService) ctx.timingService->setFixedDeltaTime(dt);
                });
            ns.set_function("setTimeScale",
                [&ctx](float scale) {
                    if (ctx.timingService) ctx.timingService->setTimeScale(scale);
                });
            ns.set_function("setMaxFixedStepsPerFrame",
                [&ctx](std::uint32_t maxSteps) {
                    if (ctx.timingService) ctx.timingService->setMaxFixedStepsPerFrame(maxSteps);
                });
            ns.set_function("setMaxDeltaTime",
                [&ctx](float dt) {
                    if (ctx.timingService) ctx.timingService->setMaxDeltaTime(dt);
                });
            ns.set_function("setDeltaSmoothingFactor",
                [&ctx](float factor) {
                    if (ctx.timingService) ctx.timingService->setDeltaSmoothingFactor(factor);
                });
        }

    }
} // namespace vultra
