// GENERATED by tools/python/extract_bindings.py + bindgen.backends.lua_sol2 -- DO NOT EDIT.
// Source of truth: tools/bindings/ir/bindings.ir.json (from VBIND_* annotations).

#include "vultra/function/scripting/bindings/script_input_binding.hpp"

#include "vultra/function/scripting/bindings/script_binding_common.hpp"
#include "vultra/function/scripting/script_context.hpp"
#include "vultra/function/scripting/script_types.hpp"
#include "vultra/core/input/input_structs.hpp"
#include "vultra/core/services/input_service.hpp"

#include <glm/vec2.hpp>

#include <cstdint>
#include <string>

namespace vultra
{
    namespace
    {
        [[maybe_unused]] ScriptVec2 toScript(const glm::vec2& v) { return {v.x, v.y}; }
        [[maybe_unused]] glm::vec2 fromScript(const ScriptVec2& v) { return {v.x, v.y}; }
    } // namespace

    void registerScriptInputBindings(sol::state& lua, ScriptContext& ctx)
    {
        (void)ctx;
        {
            auto ns = script_binding::getOrCreateTable(lua, "Input");
            ns.set_function("isKeyHeld",
                [&ctx](int key) {
                    return ctx.inputService ? ctx.inputService->isKeyHeld(static_cast<vultra::KeyCode>(key)) : false;
                });
            ns.set_function("isKeyPressed",
                [&ctx](int key) {
                    return ctx.inputService ? ctx.inputService->isKeyPressed(static_cast<vultra::KeyCode>(key)) : false;
                });
            ns.set_function("isKeyReleased",
                [&ctx](int key) {
                    return ctx.inputService ? ctx.inputService->isKeyReleased(static_cast<vultra::KeyCode>(key)) : false;
                });
            ns.set_function("isKeyRepeated",
                [&ctx](int key) {
                    return ctx.inputService ? ctx.inputService->isKeyRepeated(static_cast<vultra::KeyCode>(key)) : false;
                });
            ns.set_function("isMouseButtonHeld",
                [&ctx](int button) {
                    return ctx.inputService ? ctx.inputService->isMouseButtonHeld(static_cast<vultra::MouseCode>(button)) : false;
                });
            ns.set_function("isMouseButtonPressed",
                [&ctx](int button) {
                    return ctx.inputService ? ctx.inputService->isMouseButtonPressed(static_cast<vultra::MouseCode>(button)) : false;
                });
            ns.set_function("isMouseButtonReleased",
                [&ctx](int button) {
                    return ctx.inputService ? ctx.inputService->isMouseButtonReleased(static_cast<vultra::MouseCode>(button)) : false;
                });
            ns.set_function("mouseButtonClicks",
                [&ctx](int button) {
                    return ctx.inputService ? ctx.inputService->mouseButtonClicks(static_cast<vultra::MouseCode>(button)) : 0;
                });
            ns.set_function("mousePosition",
                [&ctx]() {
                    return ctx.inputService ? toScript(ctx.inputService->mousePosition()) : ScriptVec2 {};
                });
            ns.set_function("mousePositionFlipY",
                [&ctx]() {
                    return ctx.inputService ? toScript(ctx.inputService->mousePositionFlipY()) : ScriptVec2 {};
                });
            ns.set_function("mousePositionDelta",
                [&ctx]() {
                    return ctx.inputService ? toScript(ctx.inputService->mousePositionDelta()) : ScriptVec2 {};
                });
            ns.set_function("mouseScrollDelta",
                [&ctx]() {
                    return ctx.inputService ? toScript(ctx.inputService->mouseScrollDelta()) : ScriptVec2 {};
                });
            ns.set_function("isGamepadConnected",
                [&ctx]() {
                    return ctx.inputService ? ctx.inputService->isGamepadConnected() : false;
                });
            ns.set_function("isGamepadButtonHeld",
                [&ctx](int button) {
                    return ctx.inputService ? ctx.inputService->isGamepadButtonHeld(static_cast<vultra::GamepadButton>(button)) : false;
                });
            ns.set_function("isGamepadButtonPressed",
                [&ctx](int button) {
                    return ctx.inputService ? ctx.inputService->isGamepadButtonPressed(static_cast<vultra::GamepadButton>(button)) : false;
                });
            ns.set_function("isGamepadButtonReleased",
                [&ctx](int button) {
                    return ctx.inputService ? ctx.inputService->isGamepadButtonReleased(static_cast<vultra::GamepadButton>(button)) : false;
                });
            ns.set_function("gamepadAxis",
                [&ctx](int axis) {
                    return ctx.inputService ? ctx.inputService->gamepadAxis(static_cast<vultra::GamepadAxis>(axis)) : 0.0f;
                });
            ns.set_function("rumble",
                [&ctx](float lowFrequency, float highFrequency, int durationMs) {
                    if (ctx.inputService) ctx.inputService->rumble(lowFrequency, highFrequency, durationMs);
                });
            ns.set_function("touchCount",
                [&ctx]() {
                    return ctx.inputService ? ctx.inputService->touchCount() : 0;
                });
            ns.set_function("touchId",
                [&ctx](int index) {
                    return ctx.inputService ? ctx.inputService->touchId(index) : 0;
                });
            ns.set_function("touchPosition",
                [&ctx](int index) {
                    return ctx.inputService ? toScript(ctx.inputService->touchPosition(index)) : ScriptVec2 {};
                });
            ns.set_function("touchDelta",
                [&ctx](int index) {
                    return ctx.inputService ? toScript(ctx.inputService->touchDelta(index)) : ScriptVec2 {};
                });
            ns.set_function("isTouchPressed",
                [&ctx](int index) {
                    return ctx.inputService ? ctx.inputService->isTouchPressed(index) : false;
                });
            ns.set_function("isTouchReleased",
                [&ctx](int index) {
                    return ctx.inputService ? ctx.inputService->isTouchReleased(index) : false;
                });
            ns.set_function("startTextInput",
                [&ctx]() {
                    if (ctx.inputService) ctx.inputService->startTextInput();
                });
            ns.set_function("stopTextInput",
                [&ctx]() {
                    if (ctx.inputService) ctx.inputService->stopTextInput();
                });
            ns.set_function("textInput",
                [&ctx]() {
                    return ctx.inputService ? ctx.inputService->textInput() : std::string {};
                });
            ns.set_function("hasAction",
                [&ctx](const std::string& action) {
                    return ctx.inputService ? ctx.inputService->hasAction(action) : false;
                });
            ns.set_function("isActionHeld",
                [&ctx](const std::string& action) {
                    return ctx.inputService ? ctx.inputService->isActionHeld(action) : false;
                });
            ns.set_function("isActionPressed",
                [&ctx](const std::string& action) {
                    return ctx.inputService ? ctx.inputService->isActionPressed(action) : false;
                });
            ns.set_function("isActionReleased",
                [&ctx](const std::string& action) {
                    return ctx.inputService ? ctx.inputService->isActionReleased(action) : false;
                });
            ns.set_function("actionAxis",
                [&ctx](const std::string& action) {
                    return ctx.inputService ? ctx.inputService->actionAxis(action) : 0.0f;
                });
            ns.set_function("clearActionEvents",
                [&ctx](const std::string& action) {
                    if (ctx.inputService) ctx.inputService->clearActionEvents(action);
                });
            ns.set_function("bindActionKey",
                [&ctx](const std::string& action, int key) {
                    if (ctx.inputService) ctx.inputService->bindActionKey(action, static_cast<vultra::KeyCode>(key));
                });
            ns.set_function("bindActionMouseButton",
                [&ctx](const std::string& action, int button) {
                    if (ctx.inputService) ctx.inputService->bindActionMouseButton(action, static_cast<vultra::MouseCode>(button));
                });
            ns.set_function("bindActionGamepadButton",
                [&ctx](const std::string& action, int button) {
                    if (ctx.inputService) ctx.inputService->bindActionGamepadButton(action, static_cast<vultra::GamepadButton>(button));
                });
            ns.set_function("bindActionGamepadAxis",
                [&ctx](const std::string& action, int axis, float scale) {
                    if (ctx.inputService) ctx.inputService->bindActionGamepadAxis(action, static_cast<vultra::GamepadAxis>(axis), scale);
                });
        }

        script_binding::bindEnumTable<vultra::KeyCode>(lua, "KeyCode");
        script_binding::bindEnumTable<vultra::MouseCode>(lua, "MouseCode");
        script_binding::bindEnumTable<vultra::GamepadButton>(lua, "GamepadButton");
        script_binding::bindEnumTable<vultra::GamepadAxis>(lua, "GamepadAxis");
    }
} // namespace vultra
