// GENERATED by tools/python/extract_bindings.py + bindgen.backends.lua_sol2 -- DO NOT EDIT.
// Source of truth: tools/bindings/ir/bindings.ir.json (from VBIND_* annotations).

#include "vultra/function/scripting/bindings/script_components_binding.hpp"

#include "vultra/function/scripting/bindings/script_binding_common.hpp"
#include "vultra/function/scripting/script_context.hpp"
#include "vultra/function/scripting/script_types.hpp"
#include "vultra/function/world/world.hpp"
#include "vultra/function/world/components/audio_listener_component.hpp"
#include "vultra/function/world/components/audio_source_component.hpp"
#include "vultra/function/world/components/box_shape_component.hpp"
#include "vultra/function/world/components/camera_component.hpp"
#include "vultra/function/world/components/capsule_shape_component.hpp"
#include "vultra/function/world/components/cylinder_shape_component.hpp"
#include "vultra/function/world/components/environment_component.hpp"
#include "vultra/function/world/components/light_component.hpp"
#include "vultra/function/world/components/nav_agent_component.hpp"
#include "vultra/function/world/components/particle_emitter_component.hpp"
#include "vultra/function/world/components/reflection_probe_component.hpp"
#include "vultra/function/world/components/sphere_shape_component.hpp"
#include "vultra/core/base/uuid.hpp"
#include "vultra/function/scripting/bindings/script_generated_binding.hpp"

#include <glm/vec3.hpp>
#include <glm/vec4.hpp>

#include <cstdint>
#include <stdexcept>
#include <string>

namespace vultra
{
    namespace
    {
        template<typename Component>
        Component& requireComponentRef(ScriptContext& ctx, entt::entity entity, const char* name)
        {
            auto* world = ctx.world();
            if (!world)
                throw std::runtime_error("ScriptContext has no World");
            auto* component = world->registry().try_get<Component>(entity);
            if (!component)
                throw std::runtime_error(std::string("Entity has no ") + name);
            return *component;
        }
        [[maybe_unused]] ScriptVec3 toScript(const glm::vec3& v) { return {v.x, v.y, v.z}; }
        [[maybe_unused]] glm::vec3 fromScript(const ScriptVec3& v) { return {v.x, v.y, v.z}; }
        [[maybe_unused]] ScriptVec4 toScript(const glm::vec4& v) { return {v.x, v.y, v.z, v.w}; }
        [[maybe_unused]] glm::vec4 fromScript(const ScriptVec4& v) { return {v.x, v.y, v.z, v.w}; }
        [[maybe_unused]] std::string uuidToString(const CoreUUID& id)
        {
            return id.valid() ? id.toString() : std::string {};
        }
        [[maybe_unused]] CoreUUID uuidFromString(const std::string& s)
        {
            vbase::UUID uuid {};
            vbase::try_parse_uuid(s.c_str(), uuid);
            return CoreUUID(uuid);
        }
    } // namespace

    void registerScriptComponentsBindings(sol::state& lua, ScriptContext& ctx)
    {
        (void)ctx;
        lua.new_usertype<ScriptAudioListenerRef>(
            "AudioListener",
            "valid",
            script_binding::readonlyProperty([&ctx](const ScriptAudioListenerRef& self) {
                auto* world = ctx.world();
                return world && world->registry().all_of<AudioListenerComponent>(self.entity);
            }),
            "primary",
            script_binding::property([&ctx](const ScriptAudioListenerRef& self) {
                return requireComponentRef<AudioListenerComponent>(ctx, self.entity, "AudioListenerComponent").primary;
            },
            [&ctx](const ScriptAudioListenerRef& self, const bool& value) {
                requireComponentRef<AudioListenerComponent>(ctx, self.entity, "AudioListenerComponent").primary = value;
            }));

        lua.new_usertype<ScriptAudioSourceRef>(
            "AudioSource",
            "valid",
            script_binding::readonlyProperty([&ctx](const ScriptAudioSourceRef& self) {
                auto* world = ctx.world();
                return world && world->registry().all_of<AudioSourceComponent>(self.entity);
            }),
            "clip",
            script_binding::property([&ctx](const ScriptAudioSourceRef& self) {
                return uuidToString(requireComponentRef<AudioSourceComponent>(ctx, self.entity, "AudioSourceComponent").clip);
            },
            [&ctx](const ScriptAudioSourceRef& self, const std::string& value) {
                requireComponentRef<AudioSourceComponent>(ctx, self.entity, "AudioSourceComponent").clip = uuidFromString(value);
            }),
            "volume",
            script_binding::property([&ctx](const ScriptAudioSourceRef& self) {
                return requireComponentRef<AudioSourceComponent>(ctx, self.entity, "AudioSourceComponent").volume;
            },
            [&ctx](const ScriptAudioSourceRef& self, const float& value) {
                requireComponentRef<AudioSourceComponent>(ctx, self.entity, "AudioSourceComponent").volume = value;
            }),
            "pitch",
            script_binding::property([&ctx](const ScriptAudioSourceRef& self) {
                return requireComponentRef<AudioSourceComponent>(ctx, self.entity, "AudioSourceComponent").pitch;
            },
            [&ctx](const ScriptAudioSourceRef& self, const float& value) {
                requireComponentRef<AudioSourceComponent>(ctx, self.entity, "AudioSourceComponent").pitch = value;
            }),
            "loop",
            script_binding::property([&ctx](const ScriptAudioSourceRef& self) {
                return requireComponentRef<AudioSourceComponent>(ctx, self.entity, "AudioSourceComponent").loop;
            },
            [&ctx](const ScriptAudioSourceRef& self, const bool& value) {
                requireComponentRef<AudioSourceComponent>(ctx, self.entity, "AudioSourceComponent").loop = value;
            }),
            "playOnStart",
            script_binding::property([&ctx](const ScriptAudioSourceRef& self) {
                return requireComponentRef<AudioSourceComponent>(ctx, self.entity, "AudioSourceComponent").playOnStart;
            },
            [&ctx](const ScriptAudioSourceRef& self, const bool& value) {
                requireComponentRef<AudioSourceComponent>(ctx, self.entity, "AudioSourceComponent").playOnStart = value;
            }),
            "playing",
            script_binding::property([&ctx](const ScriptAudioSourceRef& self) {
                return requireComponentRef<AudioSourceComponent>(ctx, self.entity, "AudioSourceComponent").playing;
            },
            [&ctx](const ScriptAudioSourceRef& self, const bool& value) {
                requireComponentRef<AudioSourceComponent>(ctx, self.entity, "AudioSourceComponent").playing = value;
            }),
            "spatial",
            script_binding::property([&ctx](const ScriptAudioSourceRef& self) {
                return requireComponentRef<AudioSourceComponent>(ctx, self.entity, "AudioSourceComponent").spatial;
            },
            [&ctx](const ScriptAudioSourceRef& self, const bool& value) {
                requireComponentRef<AudioSourceComponent>(ctx, self.entity, "AudioSourceComponent").spatial = value;
            }),
            "minDistance",
            script_binding::property([&ctx](const ScriptAudioSourceRef& self) {
                return requireComponentRef<AudioSourceComponent>(ctx, self.entity, "AudioSourceComponent").minDistance;
            },
            [&ctx](const ScriptAudioSourceRef& self, const float& value) {
                requireComponentRef<AudioSourceComponent>(ctx, self.entity, "AudioSourceComponent").minDistance = value;
            }),
            "maxDistance",
            script_binding::property([&ctx](const ScriptAudioSourceRef& self) {
                return requireComponentRef<AudioSourceComponent>(ctx, self.entity, "AudioSourceComponent").maxDistance;
            },
            [&ctx](const ScriptAudioSourceRef& self, const float& value) {
                requireComponentRef<AudioSourceComponent>(ctx, self.entity, "AudioSourceComponent").maxDistance = value;
            }),
            "rolloff",
            script_binding::property([&ctx](const ScriptAudioSourceRef& self) {
                return requireComponentRef<AudioSourceComponent>(ctx, self.entity, "AudioSourceComponent").rolloff;
            },
            [&ctx](const ScriptAudioSourceRef& self, const float& value) {
                requireComponentRef<AudioSourceComponent>(ctx, self.entity, "AudioSourceComponent").rolloff = value;
            }));

        lua.new_usertype<ScriptBoxShapeRef>(
            "BoxShape",
            "valid",
            script_binding::readonlyProperty([&ctx](const ScriptBoxShapeRef& self) {
                auto* world = ctx.world();
                return world && world->registry().all_of<BoxShapeComponent>(self.entity);
            }),
            "halfExtents",
            script_binding::property([&ctx](const ScriptBoxShapeRef& self) {
                return toScript(requireComponentRef<BoxShapeComponent>(ctx, self.entity, "BoxShapeComponent").halfExtents);
            },
            [&ctx](const ScriptBoxShapeRef& self, const ScriptVec3& value) {
                requireComponentRef<BoxShapeComponent>(ctx, self.entity, "BoxShapeComponent").halfExtents = fromScript(value);
            }));

        lua.new_usertype<ScriptCameraRef>(
            "CameraRef",
            "valid",
            script_binding::readonlyProperty([&ctx](const ScriptCameraRef& self) {
                auto* world = ctx.world();
                return world && world->registry().all_of<CameraComponent>(self.entity);
            }),
            "primary",
            script_binding::property([&ctx](const ScriptCameraRef& self) {
                return requireComponentRef<CameraComponent>(ctx, self.entity, "CameraComponent").primary;
            },
            [&ctx](const ScriptCameraRef& self, const bool& value) {
                requireComponentRef<CameraComponent>(ctx, self.entity, "CameraComponent").primary = value;
            }),
            "projection",
            script_binding::property([&ctx](const ScriptCameraRef& self) {
                return requireComponentRef<CameraComponent>(ctx, self.entity, "CameraComponent").projection;
            },
            [&ctx](const ScriptCameraRef& self, const std::uint32_t& value) {
                requireComponentRef<CameraComponent>(ctx, self.entity, "CameraComponent").projection = value;
            }),
            "fovY",
            script_binding::property([&ctx](const ScriptCameraRef& self) {
                return requireComponentRef<CameraComponent>(ctx, self.entity, "CameraComponent").fovY;
            },
            [&ctx](const ScriptCameraRef& self, const float& value) {
                requireComponentRef<CameraComponent>(ctx, self.entity, "CameraComponent").fovY = value;
            }),
            "fovYDegrees",
            script_binding::property([&ctx](const ScriptCameraRef& self) {
                script_binding::warnDeprecated("CameraRef.fovYDegrees", "CameraRef.fovY");
                return requireComponentRef<CameraComponent>(ctx, self.entity, "CameraComponent").fovY;
            },
            [&ctx](const ScriptCameraRef& self, const float& value) {
                script_binding::warnDeprecated("CameraRef.fovYDegrees", "CameraRef.fovY");
                requireComponentRef<CameraComponent>(ctx, self.entity, "CameraComponent").fovY = value;
            }),
            "orthographicHeight",
            script_binding::property([&ctx](const ScriptCameraRef& self) {
                return requireComponentRef<CameraComponent>(ctx, self.entity, "CameraComponent").orthographicHeight;
            },
            [&ctx](const ScriptCameraRef& self, const float& value) {
                requireComponentRef<CameraComponent>(ctx, self.entity, "CameraComponent").orthographicHeight = value;
            }),
            "zNear",
            script_binding::property([&ctx](const ScriptCameraRef& self) {
                return requireComponentRef<CameraComponent>(ctx, self.entity, "CameraComponent").zNear;
            },
            [&ctx](const ScriptCameraRef& self, const float& value) {
                requireComponentRef<CameraComponent>(ctx, self.entity, "CameraComponent").zNear = value;
            }),
            "zFar",
            script_binding::property([&ctx](const ScriptCameraRef& self) {
                return requireComponentRef<CameraComponent>(ctx, self.entity, "CameraComponent").zFar;
            },
            [&ctx](const ScriptCameraRef& self, const float& value) {
                requireComponentRef<CameraComponent>(ctx, self.entity, "CameraComponent").zFar = value;
            }),
            "clearMode",
            script_binding::property([&ctx](const ScriptCameraRef& self) {
                return requireComponentRef<CameraComponent>(ctx, self.entity, "CameraComponent").clearMode;
            },
            [&ctx](const ScriptCameraRef& self, const std::uint32_t& value) {
                requireComponentRef<CameraComponent>(ctx, self.entity, "CameraComponent").clearMode = value;
            }),
            "clearColor",
            script_binding::property([&ctx](const ScriptCameraRef& self) {
                return toScript(requireComponentRef<CameraComponent>(ctx, self.entity, "CameraComponent").clearColor);
            },
            [&ctx](const ScriptCameraRef& self, const ScriptVec4& value) {
                requireComponentRef<CameraComponent>(ctx, self.entity, "CameraComponent").clearColor = fromScript(value);
            }),
            "priority",
            script_binding::property([&ctx](const ScriptCameraRef& self) {
                return requireComponentRef<CameraComponent>(ctx, self.entity, "CameraComponent").priority;
            },
            [&ctx](const ScriptCameraRef& self, const int& value) {
                requireComponentRef<CameraComponent>(ctx, self.entity, "CameraComponent").priority = value;
            }),
            "cullingMask",
            script_binding::property([&ctx](const ScriptCameraRef& self) {
                return requireComponentRef<CameraComponent>(ctx, self.entity, "CameraComponent").cullingMask;
            },
            [&ctx](const ScriptCameraRef& self, const std::uint32_t& value) {
                requireComponentRef<CameraComponent>(ctx, self.entity, "CameraComponent").cullingMask = value;
            }),
            "rendererKey",
            script_binding::property([&ctx](const ScriptCameraRef& self) {
                return requireComponentRef<CameraComponent>(ctx, self.entity, "CameraComponent").rendererKey;
            },
            [&ctx](const ScriptCameraRef& self, const std::string& value) {
                requireComponentRef<CameraComponent>(ctx, self.entity, "CameraComponent").rendererKey = value;
            }));

        lua.new_usertype<ScriptCapsuleShapeRef>(
            "CapsuleShape",
            "valid",
            script_binding::readonlyProperty([&ctx](const ScriptCapsuleShapeRef& self) {
                auto* world = ctx.world();
                return world && world->registry().all_of<CapsuleShapeComponent>(self.entity);
            }),
            "halfHeightOfCylinder",
            script_binding::property([&ctx](const ScriptCapsuleShapeRef& self) {
                return requireComponentRef<CapsuleShapeComponent>(ctx, self.entity, "CapsuleShapeComponent").halfHeightOfCylinder;
            },
            [&ctx](const ScriptCapsuleShapeRef& self, const float& value) {
                requireComponentRef<CapsuleShapeComponent>(ctx, self.entity, "CapsuleShapeComponent").halfHeightOfCylinder = value;
            }),
            "radius",
            script_binding::property([&ctx](const ScriptCapsuleShapeRef& self) {
                return requireComponentRef<CapsuleShapeComponent>(ctx, self.entity, "CapsuleShapeComponent").radius;
            },
            [&ctx](const ScriptCapsuleShapeRef& self, const float& value) {
                requireComponentRef<CapsuleShapeComponent>(ctx, self.entity, "CapsuleShapeComponent").radius = value;
            }));

        lua.new_usertype<ScriptCylinderShapeRef>(
            "CylinderShape",
            "valid",
            script_binding::readonlyProperty([&ctx](const ScriptCylinderShapeRef& self) {
                auto* world = ctx.world();
                return world && world->registry().all_of<CylinderShapeComponent>(self.entity);
            }),
            "halfHeight",
            script_binding::property([&ctx](const ScriptCylinderShapeRef& self) {
                return requireComponentRef<CylinderShapeComponent>(ctx, self.entity, "CylinderShapeComponent").halfHeight;
            },
            [&ctx](const ScriptCylinderShapeRef& self, const float& value) {
                requireComponentRef<CylinderShapeComponent>(ctx, self.entity, "CylinderShapeComponent").halfHeight = value;
            }),
            "radius",
            script_binding::property([&ctx](const ScriptCylinderShapeRef& self) {
                return requireComponentRef<CylinderShapeComponent>(ctx, self.entity, "CylinderShapeComponent").radius;
            },
            [&ctx](const ScriptCylinderShapeRef& self, const float& value) {
                requireComponentRef<CylinderShapeComponent>(ctx, self.entity, "CylinderShapeComponent").radius = value;
            }));

        lua.new_usertype<ScriptEnvironmentRef>(
            "Environment",
            "valid",
            script_binding::readonlyProperty([&ctx](const ScriptEnvironmentRef& self) {
                auto* world = ctx.world();
                return world && world->registry().all_of<EnvironmentComponent>(self.entity);
            }),
            "active",
            script_binding::property([&ctx](const ScriptEnvironmentRef& self) {
                return requireComponentRef<EnvironmentComponent>(ctx, self.entity, "EnvironmentComponent").active;
            },
            [&ctx](const ScriptEnvironmentRef& self, const bool& value) {
                requireComponentRef<EnvironmentComponent>(ctx, self.entity, "EnvironmentComponent").active = value;
            }),
            "skybox",
            script_binding::property([&ctx](const ScriptEnvironmentRef& self) {
                return uuidToString(requireComponentRef<EnvironmentComponent>(ctx, self.entity, "EnvironmentComponent").skybox);
            },
            [&ctx](const ScriptEnvironmentRef& self, const std::string& value) {
                requireComponentRef<EnvironmentComponent>(ctx, self.entity, "EnvironmentComponent").skybox = uuidFromString(value);
            }),
            "ambientColor",
            script_binding::property([&ctx](const ScriptEnvironmentRef& self) {
                return toScript(requireComponentRef<EnvironmentComponent>(ctx, self.entity, "EnvironmentComponent").ambientColor);
            },
            [&ctx](const ScriptEnvironmentRef& self, const ScriptVec3& value) {
                requireComponentRef<EnvironmentComponent>(ctx, self.entity, "EnvironmentComponent").ambientColor = fromScript(value);
            }),
            "ambientIntensity",
            script_binding::property([&ctx](const ScriptEnvironmentRef& self) {
                return requireComponentRef<EnvironmentComponent>(ctx, self.entity, "EnvironmentComponent").ambientIntensity;
            },
            [&ctx](const ScriptEnvironmentRef& self, const float& value) {
                requireComponentRef<EnvironmentComponent>(ctx, self.entity, "EnvironmentComponent").ambientIntensity = value;
            }),
            "enableIBL",
            script_binding::property([&ctx](const ScriptEnvironmentRef& self) {
                return requireComponentRef<EnvironmentComponent>(ctx, self.entity, "EnvironmentComponent").enableIBL;
            },
            [&ctx](const ScriptEnvironmentRef& self, const bool& value) {
                requireComponentRef<EnvironmentComponent>(ctx, self.entity, "EnvironmentComponent").enableIBL = value;
            }),
            "iblColor",
            script_binding::property([&ctx](const ScriptEnvironmentRef& self) {
                return toScript(requireComponentRef<EnvironmentComponent>(ctx, self.entity, "EnvironmentComponent").iblColor);
            },
            [&ctx](const ScriptEnvironmentRef& self, const ScriptVec3& value) {
                requireComponentRef<EnvironmentComponent>(ctx, self.entity, "EnvironmentComponent").iblColor = fromScript(value);
            }),
            "iblIntensity",
            script_binding::property([&ctx](const ScriptEnvironmentRef& self) {
                return requireComponentRef<EnvironmentComponent>(ctx, self.entity, "EnvironmentComponent").iblIntensity;
            },
            [&ctx](const ScriptEnvironmentRef& self, const float& value) {
                requireComponentRef<EnvironmentComponent>(ctx, self.entity, "EnvironmentComponent").iblIntensity = value;
            }));

        lua.new_usertype<ScriptLightRef>(
            "Light",
            "valid",
            script_binding::readonlyProperty([&ctx](const ScriptLightRef& self) {
                auto* world = ctx.world();
                return world && world->registry().all_of<LightComponent>(self.entity);
            }),
            "kind",
            script_binding::property([&ctx](const ScriptLightRef& self) {
                return requireComponentRef<LightComponent>(ctx, self.entity, "LightComponent").kind;
            },
            [&ctx](const ScriptLightRef& self, const std::uint32_t& value) {
                requireComponentRef<LightComponent>(ctx, self.entity, "LightComponent").kind = value;
            }),
            "color",
            script_binding::property([&ctx](const ScriptLightRef& self) {
                return toScript(requireComponentRef<LightComponent>(ctx, self.entity, "LightComponent").color);
            },
            [&ctx](const ScriptLightRef& self, const ScriptVec3& value) {
                requireComponentRef<LightComponent>(ctx, self.entity, "LightComponent").color = fromScript(value);
            }),
            "intensity",
            script_binding::property([&ctx](const ScriptLightRef& self) {
                return requireComponentRef<LightComponent>(ctx, self.entity, "LightComponent").intensity;
            },
            [&ctx](const ScriptLightRef& self, const float& value) {
                requireComponentRef<LightComponent>(ctx, self.entity, "LightComponent").intensity = value;
            }),
            "range",
            script_binding::property([&ctx](const ScriptLightRef& self) {
                return requireComponentRef<LightComponent>(ctx, self.entity, "LightComponent").range;
            },
            [&ctx](const ScriptLightRef& self, const float& value) {
                requireComponentRef<LightComponent>(ctx, self.entity, "LightComponent").range = value;
            }),
            "radius",
            script_binding::property([&ctx](const ScriptLightRef& self) {
                return requireComponentRef<LightComponent>(ctx, self.entity, "LightComponent").radius;
            },
            [&ctx](const ScriptLightRef& self, const float& value) {
                requireComponentRef<LightComponent>(ctx, self.entity, "LightComponent").radius = value;
            }),
            "width",
            script_binding::property([&ctx](const ScriptLightRef& self) {
                return requireComponentRef<LightComponent>(ctx, self.entity, "LightComponent").width;
            },
            [&ctx](const ScriptLightRef& self, const float& value) {
                requireComponentRef<LightComponent>(ctx, self.entity, "LightComponent").width = value;
            }),
            "height",
            script_binding::property([&ctx](const ScriptLightRef& self) {
                return requireComponentRef<LightComponent>(ctx, self.entity, "LightComponent").height;
            },
            [&ctx](const ScriptLightRef& self, const float& value) {
                requireComponentRef<LightComponent>(ctx, self.entity, "LightComponent").height = value;
            }),
            "castsShadow",
            script_binding::property([&ctx](const ScriptLightRef& self) {
                return requireComponentRef<LightComponent>(ctx, self.entity, "LightComponent").castsShadow;
            },
            [&ctx](const ScriptLightRef& self, const bool& value) {
                requireComponentRef<LightComponent>(ctx, self.entity, "LightComponent").castsShadow = value;
            }),
            "twoSided",
            script_binding::property([&ctx](const ScriptLightRef& self) {
                return requireComponentRef<LightComponent>(ctx, self.entity, "LightComponent").twoSided;
            },
            [&ctx](const ScriptLightRef& self, const bool& value) {
                requireComponentRef<LightComponent>(ctx, self.entity, "LightComponent").twoSided = value;
            }));

        lua.new_usertype<ScriptNavAgentRef>(
            "NavAgent",
            "valid",
            script_binding::readonlyProperty([&ctx](const ScriptNavAgentRef& self) {
                auto* world = ctx.world();
                return world && world->registry().all_of<NavAgentComponent>(self.entity);
            }),
            "radius",
            script_binding::property([&ctx](const ScriptNavAgentRef& self) {
                return requireComponentRef<NavAgentComponent>(ctx, self.entity, "NavAgentComponent").radius;
            },
            [&ctx](const ScriptNavAgentRef& self, const float& value) {
                requireComponentRef<NavAgentComponent>(ctx, self.entity, "NavAgentComponent").radius = value;
            }),
            "height",
            script_binding::property([&ctx](const ScriptNavAgentRef& self) {
                return requireComponentRef<NavAgentComponent>(ctx, self.entity, "NavAgentComponent").height;
            },
            [&ctx](const ScriptNavAgentRef& self, const float& value) {
                requireComponentRef<NavAgentComponent>(ctx, self.entity, "NavAgentComponent").height = value;
            }),
            "speed",
            script_binding::property([&ctx](const ScriptNavAgentRef& self) {
                return requireComponentRef<NavAgentComponent>(ctx, self.entity, "NavAgentComponent").speed;
            },
            [&ctx](const ScriptNavAgentRef& self, const float& value) {
                requireComponentRef<NavAgentComponent>(ctx, self.entity, "NavAgentComponent").speed = value;
            }),
            "stoppingDistance",
            script_binding::property([&ctx](const ScriptNavAgentRef& self) {
                return requireComponentRef<NavAgentComponent>(ctx, self.entity, "NavAgentComponent").stoppingDistance;
            },
            [&ctx](const ScriptNavAgentRef& self, const float& value) {
                requireComponentRef<NavAgentComponent>(ctx, self.entity, "NavAgentComponent").stoppingDistance = value;
            }),
            "targetPosition",
            script_binding::property([&ctx](const ScriptNavAgentRef& self) {
                return toScript(requireComponentRef<NavAgentComponent>(ctx, self.entity, "NavAgentComponent").targetPosition);
            },
            [&ctx](const ScriptNavAgentRef& self, const ScriptVec3& value) {
                requireComponentRef<NavAgentComponent>(ctx, self.entity, "NavAgentComponent").targetPosition = fromScript(value);
            }),
            "hasTarget",
            script_binding::property([&ctx](const ScriptNavAgentRef& self) {
                return requireComponentRef<NavAgentComponent>(ctx, self.entity, "NavAgentComponent").hasTarget;
            },
            [&ctx](const ScriptNavAgentRef& self, const bool& value) {
                requireComponentRef<NavAgentComponent>(ctx, self.entity, "NavAgentComponent").hasTarget = value;
            }),
            "moving",
            script_binding::readonlyProperty([&ctx](const ScriptNavAgentRef& self) {
                return requireComponentRef<NavAgentComponent>(ctx, self.entity, "NavAgentComponent").moving;
            }));

        lua.new_usertype<ScriptParticleEmitterRef>(
            "ParticleEmitter",
            "valid",
            script_binding::readonlyProperty([&ctx](const ScriptParticleEmitterRef& self) {
                auto* world = ctx.world();
                return world && world->registry().all_of<ParticleEmitterComponent>(self.entity);
            }),
            "playing",
            script_binding::property([&ctx](const ScriptParticleEmitterRef& self) {
                return requireComponentRef<ParticleEmitterComponent>(ctx, self.entity, "ParticleEmitterComponent").playing;
            },
            [&ctx](const ScriptParticleEmitterRef& self, const bool& value) {
                requireComponentRef<ParticleEmitterComponent>(ctx, self.entity, "ParticleEmitterComponent").playing = value;
            }),
            "worldSpace",
            script_binding::property([&ctx](const ScriptParticleEmitterRef& self) {
                return requireComponentRef<ParticleEmitterComponent>(ctx, self.entity, "ParticleEmitterComponent").worldSpace;
            },
            [&ctx](const ScriptParticleEmitterRef& self, const bool& value) {
                requireComponentRef<ParticleEmitterComponent>(ctx, self.entity, "ParticleEmitterComponent").worldSpace = value;
            }),
            "gpu",
            script_binding::property([&ctx](const ScriptParticleEmitterRef& self) {
                return requireComponentRef<ParticleEmitterComponent>(ctx, self.entity, "ParticleEmitterComponent").gpu;
            },
            [&ctx](const ScriptParticleEmitterRef& self, const bool& value) {
                requireComponentRef<ParticleEmitterComponent>(ctx, self.entity, "ParticleEmitterComponent").gpu = value;
            }),
            "maxParticles",
            script_binding::property([&ctx](const ScriptParticleEmitterRef& self) {
                return requireComponentRef<ParticleEmitterComponent>(ctx, self.entity, "ParticleEmitterComponent").maxParticles;
            },
            [&ctx](const ScriptParticleEmitterRef& self, const std::uint32_t& value) {
                requireComponentRef<ParticleEmitterComponent>(ctx, self.entity, "ParticleEmitterComponent").maxParticles = value;
            }),
            "emissionRate",
            script_binding::property([&ctx](const ScriptParticleEmitterRef& self) {
                return requireComponentRef<ParticleEmitterComponent>(ctx, self.entity, "ParticleEmitterComponent").emissionRate;
            },
            [&ctx](const ScriptParticleEmitterRef& self, const float& value) {
                requireComponentRef<ParticleEmitterComponent>(ctx, self.entity, "ParticleEmitterComponent").emissionRate = value;
            }),
            "lifetime",
            script_binding::property([&ctx](const ScriptParticleEmitterRef& self) {
                return requireComponentRef<ParticleEmitterComponent>(ctx, self.entity, "ParticleEmitterComponent").lifetime;
            },
            [&ctx](const ScriptParticleEmitterRef& self, const float& value) {
                requireComponentRef<ParticleEmitterComponent>(ctx, self.entity, "ParticleEmitterComponent").lifetime = value;
            }),
            "lifetimeVariance",
            script_binding::property([&ctx](const ScriptParticleEmitterRef& self) {
                return requireComponentRef<ParticleEmitterComponent>(ctx, self.entity, "ParticleEmitterComponent").lifetimeVariance;
            },
            [&ctx](const ScriptParticleEmitterRef& self, const float& value) {
                requireComponentRef<ParticleEmitterComponent>(ctx, self.entity, "ParticleEmitterComponent").lifetimeVariance = value;
            }),
            "spawnRadius",
            script_binding::property([&ctx](const ScriptParticleEmitterRef& self) {
                return requireComponentRef<ParticleEmitterComponent>(ctx, self.entity, "ParticleEmitterComponent").spawnRadius;
            },
            [&ctx](const ScriptParticleEmitterRef& self, const float& value) {
                requireComponentRef<ParticleEmitterComponent>(ctx, self.entity, "ParticleEmitterComponent").spawnRadius = value;
            }),
            "startVelocity",
            script_binding::property([&ctx](const ScriptParticleEmitterRef& self) {
                return toScript(requireComponentRef<ParticleEmitterComponent>(ctx, self.entity, "ParticleEmitterComponent").startVelocity);
            },
            [&ctx](const ScriptParticleEmitterRef& self, const ScriptVec3& value) {
                requireComponentRef<ParticleEmitterComponent>(ctx, self.entity, "ParticleEmitterComponent").startVelocity = fromScript(value);
            }),
            "velocityVariance",
            script_binding::property([&ctx](const ScriptParticleEmitterRef& self) {
                return requireComponentRef<ParticleEmitterComponent>(ctx, self.entity, "ParticleEmitterComponent").velocityVariance;
            },
            [&ctx](const ScriptParticleEmitterRef& self, const float& value) {
                requireComponentRef<ParticleEmitterComponent>(ctx, self.entity, "ParticleEmitterComponent").velocityVariance = value;
            }),
            "gravity",
            script_binding::property([&ctx](const ScriptParticleEmitterRef& self) {
                return toScript(requireComponentRef<ParticleEmitterComponent>(ctx, self.entity, "ParticleEmitterComponent").gravity);
            },
            [&ctx](const ScriptParticleEmitterRef& self, const ScriptVec3& value) {
                requireComponentRef<ParticleEmitterComponent>(ctx, self.entity, "ParticleEmitterComponent").gravity = fromScript(value);
            }),
            "startSize",
            script_binding::property([&ctx](const ScriptParticleEmitterRef& self) {
                return requireComponentRef<ParticleEmitterComponent>(ctx, self.entity, "ParticleEmitterComponent").startSize;
            },
            [&ctx](const ScriptParticleEmitterRef& self, const float& value) {
                requireComponentRef<ParticleEmitterComponent>(ctx, self.entity, "ParticleEmitterComponent").startSize = value;
            }),
            "endSize",
            script_binding::property([&ctx](const ScriptParticleEmitterRef& self) {
                return requireComponentRef<ParticleEmitterComponent>(ctx, self.entity, "ParticleEmitterComponent").endSize;
            },
            [&ctx](const ScriptParticleEmitterRef& self, const float& value) {
                requireComponentRef<ParticleEmitterComponent>(ctx, self.entity, "ParticleEmitterComponent").endSize = value;
            }),
            "startColor",
            script_binding::property([&ctx](const ScriptParticleEmitterRef& self) {
                return toScript(requireComponentRef<ParticleEmitterComponent>(ctx, self.entity, "ParticleEmitterComponent").startColor);
            },
            [&ctx](const ScriptParticleEmitterRef& self, const ScriptVec4& value) {
                requireComponentRef<ParticleEmitterComponent>(ctx, self.entity, "ParticleEmitterComponent").startColor = fromScript(value);
            }),
            "endColor",
            script_binding::property([&ctx](const ScriptParticleEmitterRef& self) {
                return toScript(requireComponentRef<ParticleEmitterComponent>(ctx, self.entity, "ParticleEmitterComponent").endColor);
            },
            [&ctx](const ScriptParticleEmitterRef& self, const ScriptVec4& value) {
                requireComponentRef<ParticleEmitterComponent>(ctx, self.entity, "ParticleEmitterComponent").endColor = fromScript(value);
            }));

        lua.new_usertype<ScriptReflectionProbeRef>(
            "ReflectionProbe",
            "valid",
            script_binding::readonlyProperty([&ctx](const ScriptReflectionProbeRef& self) {
                auto* world = ctx.world();
                return world && world->registry().all_of<ReflectionProbeComponent>(self.entity);
            }),
            "active",
            script_binding::property([&ctx](const ScriptReflectionProbeRef& self) {
                return requireComponentRef<ReflectionProbeComponent>(ctx, self.entity, "ReflectionProbeComponent").active;
            },
            [&ctx](const ScriptReflectionProbeRef& self, const bool& value) {
                requireComponentRef<ReflectionProbeComponent>(ctx, self.entity, "ReflectionProbeComponent").active = value;
            }),
            "enableIBL",
            script_binding::property([&ctx](const ScriptReflectionProbeRef& self) {
                return requireComponentRef<ReflectionProbeComponent>(ctx, self.entity, "ReflectionProbeComponent").enableIBL;
            },
            [&ctx](const ScriptReflectionProbeRef& self, const bool& value) {
                requireComponentRef<ReflectionProbeComponent>(ctx, self.entity, "ReflectionProbeComponent").enableIBL = value;
            }),
            "environmentMap",
            script_binding::property([&ctx](const ScriptReflectionProbeRef& self) {
                return uuidToString(requireComponentRef<ReflectionProbeComponent>(ctx, self.entity, "ReflectionProbeComponent").environmentMap);
            },
            [&ctx](const ScriptReflectionProbeRef& self, const std::string& value) {
                requireComponentRef<ReflectionProbeComponent>(ctx, self.entity, "ReflectionProbeComponent").environmentMap = uuidFromString(value);
            }),
            "shape",
            script_binding::property([&ctx](const ScriptReflectionProbeRef& self) {
                return requireComponentRef<ReflectionProbeComponent>(ctx, self.entity, "ReflectionProbeComponent").shape;
            },
            [&ctx](const ScriptReflectionProbeRef& self, const std::uint32_t& value) {
                requireComponentRef<ReflectionProbeComponent>(ctx, self.entity, "ReflectionProbeComponent").shape = value;
            }),
            "boxSize",
            script_binding::property([&ctx](const ScriptReflectionProbeRef& self) {
                return toScript(requireComponentRef<ReflectionProbeComponent>(ctx, self.entity, "ReflectionProbeComponent").boxSize);
            },
            [&ctx](const ScriptReflectionProbeRef& self, const ScriptVec3& value) {
                requireComponentRef<ReflectionProbeComponent>(ctx, self.entity, "ReflectionProbeComponent").boxSize = fromScript(value);
            }),
            "radius",
            script_binding::property([&ctx](const ScriptReflectionProbeRef& self) {
                return requireComponentRef<ReflectionProbeComponent>(ctx, self.entity, "ReflectionProbeComponent").radius;
            },
            [&ctx](const ScriptReflectionProbeRef& self, const float& value) {
                requireComponentRef<ReflectionProbeComponent>(ctx, self.entity, "ReflectionProbeComponent").radius = value;
            }),
            "blendDistance",
            script_binding::property([&ctx](const ScriptReflectionProbeRef& self) {
                return requireComponentRef<ReflectionProbeComponent>(ctx, self.entity, "ReflectionProbeComponent").blendDistance;
            },
            [&ctx](const ScriptReflectionProbeRef& self, const float& value) {
                requireComponentRef<ReflectionProbeComponent>(ctx, self.entity, "ReflectionProbeComponent").blendDistance = value;
            }),
            "intensity",
            script_binding::property([&ctx](const ScriptReflectionProbeRef& self) {
                return requireComponentRef<ReflectionProbeComponent>(ctx, self.entity, "ReflectionProbeComponent").intensity;
            },
            [&ctx](const ScriptReflectionProbeRef& self, const float& value) {
                requireComponentRef<ReflectionProbeComponent>(ctx, self.entity, "ReflectionProbeComponent").intensity = value;
            }),
            "priority",
            script_binding::property([&ctx](const ScriptReflectionProbeRef& self) {
                return requireComponentRef<ReflectionProbeComponent>(ctx, self.entity, "ReflectionProbeComponent").priority;
            },
            [&ctx](const ScriptReflectionProbeRef& self, const int& value) {
                requireComponentRef<ReflectionProbeComponent>(ctx, self.entity, "ReflectionProbeComponent").priority = value;
            }),
            "parallaxCorrection",
            script_binding::property([&ctx](const ScriptReflectionProbeRef& self) {
                return requireComponentRef<ReflectionProbeComponent>(ctx, self.entity, "ReflectionProbeComponent").parallaxCorrection;
            },
            [&ctx](const ScriptReflectionProbeRef& self, const bool& value) {
                requireComponentRef<ReflectionProbeComponent>(ctx, self.entity, "ReflectionProbeComponent").parallaxCorrection = value;
            }));

        lua.new_usertype<ScriptSphereShapeRef>(
            "SphereShape",
            "valid",
            script_binding::readonlyProperty([&ctx](const ScriptSphereShapeRef& self) {
                auto* world = ctx.world();
                return world && world->registry().all_of<SphereShapeComponent>(self.entity);
            }),
            "radius",
            script_binding::property([&ctx](const ScriptSphereShapeRef& self) {
                return requireComponentRef<SphereShapeComponent>(ctx, self.entity, "SphereShapeComponent").radius;
            },
            [&ctx](const ScriptSphereShapeRef& self, const float& value) {
                requireComponentRef<SphereShapeComponent>(ctx, self.entity, "SphereShapeComponent").radius = value;
            }));

    }

    void applyGeneratedEntityAccessors(sol::usertype<ScriptEntity>& entityType, ScriptContext& ctx)
    {
        entityType["navAgent"] =
            sol::readonly_property([](const ScriptEntity& self) { return ScriptNavAgentRef {self.value}; });
        entityType["hasNavAgent"] = [&ctx](const ScriptEntity& self) {
            auto* world = ctx.world();
            return world && ctx.isValid(self.value) && world->registry().all_of<NavAgentComponent>(self.value);
        };
    }
} // namespace vultra
