// GENERATED by tools/python/gen_lua_bindings.py -- DO NOT EDIT.
// Source of truth: VLUA_* annotations in the component headers below.

#include "vultra/function/scripting/bindings/script_generated_binding.hpp"

#include "vultra/function/scripting/bindings/script_binding_common.hpp"
#include "vultra/function/scripting/script_types.hpp"
#include "vultra/function/world/world.hpp"
#include "vultra/core/base/uuid.hpp"
#include "vultra/function/world/components/audio_listener_component.hpp"
#include "vultra/function/world/components/audio_source_component.hpp"
#include "vultra/function/world/components/box_shape_component.hpp"
#include "vultra/function/world/components/camera_component.hpp"
#include "vultra/function/world/components/capsule_shape_component.hpp"
#include "vultra/function/world/components/cylinder_shape_component.hpp"
#include "vultra/function/world/components/environment_component.hpp"
#include "vultra/function/world/components/light_component.hpp"
#include "vultra/function/world/components/particle_emitter_component.hpp"
#include "vultra/function/world/components/reflection_probe_component.hpp"
#include "vultra/function/world/components/sphere_shape_component.hpp"

#include <glm/vec2.hpp>
#include <glm/vec3.hpp>
#include <glm/vec4.hpp>

#include <cstdint>
#include <stdexcept>
#include <string>

namespace vultra
{
    namespace
    {
        template<typename Component>
        Component& requireComponentRef(ScriptContext& ctx, entt::entity entity, const char* name)
        {
            auto* world = ctx.world();
            if (!world)
                throw std::runtime_error("ScriptContext has no World");
            auto* component = world->registry().try_get<Component>(entity);
            if (!component)
                throw std::runtime_error(std::string("Entity has no ") + name);
            return *component;
        }

        [[maybe_unused]] ScriptVec2 toScript(const glm::vec2& v) { return {v.x, v.y}; }
        [[maybe_unused]] ScriptVec3 toScript(const glm::vec3& v) { return {v.x, v.y, v.z}; }
        [[maybe_unused]] ScriptVec4 toScript(const glm::vec4& v) { return {v.x, v.y, v.z, v.w}; }
        [[maybe_unused]] glm::vec2 fromScript(const ScriptVec2& v) { return {v.x, v.y}; }
        [[maybe_unused]] glm::vec3 fromScript(const ScriptVec3& v) { return {v.x, v.y, v.z}; }
        [[maybe_unused]] glm::vec4 fromScript(const ScriptVec4& v) { return {v.x, v.y, v.z, v.w}; }

        [[maybe_unused]] std::string uuidToString(const CoreUUID& id)
        {
            return id.valid() ? id.toString() : std::string {};
        }
        [[maybe_unused]] CoreUUID uuidFromString(const std::string& s)
        {
            vbase::UUID uuid {};
            vbase::try_parse_uuid(s.c_str(), uuid);
            return CoreUUID(uuid);
        }
    } // namespace

    void registerGeneratedComponentBindings(sol::state& lua, ScriptContext& ctx)
    {
        lua.new_usertype<ScriptAudioListenerRef>(
            "AudioListener",
            "valid",
            VULTRA_LUA_READONLY_PROPERTY([&ctx](const ScriptAudioListenerRef& self) {
                auto* world = ctx.world();
                return world && world->registry().all_of<AudioListenerComponent>(self.entity);
            }),
            "primary",
            VULTRA_LUA_PROPERTY([&ctx](const ScriptAudioListenerRef& self) {
                return requireComponentRef<AudioListenerComponent>(ctx, self.entity, "AudioListenerComponent").primary;
            },
            [&ctx](const ScriptAudioListenerRef& self, const bool& value) {
                requireComponentRef<AudioListenerComponent>(ctx, self.entity, "AudioListenerComponent").primary = value;
            }));

        lua.new_usertype<ScriptAudioSourceRef>(
            "AudioSource",
            "valid",
            VULTRA_LUA_READONLY_PROPERTY([&ctx](const ScriptAudioSourceRef& self) {
                auto* world = ctx.world();
                return world && world->registry().all_of<AudioSourceComponent>(self.entity);
            }),
            "clip",
            VULTRA_LUA_PROPERTY([&ctx](const ScriptAudioSourceRef& self) {
                return uuidToString(requireComponentRef<AudioSourceComponent>(ctx, self.entity, "AudioSourceComponent").clip);
            },
            [&ctx](const ScriptAudioSourceRef& self, const std::string& value) {
                requireComponentRef<AudioSourceComponent>(ctx, self.entity, "AudioSourceComponent").clip = uuidFromString(value);
            }),
            "volume",
            VULTRA_LUA_PROPERTY([&ctx](const ScriptAudioSourceRef& self) {
                return requireComponentRef<AudioSourceComponent>(ctx, self.entity, "AudioSourceComponent").volume;
            },
            [&ctx](const ScriptAudioSourceRef& self, const float& value) {
                requireComponentRef<AudioSourceComponent>(ctx, self.entity, "AudioSourceComponent").volume = value;
            }),
            "pitch",
            VULTRA_LUA_PROPERTY([&ctx](const ScriptAudioSourceRef& self) {
                return requireComponentRef<AudioSourceComponent>(ctx, self.entity, "AudioSourceComponent").pitch;
            },
            [&ctx](const ScriptAudioSourceRef& self, const float& value) {
                requireComponentRef<AudioSourceComponent>(ctx, self.entity, "AudioSourceComponent").pitch = value;
            }),
            "loop",
            VULTRA_LUA_PROPERTY([&ctx](const ScriptAudioSourceRef& self) {
                return requireComponentRef<AudioSourceComponent>(ctx, self.entity, "AudioSourceComponent").loop;
            },
            [&ctx](const ScriptAudioSourceRef& self, const bool& value) {
                requireComponentRef<AudioSourceComponent>(ctx, self.entity, "AudioSourceComponent").loop = value;
            }),
            "playOnStart",
            VULTRA_LUA_PROPERTY([&ctx](const ScriptAudioSourceRef& self) {
                return requireComponentRef<AudioSourceComponent>(ctx, self.entity, "AudioSourceComponent").playOnStart;
            },
            [&ctx](const ScriptAudioSourceRef& self, const bool& value) {
                requireComponentRef<AudioSourceComponent>(ctx, self.entity, "AudioSourceComponent").playOnStart = value;
            }),
            "playing",
            VULTRA_LUA_PROPERTY([&ctx](const ScriptAudioSourceRef& self) {
                return requireComponentRef<AudioSourceComponent>(ctx, self.entity, "AudioSourceComponent").playing;
            },
            [&ctx](const ScriptAudioSourceRef& self, const bool& value) {
                requireComponentRef<AudioSourceComponent>(ctx, self.entity, "AudioSourceComponent").playing = value;
            }),
            "spatial",
            VULTRA_LUA_PROPERTY([&ctx](const ScriptAudioSourceRef& self) {
                return requireComponentRef<AudioSourceComponent>(ctx, self.entity, "AudioSourceComponent").spatial;
            },
            [&ctx](const ScriptAudioSourceRef& self, const bool& value) {
                requireComponentRef<AudioSourceComponent>(ctx, self.entity, "AudioSourceComponent").spatial = value;
            }),
            "minDistance",
            VULTRA_LUA_PROPERTY([&ctx](const ScriptAudioSourceRef& self) {
                return requireComponentRef<AudioSourceComponent>(ctx, self.entity, "AudioSourceComponent").minDistance;
            },
            [&ctx](const ScriptAudioSourceRef& self, const float& value) {
                requireComponentRef<AudioSourceComponent>(ctx, self.entity, "AudioSourceComponent").minDistance = value;
            }),
            "maxDistance",
            VULTRA_LUA_PROPERTY([&ctx](const ScriptAudioSourceRef& self) {
                return requireComponentRef<AudioSourceComponent>(ctx, self.entity, "AudioSourceComponent").maxDistance;
            },
            [&ctx](const ScriptAudioSourceRef& self, const float& value) {
                requireComponentRef<AudioSourceComponent>(ctx, self.entity, "AudioSourceComponent").maxDistance = value;
            }),
            "rolloff",
            VULTRA_LUA_PROPERTY([&ctx](const ScriptAudioSourceRef& self) {
                return requireComponentRef<AudioSourceComponent>(ctx, self.entity, "AudioSourceComponent").rolloff;
            },
            [&ctx](const ScriptAudioSourceRef& self, const float& value) {
                requireComponentRef<AudioSourceComponent>(ctx, self.entity, "AudioSourceComponent").rolloff = value;
            }));

        lua.new_usertype<ScriptBoxShapeRef>(
            "BoxShape",
            "valid",
            VULTRA_LUA_READONLY_PROPERTY([&ctx](const ScriptBoxShapeRef& self) {
                auto* world = ctx.world();
                return world && world->registry().all_of<BoxShapeComponent>(self.entity);
            }),
            "halfExtents",
            VULTRA_LUA_PROPERTY([&ctx](const ScriptBoxShapeRef& self) {
                return toScript(requireComponentRef<BoxShapeComponent>(ctx, self.entity, "BoxShapeComponent").halfExtents);
            },
            [&ctx](const ScriptBoxShapeRef& self, const ScriptVec3& value) {
                requireComponentRef<BoxShapeComponent>(ctx, self.entity, "BoxShapeComponent").halfExtents = fromScript(value);
            }));

        lua.new_usertype<ScriptCameraRef>(
            "CameraRef",
            "valid",
            VULTRA_LUA_READONLY_PROPERTY([&ctx](const ScriptCameraRef& self) {
                auto* world = ctx.world();
                return world && world->registry().all_of<CameraComponent>(self.entity);
            }),
            "primary",
            VULTRA_LUA_PROPERTY([&ctx](const ScriptCameraRef& self) {
                return requireComponentRef<CameraComponent>(ctx, self.entity, "CameraComponent").primary;
            },
            [&ctx](const ScriptCameraRef& self, const bool& value) {
                requireComponentRef<CameraComponent>(ctx, self.entity, "CameraComponent").primary = value;
            }),
            "projection",
            VULTRA_LUA_PROPERTY([&ctx](const ScriptCameraRef& self) {
                return requireComponentRef<CameraComponent>(ctx, self.entity, "CameraComponent").projection;
            },
            [&ctx](const ScriptCameraRef& self, const std::uint32_t& value) {
                requireComponentRef<CameraComponent>(ctx, self.entity, "CameraComponent").projection = value;
            }),
            "fovY",
            VULTRA_LUA_PROPERTY([&ctx](const ScriptCameraRef& self) {
                return requireComponentRef<CameraComponent>(ctx, self.entity, "CameraComponent").fovY;
            },
            [&ctx](const ScriptCameraRef& self, const float& value) {
                requireComponentRef<CameraComponent>(ctx, self.entity, "CameraComponent").fovY = value;
            }),
            "fovYDegrees",
            VULTRA_LUA_PROPERTY([&ctx](const ScriptCameraRef& self) {
                script_binding::warnDeprecated("CameraRef.fovYDegrees", "CameraRef.fovY");
                return requireComponentRef<CameraComponent>(ctx, self.entity, "CameraComponent").fovY;
            },
            [&ctx](const ScriptCameraRef& self, const float& value) {
                script_binding::warnDeprecated("CameraRef.fovYDegrees", "CameraRef.fovY");
                requireComponentRef<CameraComponent>(ctx, self.entity, "CameraComponent").fovY = value;
            }),
            "orthographicHeight",
            VULTRA_LUA_PROPERTY([&ctx](const ScriptCameraRef& self) {
                return requireComponentRef<CameraComponent>(ctx, self.entity, "CameraComponent").orthographicHeight;
            },
            [&ctx](const ScriptCameraRef& self, const float& value) {
                requireComponentRef<CameraComponent>(ctx, self.entity, "CameraComponent").orthographicHeight = value;
            }),
            "zNear",
            VULTRA_LUA_PROPERTY([&ctx](const ScriptCameraRef& self) {
                return requireComponentRef<CameraComponent>(ctx, self.entity, "CameraComponent").zNear;
            },
            [&ctx](const ScriptCameraRef& self, const float& value) {
                requireComponentRef<CameraComponent>(ctx, self.entity, "CameraComponent").zNear = value;
            }),
            "zFar",
            VULTRA_LUA_PROPERTY([&ctx](const ScriptCameraRef& self) {
                return requireComponentRef<CameraComponent>(ctx, self.entity, "CameraComponent").zFar;
            },
            [&ctx](const ScriptCameraRef& self, const float& value) {
                requireComponentRef<CameraComponent>(ctx, self.entity, "CameraComponent").zFar = value;
            }),
            "clearMode",
            VULTRA_LUA_PROPERTY([&ctx](const ScriptCameraRef& self) {
                return requireComponentRef<CameraComponent>(ctx, self.entity, "CameraComponent").clearMode;
            },
            [&ctx](const ScriptCameraRef& self, const std::uint32_t& value) {
                requireComponentRef<CameraComponent>(ctx, self.entity, "CameraComponent").clearMode = value;
            }),
            "clearColor",
            VULTRA_LUA_PROPERTY([&ctx](const ScriptCameraRef& self) {
                return toScript(requireComponentRef<CameraComponent>(ctx, self.entity, "CameraComponent").clearColor);
            },
            [&ctx](const ScriptCameraRef& self, const ScriptVec4& value) {
                requireComponentRef<CameraComponent>(ctx, self.entity, "CameraComponent").clearColor = fromScript(value);
            }),
            "priority",
            VULTRA_LUA_PROPERTY([&ctx](const ScriptCameraRef& self) {
                return requireComponentRef<CameraComponent>(ctx, self.entity, "CameraComponent").priority;
            },
            [&ctx](const ScriptCameraRef& self, const int& value) {
                requireComponentRef<CameraComponent>(ctx, self.entity, "CameraComponent").priority = value;
            }),
            "cullingMask",
            VULTRA_LUA_PROPERTY([&ctx](const ScriptCameraRef& self) {
                return requireComponentRef<CameraComponent>(ctx, self.entity, "CameraComponent").cullingMask;
            },
            [&ctx](const ScriptCameraRef& self, const std::uint32_t& value) {
                requireComponentRef<CameraComponent>(ctx, self.entity, "CameraComponent").cullingMask = value;
            }),
            "rendererKey",
            VULTRA_LUA_PROPERTY([&ctx](const ScriptCameraRef& self) {
                return requireComponentRef<CameraComponent>(ctx, self.entity, "CameraComponent").rendererKey;
            },
            [&ctx](const ScriptCameraRef& self, const std::string& value) {
                requireComponentRef<CameraComponent>(ctx, self.entity, "CameraComponent").rendererKey = value;
            }));

        lua.new_usertype<ScriptCapsuleShapeRef>(
            "CapsuleShape",
            "valid",
            VULTRA_LUA_READONLY_PROPERTY([&ctx](const ScriptCapsuleShapeRef& self) {
                auto* world = ctx.world();
                return world && world->registry().all_of<CapsuleShapeComponent>(self.entity);
            }),
            "halfHeightOfCylinder",
            VULTRA_LUA_PROPERTY([&ctx](const ScriptCapsuleShapeRef& self) {
                return requireComponentRef<CapsuleShapeComponent>(ctx, self.entity, "CapsuleShapeComponent").halfHeightOfCylinder;
            },
            [&ctx](const ScriptCapsuleShapeRef& self, const float& value) {
                requireComponentRef<CapsuleShapeComponent>(ctx, self.entity, "CapsuleShapeComponent").halfHeightOfCylinder = value;
            }),
            "radius",
            VULTRA_LUA_PROPERTY([&ctx](const ScriptCapsuleShapeRef& self) {
                return requireComponentRef<CapsuleShapeComponent>(ctx, self.entity, "CapsuleShapeComponent").radius;
            },
            [&ctx](const ScriptCapsuleShapeRef& self, const float& value) {
                requireComponentRef<CapsuleShapeComponent>(ctx, self.entity, "CapsuleShapeComponent").radius = value;
            }));

        lua.new_usertype<ScriptCylinderShapeRef>(
            "CylinderShape",
            "valid",
            VULTRA_LUA_READONLY_PROPERTY([&ctx](const ScriptCylinderShapeRef& self) {
                auto* world = ctx.world();
                return world && world->registry().all_of<CylinderShapeComponent>(self.entity);
            }),
            "halfHeight",
            VULTRA_LUA_PROPERTY([&ctx](const ScriptCylinderShapeRef& self) {
                return requireComponentRef<CylinderShapeComponent>(ctx, self.entity, "CylinderShapeComponent").halfHeight;
            },
            [&ctx](const ScriptCylinderShapeRef& self, const float& value) {
                requireComponentRef<CylinderShapeComponent>(ctx, self.entity, "CylinderShapeComponent").halfHeight = value;
            }),
            "radius",
            VULTRA_LUA_PROPERTY([&ctx](const ScriptCylinderShapeRef& self) {
                return requireComponentRef<CylinderShapeComponent>(ctx, self.entity, "CylinderShapeComponent").radius;
            },
            [&ctx](const ScriptCylinderShapeRef& self, const float& value) {
                requireComponentRef<CylinderShapeComponent>(ctx, self.entity, "CylinderShapeComponent").radius = value;
            }));

        lua.new_usertype<ScriptEnvironmentRef>(
            "Environment",
            "valid",
            VULTRA_LUA_READONLY_PROPERTY([&ctx](const ScriptEnvironmentRef& self) {
                auto* world = ctx.world();
                return world && world->registry().all_of<EnvironmentComponent>(self.entity);
            }),
            "active",
            VULTRA_LUA_PROPERTY([&ctx](const ScriptEnvironmentRef& self) {
                return requireComponentRef<EnvironmentComponent>(ctx, self.entity, "EnvironmentComponent").active;
            },
            [&ctx](const ScriptEnvironmentRef& self, const bool& value) {
                requireComponentRef<EnvironmentComponent>(ctx, self.entity, "EnvironmentComponent").active = value;
            }),
            "skybox",
            VULTRA_LUA_PROPERTY([&ctx](const ScriptEnvironmentRef& self) {
                return uuidToString(requireComponentRef<EnvironmentComponent>(ctx, self.entity, "EnvironmentComponent").skybox);
            },
            [&ctx](const ScriptEnvironmentRef& self, const std::string& value) {
                requireComponentRef<EnvironmentComponent>(ctx, self.entity, "EnvironmentComponent").skybox = uuidFromString(value);
            }),
            "ambientColor",
            VULTRA_LUA_PROPERTY([&ctx](const ScriptEnvironmentRef& self) {
                return toScript(requireComponentRef<EnvironmentComponent>(ctx, self.entity, "EnvironmentComponent").ambientColor);
            },
            [&ctx](const ScriptEnvironmentRef& self, const ScriptVec3& value) {
                requireComponentRef<EnvironmentComponent>(ctx, self.entity, "EnvironmentComponent").ambientColor = fromScript(value);
            }),
            "ambientIntensity",
            VULTRA_LUA_PROPERTY([&ctx](const ScriptEnvironmentRef& self) {
                return requireComponentRef<EnvironmentComponent>(ctx, self.entity, "EnvironmentComponent").ambientIntensity;
            },
            [&ctx](const ScriptEnvironmentRef& self, const float& value) {
                requireComponentRef<EnvironmentComponent>(ctx, self.entity, "EnvironmentComponent").ambientIntensity = value;
            }),
            "enableIBL",
            VULTRA_LUA_PROPERTY([&ctx](const ScriptEnvironmentRef& self) {
                return requireComponentRef<EnvironmentComponent>(ctx, self.entity, "EnvironmentComponent").enableIBL;
            },
            [&ctx](const ScriptEnvironmentRef& self, const bool& value) {
                requireComponentRef<EnvironmentComponent>(ctx, self.entity, "EnvironmentComponent").enableIBL = value;
            }),
            "iblColor",
            VULTRA_LUA_PROPERTY([&ctx](const ScriptEnvironmentRef& self) {
                return toScript(requireComponentRef<EnvironmentComponent>(ctx, self.entity, "EnvironmentComponent").iblColor);
            },
            [&ctx](const ScriptEnvironmentRef& self, const ScriptVec3& value) {
                requireComponentRef<EnvironmentComponent>(ctx, self.entity, "EnvironmentComponent").iblColor = fromScript(value);
            }),
            "iblIntensity",
            VULTRA_LUA_PROPERTY([&ctx](const ScriptEnvironmentRef& self) {
                return requireComponentRef<EnvironmentComponent>(ctx, self.entity, "EnvironmentComponent").iblIntensity;
            },
            [&ctx](const ScriptEnvironmentRef& self, const float& value) {
                requireComponentRef<EnvironmentComponent>(ctx, self.entity, "EnvironmentComponent").iblIntensity = value;
            }));

        lua.new_usertype<ScriptLightRef>(
            "Light",
            "valid",
            VULTRA_LUA_READONLY_PROPERTY([&ctx](const ScriptLightRef& self) {
                auto* world = ctx.world();
                return world && world->registry().all_of<LightComponent>(self.entity);
            }),
            "kind",
            VULTRA_LUA_PROPERTY([&ctx](const ScriptLightRef& self) {
                return requireComponentRef<LightComponent>(ctx, self.entity, "LightComponent").kind;
            },
            [&ctx](const ScriptLightRef& self, const std::uint32_t& value) {
                requireComponentRef<LightComponent>(ctx, self.entity, "LightComponent").kind = value;
            }),
            "color",
            VULTRA_LUA_PROPERTY([&ctx](const ScriptLightRef& self) {
                return toScript(requireComponentRef<LightComponent>(ctx, self.entity, "LightComponent").color);
            },
            [&ctx](const ScriptLightRef& self, const ScriptVec3& value) {
                requireComponentRef<LightComponent>(ctx, self.entity, "LightComponent").color = fromScript(value);
            }),
            "intensity",
            VULTRA_LUA_PROPERTY([&ctx](const ScriptLightRef& self) {
                return requireComponentRef<LightComponent>(ctx, self.entity, "LightComponent").intensity;
            },
            [&ctx](const ScriptLightRef& self, const float& value) {
                requireComponentRef<LightComponent>(ctx, self.entity, "LightComponent").intensity = value;
            }),
            "range",
            VULTRA_LUA_PROPERTY([&ctx](const ScriptLightRef& self) {
                return requireComponentRef<LightComponent>(ctx, self.entity, "LightComponent").range;
            },
            [&ctx](const ScriptLightRef& self, const float& value) {
                requireComponentRef<LightComponent>(ctx, self.entity, "LightComponent").range = value;
            }),
            "radius",
            VULTRA_LUA_PROPERTY([&ctx](const ScriptLightRef& self) {
                return requireComponentRef<LightComponent>(ctx, self.entity, "LightComponent").radius;
            },
            [&ctx](const ScriptLightRef& self, const float& value) {
                requireComponentRef<LightComponent>(ctx, self.entity, "LightComponent").radius = value;
            }),
            "width",
            VULTRA_LUA_PROPERTY([&ctx](const ScriptLightRef& self) {
                return requireComponentRef<LightComponent>(ctx, self.entity, "LightComponent").width;
            },
            [&ctx](const ScriptLightRef& self, const float& value) {
                requireComponentRef<LightComponent>(ctx, self.entity, "LightComponent").width = value;
            }),
            "height",
            VULTRA_LUA_PROPERTY([&ctx](const ScriptLightRef& self) {
                return requireComponentRef<LightComponent>(ctx, self.entity, "LightComponent").height;
            },
            [&ctx](const ScriptLightRef& self, const float& value) {
                requireComponentRef<LightComponent>(ctx, self.entity, "LightComponent").height = value;
            }),
            "castsShadow",
            VULTRA_LUA_PROPERTY([&ctx](const ScriptLightRef& self) {
                return requireComponentRef<LightComponent>(ctx, self.entity, "LightComponent").castsShadow;
            },
            [&ctx](const ScriptLightRef& self, const bool& value) {
                requireComponentRef<LightComponent>(ctx, self.entity, "LightComponent").castsShadow = value;
            }),
            "twoSided",
            VULTRA_LUA_PROPERTY([&ctx](const ScriptLightRef& self) {
                return requireComponentRef<LightComponent>(ctx, self.entity, "LightComponent").twoSided;
            },
            [&ctx](const ScriptLightRef& self, const bool& value) {
                requireComponentRef<LightComponent>(ctx, self.entity, "LightComponent").twoSided = value;
            }));

        lua.new_usertype<ScriptParticleEmitterRef>(
            "ParticleEmitter",
            "valid",
            VULTRA_LUA_READONLY_PROPERTY([&ctx](const ScriptParticleEmitterRef& self) {
                auto* world = ctx.world();
                return world && world->registry().all_of<ParticleEmitterComponent>(self.entity);
            }),
            "playing",
            VULTRA_LUA_PROPERTY([&ctx](const ScriptParticleEmitterRef& self) {
                return requireComponentRef<ParticleEmitterComponent>(ctx, self.entity, "ParticleEmitterComponent").playing;
            },
            [&ctx](const ScriptParticleEmitterRef& self, const bool& value) {
                requireComponentRef<ParticleEmitterComponent>(ctx, self.entity, "ParticleEmitterComponent").playing = value;
            }),
            "worldSpace",
            VULTRA_LUA_PROPERTY([&ctx](const ScriptParticleEmitterRef& self) {
                return requireComponentRef<ParticleEmitterComponent>(ctx, self.entity, "ParticleEmitterComponent").worldSpace;
            },
            [&ctx](const ScriptParticleEmitterRef& self, const bool& value) {
                requireComponentRef<ParticleEmitterComponent>(ctx, self.entity, "ParticleEmitterComponent").worldSpace = value;
            }),
            "gpu",
            VULTRA_LUA_PROPERTY([&ctx](const ScriptParticleEmitterRef& self) {
                return requireComponentRef<ParticleEmitterComponent>(ctx, self.entity, "ParticleEmitterComponent").gpu;
            },
            [&ctx](const ScriptParticleEmitterRef& self, const bool& value) {
                requireComponentRef<ParticleEmitterComponent>(ctx, self.entity, "ParticleEmitterComponent").gpu = value;
            }),
            "maxParticles",
            VULTRA_LUA_PROPERTY([&ctx](const ScriptParticleEmitterRef& self) {
                return requireComponentRef<ParticleEmitterComponent>(ctx, self.entity, "ParticleEmitterComponent").maxParticles;
            },
            [&ctx](const ScriptParticleEmitterRef& self, const std::uint32_t& value) {
                requireComponentRef<ParticleEmitterComponent>(ctx, self.entity, "ParticleEmitterComponent").maxParticles = value;
            }),
            "emissionRate",
            VULTRA_LUA_PROPERTY([&ctx](const ScriptParticleEmitterRef& self) {
                return requireComponentRef<ParticleEmitterComponent>(ctx, self.entity, "ParticleEmitterComponent").emissionRate;
            },
            [&ctx](const ScriptParticleEmitterRef& self, const float& value) {
                requireComponentRef<ParticleEmitterComponent>(ctx, self.entity, "ParticleEmitterComponent").emissionRate = value;
            }),
            "lifetime",
            VULTRA_LUA_PROPERTY([&ctx](const ScriptParticleEmitterRef& self) {
                return requireComponentRef<ParticleEmitterComponent>(ctx, self.entity, "ParticleEmitterComponent").lifetime;
            },
            [&ctx](const ScriptParticleEmitterRef& self, const float& value) {
                requireComponentRef<ParticleEmitterComponent>(ctx, self.entity, "ParticleEmitterComponent").lifetime = value;
            }),
            "lifetimeVariance",
            VULTRA_LUA_PROPERTY([&ctx](const ScriptParticleEmitterRef& self) {
                return requireComponentRef<ParticleEmitterComponent>(ctx, self.entity, "ParticleEmitterComponent").lifetimeVariance;
            },
            [&ctx](const ScriptParticleEmitterRef& self, const float& value) {
                requireComponentRef<ParticleEmitterComponent>(ctx, self.entity, "ParticleEmitterComponent").lifetimeVariance = value;
            }),
            "spawnRadius",
            VULTRA_LUA_PROPERTY([&ctx](const ScriptParticleEmitterRef& self) {
                return requireComponentRef<ParticleEmitterComponent>(ctx, self.entity, "ParticleEmitterComponent").spawnRadius;
            },
            [&ctx](const ScriptParticleEmitterRef& self, const float& value) {
                requireComponentRef<ParticleEmitterComponent>(ctx, self.entity, "ParticleEmitterComponent").spawnRadius = value;
            }),
            "startVelocity",
            VULTRA_LUA_PROPERTY([&ctx](const ScriptParticleEmitterRef& self) {
                return toScript(requireComponentRef<ParticleEmitterComponent>(ctx, self.entity, "ParticleEmitterComponent").startVelocity);
            },
            [&ctx](const ScriptParticleEmitterRef& self, const ScriptVec3& value) {
                requireComponentRef<ParticleEmitterComponent>(ctx, self.entity, "ParticleEmitterComponent").startVelocity = fromScript(value);
            }),
            "velocityVariance",
            VULTRA_LUA_PROPERTY([&ctx](const ScriptParticleEmitterRef& self) {
                return requireComponentRef<ParticleEmitterComponent>(ctx, self.entity, "ParticleEmitterComponent").velocityVariance;
            },
            [&ctx](const ScriptParticleEmitterRef& self, const float& value) {
                requireComponentRef<ParticleEmitterComponent>(ctx, self.entity, "ParticleEmitterComponent").velocityVariance = value;
            }),
            "gravity",
            VULTRA_LUA_PROPERTY([&ctx](const ScriptParticleEmitterRef& self) {
                return toScript(requireComponentRef<ParticleEmitterComponent>(ctx, self.entity, "ParticleEmitterComponent").gravity);
            },
            [&ctx](const ScriptParticleEmitterRef& self, const ScriptVec3& value) {
                requireComponentRef<ParticleEmitterComponent>(ctx, self.entity, "ParticleEmitterComponent").gravity = fromScript(value);
            }),
            "startSize",
            VULTRA_LUA_PROPERTY([&ctx](const ScriptParticleEmitterRef& self) {
                return requireComponentRef<ParticleEmitterComponent>(ctx, self.entity, "ParticleEmitterComponent").startSize;
            },
            [&ctx](const ScriptParticleEmitterRef& self, const float& value) {
                requireComponentRef<ParticleEmitterComponent>(ctx, self.entity, "ParticleEmitterComponent").startSize = value;
            }),
            "endSize",
            VULTRA_LUA_PROPERTY([&ctx](const ScriptParticleEmitterRef& self) {
                return requireComponentRef<ParticleEmitterComponent>(ctx, self.entity, "ParticleEmitterComponent").endSize;
            },
            [&ctx](const ScriptParticleEmitterRef& self, const float& value) {
                requireComponentRef<ParticleEmitterComponent>(ctx, self.entity, "ParticleEmitterComponent").endSize = value;
            }),
            "startColor",
            VULTRA_LUA_PROPERTY([&ctx](const ScriptParticleEmitterRef& self) {
                return toScript(requireComponentRef<ParticleEmitterComponent>(ctx, self.entity, "ParticleEmitterComponent").startColor);
            },
            [&ctx](const ScriptParticleEmitterRef& self, const ScriptVec4& value) {
                requireComponentRef<ParticleEmitterComponent>(ctx, self.entity, "ParticleEmitterComponent").startColor = fromScript(value);
            }),
            "endColor",
            VULTRA_LUA_PROPERTY([&ctx](const ScriptParticleEmitterRef& self) {
                return toScript(requireComponentRef<ParticleEmitterComponent>(ctx, self.entity, "ParticleEmitterComponent").endColor);
            },
            [&ctx](const ScriptParticleEmitterRef& self, const ScriptVec4& value) {
                requireComponentRef<ParticleEmitterComponent>(ctx, self.entity, "ParticleEmitterComponent").endColor = fromScript(value);
            }));

        lua.new_usertype<ScriptReflectionProbeRef>(
            "ReflectionProbe",
            "valid",
            VULTRA_LUA_READONLY_PROPERTY([&ctx](const ScriptReflectionProbeRef& self) {
                auto* world = ctx.world();
                return world && world->registry().all_of<ReflectionProbeComponent>(self.entity);
            }),
            "active",
            VULTRA_LUA_PROPERTY([&ctx](const ScriptReflectionProbeRef& self) {
                return requireComponentRef<ReflectionProbeComponent>(ctx, self.entity, "ReflectionProbeComponent").active;
            },
            [&ctx](const ScriptReflectionProbeRef& self, const bool& value) {
                requireComponentRef<ReflectionProbeComponent>(ctx, self.entity, "ReflectionProbeComponent").active = value;
            }),
            "enableIBL",
            VULTRA_LUA_PROPERTY([&ctx](const ScriptReflectionProbeRef& self) {
                return requireComponentRef<ReflectionProbeComponent>(ctx, self.entity, "ReflectionProbeComponent").enableIBL;
            },
            [&ctx](const ScriptReflectionProbeRef& self, const bool& value) {
                requireComponentRef<ReflectionProbeComponent>(ctx, self.entity, "ReflectionProbeComponent").enableIBL = value;
            }),
            "environmentMap",
            VULTRA_LUA_PROPERTY([&ctx](const ScriptReflectionProbeRef& self) {
                return uuidToString(requireComponentRef<ReflectionProbeComponent>(ctx, self.entity, "ReflectionProbeComponent").environmentMap);
            },
            [&ctx](const ScriptReflectionProbeRef& self, const std::string& value) {
                requireComponentRef<ReflectionProbeComponent>(ctx, self.entity, "ReflectionProbeComponent").environmentMap = uuidFromString(value);
            }),
            "shape",
            VULTRA_LUA_PROPERTY([&ctx](const ScriptReflectionProbeRef& self) {
                return requireComponentRef<ReflectionProbeComponent>(ctx, self.entity, "ReflectionProbeComponent").shape;
            },
            [&ctx](const ScriptReflectionProbeRef& self, const std::uint32_t& value) {
                requireComponentRef<ReflectionProbeComponent>(ctx, self.entity, "ReflectionProbeComponent").shape = value;
            }),
            "boxSize",
            VULTRA_LUA_PROPERTY([&ctx](const ScriptReflectionProbeRef& self) {
                return toScript(requireComponentRef<ReflectionProbeComponent>(ctx, self.entity, "ReflectionProbeComponent").boxSize);
            },
            [&ctx](const ScriptReflectionProbeRef& self, const ScriptVec3& value) {
                requireComponentRef<ReflectionProbeComponent>(ctx, self.entity, "ReflectionProbeComponent").boxSize = fromScript(value);
            }),
            "radius",
            VULTRA_LUA_PROPERTY([&ctx](const ScriptReflectionProbeRef& self) {
                return requireComponentRef<ReflectionProbeComponent>(ctx, self.entity, "ReflectionProbeComponent").radius;
            },
            [&ctx](const ScriptReflectionProbeRef& self, const float& value) {
                requireComponentRef<ReflectionProbeComponent>(ctx, self.entity, "ReflectionProbeComponent").radius = value;
            }),
            "blendDistance",
            VULTRA_LUA_PROPERTY([&ctx](const ScriptReflectionProbeRef& self) {
                return requireComponentRef<ReflectionProbeComponent>(ctx, self.entity, "ReflectionProbeComponent").blendDistance;
            },
            [&ctx](const ScriptReflectionProbeRef& self, const float& value) {
                requireComponentRef<ReflectionProbeComponent>(ctx, self.entity, "ReflectionProbeComponent").blendDistance = value;
            }),
            "intensity",
            VULTRA_LUA_PROPERTY([&ctx](const ScriptReflectionProbeRef& self) {
                return requireComponentRef<ReflectionProbeComponent>(ctx, self.entity, "ReflectionProbeComponent").intensity;
            },
            [&ctx](const ScriptReflectionProbeRef& self, const float& value) {
                requireComponentRef<ReflectionProbeComponent>(ctx, self.entity, "ReflectionProbeComponent").intensity = value;
            }),
            "priority",
            VULTRA_LUA_PROPERTY([&ctx](const ScriptReflectionProbeRef& self) {
                return requireComponentRef<ReflectionProbeComponent>(ctx, self.entity, "ReflectionProbeComponent").priority;
            },
            [&ctx](const ScriptReflectionProbeRef& self, const int& value) {
                requireComponentRef<ReflectionProbeComponent>(ctx, self.entity, "ReflectionProbeComponent").priority = value;
            }),
            "parallaxCorrection",
            VULTRA_LUA_PROPERTY([&ctx](const ScriptReflectionProbeRef& self) {
                return requireComponentRef<ReflectionProbeComponent>(ctx, self.entity, "ReflectionProbeComponent").parallaxCorrection;
            },
            [&ctx](const ScriptReflectionProbeRef& self, const bool& value) {
                requireComponentRef<ReflectionProbeComponent>(ctx, self.entity, "ReflectionProbeComponent").parallaxCorrection = value;
            }));

        lua.new_usertype<ScriptSphereShapeRef>(
            "SphereShape",
            "valid",
            VULTRA_LUA_READONLY_PROPERTY([&ctx](const ScriptSphereShapeRef& self) {
                auto* world = ctx.world();
                return world && world->registry().all_of<SphereShapeComponent>(self.entity);
            }),
            "radius",
            VULTRA_LUA_PROPERTY([&ctx](const ScriptSphereShapeRef& self) {
                return requireComponentRef<SphereShapeComponent>(ctx, self.entity, "SphereShapeComponent").radius;
            },
            [&ctx](const ScriptSphereShapeRef& self, const float& value) {
                requireComponentRef<SphereShapeComponent>(ctx, self.entity, "SphereShapeComponent").radius = value;
            }));

    }

    void applyGeneratedEntityAccessors(sol::usertype<ScriptEntity>& entityType, ScriptContext& ctx)
    {
        entityType["audioListener"] =
            sol::readonly_property([](const ScriptEntity& self) { return ScriptAudioListenerRef {self.value}; });
        entityType["hasAudioListener"] = [&ctx](const ScriptEntity& self) {
            auto* world = ctx.world();
            return world && ctx.isValid(self.value) && world->registry().all_of<AudioListenerComponent>(self.value);
        };
        entityType["audioSource"] =
            sol::readonly_property([](const ScriptEntity& self) { return ScriptAudioSourceRef {self.value}; });
        entityType["hasAudioSource"] = [&ctx](const ScriptEntity& self) {
            auto* world = ctx.world();
            return world && ctx.isValid(self.value) && world->registry().all_of<AudioSourceComponent>(self.value);
        };
        entityType["boxShape"] =
            sol::readonly_property([](const ScriptEntity& self) { return ScriptBoxShapeRef {self.value}; });
        entityType["hasBoxShape"] = [&ctx](const ScriptEntity& self) {
            auto* world = ctx.world();
            return world && ctx.isValid(self.value) && world->registry().all_of<BoxShapeComponent>(self.value);
        };
        entityType["camera"] =
            sol::readonly_property([](const ScriptEntity& self) { return ScriptCameraRef {self.value}; });
        entityType["hasCamera"] = [&ctx](const ScriptEntity& self) {
            auto* world = ctx.world();
            return world && ctx.isValid(self.value) && world->registry().all_of<CameraComponent>(self.value);
        };
        entityType["capsuleShape"] =
            sol::readonly_property([](const ScriptEntity& self) { return ScriptCapsuleShapeRef {self.value}; });
        entityType["hasCapsuleShape"] = [&ctx](const ScriptEntity& self) {
            auto* world = ctx.world();
            return world && ctx.isValid(self.value) && world->registry().all_of<CapsuleShapeComponent>(self.value);
        };
        entityType["cylinderShape"] =
            sol::readonly_property([](const ScriptEntity& self) { return ScriptCylinderShapeRef {self.value}; });
        entityType["hasCylinderShape"] = [&ctx](const ScriptEntity& self) {
            auto* world = ctx.world();
            return world && ctx.isValid(self.value) && world->registry().all_of<CylinderShapeComponent>(self.value);
        };
        entityType["environment"] =
            sol::readonly_property([](const ScriptEntity& self) { return ScriptEnvironmentRef {self.value}; });
        entityType["hasEnvironment"] = [&ctx](const ScriptEntity& self) {
            auto* world = ctx.world();
            return world && ctx.isValid(self.value) && world->registry().all_of<EnvironmentComponent>(self.value);
        };
        entityType["light"] =
            sol::readonly_property([](const ScriptEntity& self) { return ScriptLightRef {self.value}; });
        entityType["hasLight"] = [&ctx](const ScriptEntity& self) {
            auto* world = ctx.world();
            return world && ctx.isValid(self.value) && world->registry().all_of<LightComponent>(self.value);
        };
        entityType["particleEmitter"] =
            sol::readonly_property([](const ScriptEntity& self) { return ScriptParticleEmitterRef {self.value}; });
        entityType["hasParticleEmitter"] = [&ctx](const ScriptEntity& self) {
            auto* world = ctx.world();
            return world && ctx.isValid(self.value) && world->registry().all_of<ParticleEmitterComponent>(self.value);
        };
        entityType["reflectionProbe"] =
            sol::readonly_property([](const ScriptEntity& self) { return ScriptReflectionProbeRef {self.value}; });
        entityType["hasReflectionProbe"] = [&ctx](const ScriptEntity& self) {
            auto* world = ctx.world();
            return world && ctx.isValid(self.value) && world->registry().all_of<ReflectionProbeComponent>(self.value);
        };
        entityType["sphereShape"] =
            sol::readonly_property([](const ScriptEntity& self) { return ScriptSphereShapeRef {self.value}; });
        entityType["hasSphereShape"] = [&ctx](const ScriptEntity& self) {
            auto* world = ctx.world();
            return world && ctx.isValid(self.value) && world->registry().all_of<SphereShapeComponent>(self.value);
        };
    }
} // namespace vultra
