// GENERATED by tools/python/extract_bindings.py + bindgen.backends.lua_sol2 -- DO NOT EDIT.
// Source of truth: tools/bindings/ir/bindings.ir.json (from VBIND_* annotations).

#include "vultra/function/scripting/bindings/script_scene_binding.hpp"

#include "vultra/function/scripting/bindings/script_binding_common.hpp"
#include "vultra/function/scripting/script_context.hpp"
#include "vultra/function/scripting/script_types.hpp"
#include "vultra/function/scripting/bindings/script_scene_shim.hpp"

#include <cstdint>
#include <string>

namespace vultra
{
    void registerScriptSceneBindings(sol::state& lua, ScriptContext& ctx)
    {
        (void)ctx;
        {
            auto ns = script_binding::getOrCreateTable(lua, "Scene");
            ns.set_function("load",
                [&ctx](const std::string & uri) {
                    return sceneLoad(ctx, uri);
                });
            ns.set_function("instantiate",
                [&ctx](const std::string & uri) {
                    return sceneInstantiate(ctx, uri);
                });
            ns.set_function("instantiateChild",
                [&ctx](const std::string & uri, const ScriptEntity & parent, bool clearWorld) {
                    return sceneInstantiateChild(ctx, uri, parent, clearWorld);
                });
            ns.set_function("saveWorld",
                [&ctx](const std::string & uri) {
                    return sceneSaveWorld(ctx, uri);
                });
            ns.set_function("saveEntity",
                [&ctx](const std::string & uri, const ScriptEntity & root) {
                    return sceneSaveEntity(ctx, uri, root);
                });
        }

    }
} // namespace vultra
