// GENERATED by tools/python/extract_bindings.py + bindgen.backends.lua_sol2 -- DO NOT EDIT.
// Source of truth: tools/bindings/ir/bindings.ir.json (from VBIND_* annotations).

#include "vultra/function/scripting/bindings/script_navigation_binding.hpp"

#include "vultra/function/scripting/bindings/script_binding_common.hpp"
#include "vultra/function/scripting/script_context.hpp"
#include "vultra/function/scripting/script_types.hpp"
#include "vultra/function/scripting/bindings/script_nav_shim.hpp"

#include <cstdint>
#include <string>

namespace vultra
{
    void registerScriptNavigationBindings(sol::state& lua, ScriptContext& ctx)
    {
        (void)ctx;
        {
            auto ns = script_binding::getOrCreateTable(lua, "Nav");
            ns.set_function("bake",
                [&ctx]() {
                    return navBake(ctx);
                });
            ns.set_function("isBaked",
                [&ctx]() {
                    return navIsBaked(ctx);
                });
            ns.set_function("findPath",
                [&ctx](sol::this_state luaState, const ScriptVec3 & start, const ScriptVec3 & end) {
                    return navFindPath(ctx, luaState, start, end);
                });
            ns.set_function("nearestPoint",
                [&ctx](const ScriptVec3 & point) {
                    return navNearestPoint(ctx, point);
                });
            ns.set_function("setAgentDestination",
                [&ctx](const ScriptEntity & entity, const ScriptVec3 & target) {
                    return navSetAgentDestination(ctx, entity, target);
                });
            ns.set_function("stopAgent",
                [&ctx](const ScriptEntity & entity) {
                    navStopAgent(ctx, entity);
                });
            ns.set_function("agentHasPath",
                [&ctx](const ScriptEntity & entity) {
                    return navAgentHasPath(ctx, entity);
                });
            ns.set_function("setDebugDrawEnabled",
                [&ctx](bool enabled) {
                    navSetDebugDrawEnabled(ctx, enabled);
                });
            ns.set_function("debugDrawEnabled",
                [&ctx]() {
                    return navDebugDrawEnabled(ctx);
                });
        }

    }
} // namespace vultra
