// GENERATED by tools/python/extract_bindings.py + bindgen.backends.lua_sol2 -- DO NOT EDIT.
// Source of truth: tools/bindings/ir/bindings.ir.json (from VBIND_* annotations).

#include "vultra/function/scripting/bindings/script_asset_binding.hpp"

#include "vultra/function/scripting/bindings/script_binding_common.hpp"
#include "vultra/function/scripting/script_context.hpp"
#include "vultra/function/scripting/script_types.hpp"
#include "vultra/function/asset/asset_state.hpp"
#include "vultra/function/scripting/bindings/script_asset_shim.hpp"

#include <cstdint>
#include <string>

namespace vultra
{
    void registerScriptAssetBindings(sol::state& lua, ScriptContext& ctx)
    {
        (void)ctx;
        lua.new_usertype<ScriptAssetHandle>(
            "AssetHandle",
            "valid",
            &ScriptAssetHandle::valid,
            "ready",
            &ScriptAssetHandle::ready,
            "uuid",
            &ScriptAssetHandle::uuid,
            "state",
            &ScriptAssetHandle::state,
            "gpuIndex",
            &ScriptAssetHandle::gpuIndex);

        lua.new_usertype<ScriptTextAssetResult>(
            "TextAssetResult",
            "ok",
            &ScriptTextAssetResult::ok,
            "text",
            &ScriptTextAssetResult::text,
            "error",
            &ScriptTextAssetResult::error);

        lua.new_usertype<ScriptAssetMemoryStats>(
            "AssetMemoryStats",
            "cpuCacheBytes",
            &ScriptAssetMemoryStats::cpuCacheBytes);

        {
            auto ns = script_binding::getOrCreateTable(lua, "Asset");
            ns.set_function("resolveUri",
                [&ctx](const std::string & uri) {
                    return assetResolveUri(ctx, uri);
                });
            ns.set_function("loadText",
                [&ctx](const std::string & uri) {
                    return assetLoadText(ctx, uri);
                });
            ns.set_function("loadMesh",
                [&ctx](const std::string & uri) {
                    return assetLoadMesh(ctx, uri);
                });
            ns.set_function("loadTexture",
                [&ctx](const std::string & uri) {
                    return assetLoadTexture(ctx, uri);
                });
            ns.set_function("loadGaussianSplat",
                [&ctx](const std::string & uri) {
                    return assetLoadGaussianSplat(ctx, uri);
                });
            ns.set_function("memoryStats",
                [&ctx]() {
                    return assetMemoryStats(ctx);
                });
        }

        script_binding::bindEnumTable<vultra::AssetState>(lua, "AssetState");
    }
} // namespace vultra
