// GENERATED by tools/python/extract_bindings.py + bindgen.backends.lua_sol2 -- DO NOT EDIT.
// Source of truth: tools/bindings/ir/bindings.ir.json (from VBIND_* annotations).

#include "vultra/function/scripting/bindings/script_math_binding.hpp"

#include "vultra/function/scripting/bindings/script_binding_common.hpp"
#include "vultra/function/scripting/script_context.hpp"
#include "vultra/function/scripting/script_types.hpp"
#include "vultra/function/scripting/bindings/script_math_shim.hpp"

#include <cstdint>
#include <string>

namespace vultra
{
    void registerScriptMathBindings(sol::state& lua, ScriptContext& ctx)
    {
        (void)ctx;
        mathRegisterTypes(lua, ctx);
    }
} // namespace vultra
