// GENERATED by tools/python/extract_bindings.py + bindgen.backends.lua_sol2 -- DO NOT EDIT.
// Source of truth: tools/bindings/ir/bindings.ir.json (from VBIND_* annotations).

#include "vultra/function/scripting/bindings/script_render_binding.hpp"

#include "vultra/function/scripting/bindings/script_binding_common.hpp"
#include "vultra/function/scripting/script_context.hpp"
#include "vultra/function/scripting/script_types.hpp"
#include "vultra/function/rendering/render_structs.hpp"
#include "vultra/function/scripting/bindings/script_render_shim.hpp"
#include "vultra/function/services/camera_service.hpp"

#include <cstdint>
#include <string>

namespace vultra
{
    void registerScriptRenderBindings(sol::state& lua, ScriptContext& ctx)
    {
        (void)ctx;
        lua.new_usertype<ScriptCameraOverlayInfo>(
            "CameraOverlayInfo",
            "enabled",
            &ScriptCameraOverlayInfo::enabled,
            "mode",
            &ScriptCameraOverlayInfo::mode);

        lua.new_usertype<ScriptGaussianSplatSettings>(
            "GaussianSplatSettings",
            "baselineMode",
            &ScriptGaussianSplatSettings::baselineMode,
            "lodBudget",
            &ScriptGaussianSplatSettings::lodBudget,
            "clodLevel",
            &ScriptGaussianSplatSettings::clodLevel,
            "foveatedClodEnabled",
            &ScriptGaussianSplatSettings::foveatedClodEnabled,
            "foveatedRenderMode",
            &ScriptGaussianSplatSettings::foveatedRenderMode,
            "foveatedGaze",
            &ScriptGaussianSplatSettings::foveatedGaze,
            "foveatedRingDegrees",
            &ScriptGaussianSplatSettings::foveatedRingDegrees,
            "foveatedRingLevels",
            &ScriptGaussianSplatSettings::foveatedRingLevels,
            "foveatedResolutionScales",
            &ScriptGaussianSplatSettings::foveatedResolutionScales,
            "foveatedTransitionDegrees",
            &ScriptGaussianSplatSettings::foveatedTransitionDegrees,
            "foveatedBudgetControllerEnabled",
            &ScriptGaussianSplatSettings::foveatedBudgetControllerEnabled,
            "foveatedTargetFrameMs",
            &ScriptGaussianSplatSettings::foveatedTargetFrameMs,
            "foveatedBudgetAdjustRate",
            &ScriptGaussianSplatSettings::foveatedBudgetAdjustRate);

        lua.new_usertype<ScriptGaussianSplatFrameStats>(
            "GaussianSplatFrameStats",
            "frameIndex",
            &ScriptGaussianSplatFrameStats::frameIndex,
            "baselineMode",
            &ScriptGaussianSplatFrameStats::baselineMode,
            "foveatedRenderMode",
            &ScriptGaussianSplatFrameStats::foveatedRenderMode,
            "lodBudgetEnabled",
            &ScriptGaussianSplatFrameStats::lodBudgetEnabled,
            "foveatedClodEnabled",
            &ScriptGaussianSplatFrameStats::foveatedClodEnabled,
            "foveatedLayeredCompositeEnabled",
            &ScriptGaussianSplatFrameStats::foveatedLayeredCompositeEnabled,
            "foveatedBudgetControllerEnabled",
            &ScriptGaussianSplatFrameStats::foveatedBudgetControllerEnabled,
            "directPrefix",
            &ScriptGaussianSplatFrameStats::directPrefix,
            "lodBudget",
            &ScriptGaussianSplatFrameStats::lodBudget,
            "foveatedRingLevels",
            &ScriptGaussianSplatFrameStats::foveatedRingLevels,
            "foveatedResolutionScales",
            &ScriptGaussianSplatFrameStats::foveatedResolutionScales,
            "foveatedRingDegrees",
            &ScriptGaussianSplatFrameStats::foveatedRingDegrees,
            "foveatedTargetFrameMs",
            &ScriptGaussianSplatFrameStats::foveatedTargetFrameMs,
            "splatAssets",
            &ScriptGaussianSplatFrameStats::splatAssets,
            "drawRecords",
            &ScriptGaussianSplatFrameStats::drawRecords,
            "totalSplats",
            &ScriptGaussianSplatFrameStats::totalSplats,
            "preparedSplats",
            &ScriptGaussianSplatFrameStats::preparedSplats,
            "maxVisibleSplatCap",
            &ScriptGaussianSplatFrameStats::maxVisibleSplatCap,
            "lodSelectedRawSplats",
            &ScriptGaussianSplatFrameStats::lodSelectedRawSplats,
            "visibleSplats",
            &ScriptGaussianSplatFrameStats::visibleSplats,
            "drawnSplats",
            &ScriptGaussianSplatFrameStats::drawnSplats);

        {
            auto ns = script_binding::getOrCreateTable(lua, "Camera");
            ns.set_function("count",
                [&ctx]() {
                    return cameraCount(ctx);
                });
            ns.set_function("overlayInfo",
                [&ctx]() {
                    return cameraOverlayInfo(ctx);
                });
            ns.set_function("setInputSuppressed",
                [&ctx](bool suppressed) {
                    cameraSetInputSuppressed(ctx, suppressed);
                });
            ns.set_function("findPrimary",
                [&ctx]() {
                    return cameraFindPrimary(ctx);
                });
        }

        {
            auto ns = script_binding::getOrCreateTable(lua, "Render");
            ns.set_function("resize",
                [&ctx](std::uint32_t width, std::uint32_t height) {
                    renderResize(ctx, width, height);
                });
            ns.set_function("gaussianSplatSettings",
                [&ctx]() {
                    return renderGaussianSplatSettings(ctx);
                });
            ns.set_function("setGaussianSplatSettings",
                [&ctx](const ScriptGaussianSplatSettings & settings) {
                    renderSetGaussianSplatSettings(ctx, settings);
                });
            ns.set_function("gaussianSplatFrameStats",
                [&ctx]() {
                    return renderGaussianSplatFrameStats(ctx);
                });
            ns.set_function("setProfilerEnabled",
                [&ctx](bool enabled) {
                    renderSetProfilerEnabled(ctx, enabled);
                });
            ns.set_function("isProfilerEnabled",
                [&ctx]() {
                    return renderIsProfilerEnabled(ctx);
                });
            ns.set_function("profilerHistorySize",
                [&ctx]() {
                    return renderProfilerHistorySize(ctx);
                });
            ns.set_function("captureFrame",
                [&ctx]() {
                    renderCaptureFrame(ctx);
                });
        }

        {
            auto ns = script_binding::getOrCreateTable(lua, "RenderBackend");
            ns.set_function("isXREnabled",
                [&ctx]() {
                    return renderBackendIsXREnabled(ctx);
                });
            ns.set_function("isXRMirrorEnabled",
                [&ctx]() {
                    return renderBackendIsXRMirrorEnabled(ctx);
                });
            ns.set_function("isExitRequested",
                [&ctx]() {
                    return renderBackendIsExitRequested(ctx);
                });
        }

        script_binding::bindEnumTable<vultra::GaussianSplatBaselineMode>(lua, "GaussianSplatBaselineMode");
        script_binding::bindEnumTable<vultra::GaussianSplatFoveatedRenderMode>(lua, "GaussianSplatFoveatedRenderMode");
        script_binding::bindEnumTable<vultra::CameraControlMode>(lua, "CameraControlMode");
    }
} // namespace vultra
