// GENERATED by tools/python/gen_imgui_lua.py -- DO NOT EDIT.
// Source: dear_bindings JSON for the engine's pinned ImGui version.
// ImGui.* keeps upstream PascalCase names (doc/lua_api_design.md sec. 9).

#include "vultra/function/scripting/bindings/script_imgui_binding.hpp"

#include "vultra/function/scripting/script_types.hpp"

// NOLINTBEGIN
#include <imgui.h>
// NOLINTEND

#include <string>
#include <tuple>

namespace vultra
{
    namespace detail = imgui_lua_detail;

    void registerGeneratedImGuiBindings(sol::state& lua)
    {
        auto imgui = lua.create_named_table("ImGui");

        imgui.set_function("Begin", [](const char* name, sol::optional<bool> p_open, sol::optional<lua_Integer> flags) {
            detail::ensureFrame();
            bool p_open_io = p_open.value_or(bool {});
            const auto ret = ImGui::Begin(name, p_open ? &p_open_io : nullptr, static_cast<ImGuiWindowFlags>(flags.value_or(0)));
            return std::make_tuple(ret, p_open ? sol::optional<bool>(p_open_io) : sol::optional<bool>());
        });
        imgui.set_function("End", []() {
            detail::ensureFrame();
            ImGui::End();
        });
        imgui.set_function("BeginChild", [](const char* str_id, sol::optional<ScriptVec2> size, sol::optional<lua_Integer> child_flags, sol::optional<lua_Integer> window_flags) {
            detail::ensureFrame();
            const auto ret = ImGui::BeginChild(str_id, size ? ImVec2(size->x, size->y) : ImVec2(0, 0), static_cast<ImGuiChildFlags>(child_flags.value_or(0)), static_cast<ImGuiWindowFlags>(window_flags.value_or(0)));
            return ret;
        });
        imgui.set_function("EndChild", []() {
            detail::ensureFrame();
            ImGui::EndChild();
        });
        imgui.set_function("GetWindowWidth", []() {
            detail::ensureFrame();
            const auto ret = ImGui::GetWindowWidth();
            return ret;
        });
        imgui.set_function("GetWindowHeight", []() {
            detail::ensureFrame();
            const auto ret = ImGui::GetWindowHeight();
            return ret;
        });
        imgui.set_function("GetContentRegionAvail", []() {
            detail::ensureFrame();
            const ImVec2 ret = ImGui::GetContentRegionAvail();
            return ScriptVec2 {ret.x, ret.y};
        });
        imgui.set_function("SetNextWindowPos", [](const ScriptVec2& pos, sol::optional<lua_Integer> cond) {
            detail::ensureFrame();
            ImGui::SetNextWindowPos(ImVec2(pos.x, pos.y), static_cast<ImGuiCond>(cond.value_or(0)));
        });
        imgui.set_function("SetNextWindowSize", [](const ScriptVec2& size, sol::optional<lua_Integer> cond) {
            detail::ensureFrame();
            ImGui::SetNextWindowSize(ImVec2(size.x, size.y), static_cast<ImGuiCond>(cond.value_or(0)));
        });
        imgui.set_function("Separator", []() {
            detail::ensureFrame();
            ImGui::Separator();
        });
        imgui.set_function("SeparatorText", [](const char* label) {
            detail::ensureFrame();
            ImGui::SeparatorText(label);
        });
        imgui.set_function("SameLine", []() {
            detail::ensureFrame();
            ImGui::SameLine();
        });
        imgui.set_function("Spacing", []() {
            detail::ensureFrame();
            ImGui::Spacing();
        });
        imgui.set_function("NewLine", []() {
            detail::ensureFrame();
            ImGui::NewLine();
        });
        imgui.set_function("Indent", []() {
            detail::ensureFrame();
            ImGui::Indent();
        });
        imgui.set_function("Unindent", []() {
            detail::ensureFrame();
            ImGui::Unindent();
        });
        imgui.set_function("Dummy", [](const ScriptVec2& size) {
            detail::ensureFrame();
            ImGui::Dummy(ImVec2(size.x, size.y));
        });
        imgui.set_function("Text", [](const char* text) {
            detail::ensureFrame();
            ImGui::Text("%s", text);
        });
        imgui.set_function("TextColored", [](const ScriptVec4& col, const char* text) {
            detail::ensureFrame();
            ImGui::TextColored(ImVec4(col.x, col.y, col.z, col.w), "%s", text);
        });
        imgui.set_function("TextDisabled", [](const char* text) {
            detail::ensureFrame();
            ImGui::TextDisabled("%s", text);
        });
        imgui.set_function("TextWrapped", [](const char* text) {
            detail::ensureFrame();
            ImGui::TextWrapped("%s", text);
        });
        imgui.set_function("BulletText", [](const char* text) {
            detail::ensureFrame();
            ImGui::BulletText("%s", text);
        });
        imgui.set_function("Button", [](const char* label) {
            detail::ensureFrame();
            const auto ret = ImGui::Button(label);
            return ret;
        });
        imgui.set_function("SmallButton", [](const char* label) {
            detail::ensureFrame();
            const auto ret = ImGui::SmallButton(label);
            return ret;
        });
        imgui.set_function("Checkbox", [](const char* label, bool v) {
            detail::ensureFrame();
            bool v_io = v;
            const auto ret = ImGui::Checkbox(label, &v_io);
            return std::make_tuple(ret, v_io);
        });
        imgui.set_function("RadioButton", [](const char* label, bool active) {
            detail::ensureFrame();
            const auto ret = ImGui::RadioButton(label, active);
            return ret;
        });
        imgui.set_function("ProgressBar", [](float fraction, sol::optional<ScriptVec2> size_arg, sol::optional<std::string> overlay) {
            detail::ensureFrame();
            ImGui::ProgressBar(fraction, size_arg ? ImVec2(size_arg->x, size_arg->y) : ImVec2(-FLT_MIN, 0), overlay ? overlay->c_str() : nullptr);
        });
        imgui.set_function("Bullet", []() {
            detail::ensureFrame();
            ImGui::Bullet();
        });
        imgui.set_function("SliderFloat", [](const char* label, float v, float v_min, float v_max) {
            detail::ensureFrame();
            float v_io = v;
            const auto ret = ImGui::SliderFloat(label, &v_io, v_min, v_max);
            return std::make_tuple(ret, v_io);
        });
        imgui.set_function("SliderInt", [](const char* label, int v, int v_min, int v_max) {
            detail::ensureFrame();
            int v_io = v;
            const auto ret = ImGui::SliderInt(label, &v_io, v_min, v_max);
            return std::make_tuple(ret, v_io);
        });
        imgui.set_function("DragFloat", [](const char* label, float v) {
            detail::ensureFrame();
            float v_io = v;
            const auto ret = ImGui::DragFloat(label, &v_io);
            return std::make_tuple(ret, v_io);
        });
        imgui.set_function("DragInt", [](const char* label, int v) {
            detail::ensureFrame();
            int v_io = v;
            const auto ret = ImGui::DragInt(label, &v_io);
            return std::make_tuple(ret, v_io);
        });
        imgui.set_function("InputFloat", [](const char* label, float v) {
            detail::ensureFrame();
            float v_io = v;
            const auto ret = ImGui::InputFloat(label, &v_io);
            return std::make_tuple(ret, v_io);
        });
        imgui.set_function("InputInt", [](const char* label, int v) {
            detail::ensureFrame();
            int v_io = v;
            const auto ret = ImGui::InputInt(label, &v_io);
            return std::make_tuple(ret, v_io);
        });
        imgui.set_function("BeginCombo", [](const char* label, const char* preview_value, sol::optional<lua_Integer> flags) {
            detail::ensureFrame();
            const auto ret = ImGui::BeginCombo(label, preview_value, static_cast<ImGuiComboFlags>(flags.value_or(0)));
            return ret;
        });
        imgui.set_function("EndCombo", []() {
            detail::ensureFrame();
            ImGui::EndCombo();
        });
        imgui.set_function("Selectable", [](const char* label) {
            detail::ensureFrame();
            const auto ret = ImGui::Selectable(label);
            return ret;
        });
        imgui.set_function("TreeNode", [](const char* label) {
            detail::ensureFrame();
            const auto ret = ImGui::TreeNode(label);
            return ret;
        });
        imgui.set_function("TreePop", []() {
            detail::ensureFrame();
            ImGui::TreePop();
        });
        imgui.set_function("CollapsingHeader", [](const char* label, sol::optional<lua_Integer> flags) {
            detail::ensureFrame();
            const auto ret = ImGui::CollapsingHeader(label, static_cast<ImGuiTreeNodeFlags>(flags.value_or(0)));
            return ret;
        });
        imgui.set_function("SetNextItemOpen", [](bool is_open, sol::optional<lua_Integer> cond) {
            detail::ensureFrame();
            ImGui::SetNextItemOpen(is_open, static_cast<ImGuiCond>(cond.value_or(0)));
        });
        imgui.set_function("BeginMenuBar", []() {
            detail::ensureFrame();
            const auto ret = ImGui::BeginMenuBar();
            return ret;
        });
        imgui.set_function("EndMenuBar", []() {
            detail::ensureFrame();
            ImGui::EndMenuBar();
        });
        imgui.set_function("BeginMainMenuBar", []() {
            detail::ensureFrame();
            const auto ret = ImGui::BeginMainMenuBar();
            return ret;
        });
        imgui.set_function("EndMainMenuBar", []() {
            detail::ensureFrame();
            ImGui::EndMainMenuBar();
        });
        imgui.set_function("BeginMenu", [](const char* label) {
            detail::ensureFrame();
            const auto ret = ImGui::BeginMenu(label);
            return ret;
        });
        imgui.set_function("EndMenu", []() {
            detail::ensureFrame();
            ImGui::EndMenu();
        });
        imgui.set_function("MenuItem", [](const char* label) {
            detail::ensureFrame();
            const auto ret = ImGui::MenuItem(label);
            return ret;
        });
        imgui.set_function("OpenPopup", [](const char* str_id, sol::optional<lua_Integer> popup_flags) {
            detail::ensureFrame();
            ImGui::OpenPopup(str_id, static_cast<ImGuiPopupFlags>(popup_flags.value_or(0)));
        });
        imgui.set_function("BeginPopup", [](const char* str_id, sol::optional<lua_Integer> flags) {
            detail::ensureFrame();
            const auto ret = ImGui::BeginPopup(str_id, static_cast<ImGuiWindowFlags>(flags.value_or(0)));
            return ret;
        });
        imgui.set_function("EndPopup", []() {
            detail::ensureFrame();
            ImGui::EndPopup();
        });
        imgui.set_function("BeginPopupModal", [](const char* name, sol::optional<bool> p_open, sol::optional<lua_Integer> flags) {
            detail::ensureFrame();
            bool p_open_io = p_open.value_or(bool {});
            const auto ret = ImGui::BeginPopupModal(name, p_open ? &p_open_io : nullptr, static_cast<ImGuiWindowFlags>(flags.value_or(0)));
            return std::make_tuple(ret, p_open ? sol::optional<bool>(p_open_io) : sol::optional<bool>());
        });
        imgui.set_function("CloseCurrentPopup", []() {
            detail::ensureFrame();
            ImGui::CloseCurrentPopup();
        });
        imgui.set_function("BeginTooltip", []() {
            detail::ensureFrame();
            const auto ret = ImGui::BeginTooltip();
            return ret;
        });
        imgui.set_function("EndTooltip", []() {
            detail::ensureFrame();
            ImGui::EndTooltip();
        });
        imgui.set_function("SetTooltip", [](const char* text) {
            detail::ensureFrame();
            ImGui::SetTooltip("%s", text);
        });
        imgui.set_function("SetItemTooltip", [](const char* text) {
            detail::ensureFrame();
            ImGui::SetItemTooltip("%s", text);
        });
        imgui.set_function("BeginTabBar", [](const char* str_id, sol::optional<lua_Integer> flags) {
            detail::ensureFrame();
            const auto ret = ImGui::BeginTabBar(str_id, static_cast<ImGuiTabBarFlags>(flags.value_or(0)));
            return ret;
        });
        imgui.set_function("EndTabBar", []() {
            detail::ensureFrame();
            ImGui::EndTabBar();
        });
        imgui.set_function("BeginTabItem", [](const char* label, sol::optional<bool> p_open, sol::optional<lua_Integer> flags) {
            detail::ensureFrame();
            bool p_open_io = p_open.value_or(bool {});
            const auto ret = ImGui::BeginTabItem(label, p_open ? &p_open_io : nullptr, static_cast<ImGuiTabItemFlags>(flags.value_or(0)));
            return std::make_tuple(ret, p_open ? sol::optional<bool>(p_open_io) : sol::optional<bool>());
        });
        imgui.set_function("EndTabItem", []() {
            detail::ensureFrame();
            ImGui::EndTabItem();
        });
        imgui.set_function("BeginTable", [](const char* str_id, int columns, sol::optional<lua_Integer> flags) {
            detail::ensureFrame();
            const auto ret = ImGui::BeginTable(str_id, columns, static_cast<ImGuiTableFlags>(flags.value_or(0)));
            return ret;
        });
        imgui.set_function("EndTable", []() {
            detail::ensureFrame();
            ImGui::EndTable();
        });
        imgui.set_function("TableNextRow", []() {
            detail::ensureFrame();
            ImGui::TableNextRow();
        });
        imgui.set_function("TableNextColumn", []() {
            detail::ensureFrame();
            const auto ret = ImGui::TableNextColumn();
            return ret;
        });
        imgui.set_function("TableSetColumnIndex", [](int column_n) {
            detail::ensureFrame();
            const auto ret = ImGui::TableSetColumnIndex(column_n);
            return ret;
        });
        imgui.set_function("TableSetupColumn", [](const char* label, sol::optional<lua_Integer> flags) {
            detail::ensureFrame();
            ImGui::TableSetupColumn(label, static_cast<ImGuiTableColumnFlags>(flags.value_or(0)));
        });
        imgui.set_function("TableHeadersRow", []() {
            detail::ensureFrame();
            ImGui::TableHeadersRow();
        });
        imgui.set_function("IsItemHovered", [](sol::optional<lua_Integer> flags) {
            detail::ensureFrame();
            const auto ret = ImGui::IsItemHovered(static_cast<ImGuiHoveredFlags>(flags.value_or(0)));
            return ret;
        });
        imgui.set_function("IsItemActive", []() {
            detail::ensureFrame();
            const auto ret = ImGui::IsItemActive();
            return ret;
        });
        imgui.set_function("IsItemEdited", []() {
            detail::ensureFrame();
            const auto ret = ImGui::IsItemEdited();
            return ret;
        });
        imgui.set_function("IsItemClicked", []() {
            detail::ensureFrame();
            const auto ret = ImGui::IsItemClicked();
            return ret;
        });
        imgui.set_function("PushID", [](const char* str_id_begin, const char* str_id_end) {
            detail::ensureFrame();
            ImGui::PushID(str_id_begin, str_id_end);
        });
        imgui.set_function("PopID", []() {
            detail::ensureFrame();
            ImGui::PopID();
        });
        imgui.set_function("PushStyleColor", [](lua_Integer idx, const ScriptVec4& col) {
            detail::ensureFrame();
            ImGui::PushStyleColor(static_cast<ImGuiCol>(idx), ImVec4(col.x, col.y, col.z, col.w));
        });
        imgui.set_function("PopStyleColor", []() {
            detail::ensureFrame();
            ImGui::PopStyleColor();
        });
        imgui.set_function("PushStyleVar", [](lua_Integer idx, float val) {
            detail::ensureFrame();
            ImGui::PushStyleVar(static_cast<ImGuiStyleVar>(idx), val);
        });
        imgui.set_function("PushStyleVarVec2", [](lua_Integer idx, const ScriptVec2& val) {
            detail::ensureFrame();
            ImGui::PushStyleVar(static_cast<ImGuiStyleVar>(idx), ImVec2(val.x, val.y));
        });
        imgui.set_function("PopStyleVar", []() {
            detail::ensureFrame();
            ImGui::PopStyleVar();
        });

        {
            auto t = lua.create_table();
            t["None"] = 0;
            t["NoTitleBar"] = 1;
            t["NoResize"] = 2;
            t["NoMove"] = 4;
            t["NoScrollbar"] = 8;
            t["NoScrollWithMouse"] = 16;
            t["NoCollapse"] = 32;
            t["AlwaysAutoResize"] = 64;
            t["NoBackground"] = 128;
            t["NoSavedSettings"] = 256;
            t["NoMouseInputs"] = 512;
            t["MenuBar"] = 1024;
            t["HorizontalScrollbar"] = 2048;
            t["NoFocusOnAppearing"] = 4096;
            t["NoBringToFrontOnFocus"] = 8192;
            t["AlwaysVerticalScrollbar"] = 16384;
            t["AlwaysHorizontalScrollbar"] = 32768;
            t["NoNavInputs"] = 65536;
            t["NoNavFocus"] = 131072;
            t["UnsavedDocument"] = 262144;
            t["NoDocking"] = 524288;
            t["NoNav"] = 196608;
            t["NoDecoration"] = 43;
            t["NoInputs"] = 197120;
            imgui["WindowFlags"] = t;
        }
        {
            auto t = lua.create_table();
            t["None"] = 0;
            t["Borders"] = 1;
            t["AlwaysUseWindowPadding"] = 2;
            t["ResizeX"] = 4;
            t["ResizeY"] = 8;
            t["AutoResizeX"] = 16;
            t["AutoResizeY"] = 32;
            t["AlwaysAutoResize"] = 64;
            t["FrameStyle"] = 128;
            t["NavFlattened"] = 256;
            imgui["ChildFlags"] = t;
        }
        {
            auto t = lua.create_table();
            t["None"] = 0;
            t["Always"] = 1;
            t["Once"] = 2;
            t["FirstUseEver"] = 4;
            t["Appearing"] = 8;
            imgui["Cond"] = t;
        }
        {
            auto t = lua.create_table();
            t["Text"] = 0;
            t["TextDisabled"] = 1;
            t["WindowBg"] = 2;
            t["ChildBg"] = 3;
            t["PopupBg"] = 4;
            t["Border"] = 5;
            t["BorderShadow"] = 6;
            t["FrameBg"] = 7;
            t["FrameBgHovered"] = 8;
            t["FrameBgActive"] = 9;
            t["TitleBg"] = 10;
            t["TitleBgActive"] = 11;
            t["TitleBgCollapsed"] = 12;
            t["MenuBarBg"] = 13;
            t["ScrollbarBg"] = 14;
            t["ScrollbarGrab"] = 15;
            t["ScrollbarGrabHovered"] = 16;
            t["ScrollbarGrabActive"] = 17;
            t["CheckMark"] = 18;
            t["SliderGrab"] = 19;
            t["SliderGrabActive"] = 20;
            t["Button"] = 21;
            t["ButtonHovered"] = 22;
            t["ButtonActive"] = 23;
            t["Header"] = 24;
            t["HeaderHovered"] = 25;
            t["HeaderActive"] = 26;
            t["Separator"] = 27;
            t["SeparatorHovered"] = 28;
            t["SeparatorActive"] = 29;
            t["ResizeGrip"] = 30;
            t["ResizeGripHovered"] = 31;
            t["ResizeGripActive"] = 32;
            t["InputTextCursor"] = 33;
            t["TabHovered"] = 34;
            t["Tab"] = 35;
            t["TabSelected"] = 36;
            t["TabSelectedOverline"] = 37;
            t["TabDimmed"] = 38;
            t["TabDimmedSelected"] = 39;
            t["TabDimmedSelectedOverline"] = 40;
            t["DockingPreview"] = 41;
            t["DockingEmptyBg"] = 42;
            t["PlotLines"] = 43;
            t["PlotLinesHovered"] = 44;
            t["PlotHistogram"] = 45;
            t["PlotHistogramHovered"] = 46;
            t["TableHeaderBg"] = 47;
            t["TableBorderStrong"] = 48;
            t["TableBorderLight"] = 49;
            t["TableRowBg"] = 50;
            t["TableRowBgAlt"] = 51;
            t["TextLink"] = 52;
            t["TextSelectedBg"] = 53;
            t["TreeLines"] = 54;
            t["DragDropTarget"] = 55;
            t["DragDropTargetBg"] = 56;
            t["UnsavedMarker"] = 57;
            t["NavCursor"] = 58;
            t["NavWindowingHighlight"] = 59;
            t["NavWindowingDimBg"] = 60;
            t["ModalWindowDimBg"] = 61;
            t["TabActive"] = 36;
            t["TabUnfocused"] = 38;
            t["TabUnfocusedActive"] = 39;
            t["NavHighlight"] = 58;
            imgui["Col"] = t;
        }
        {
            auto t = lua.create_table();
            t["Alpha"] = 0;
            t["DisabledAlpha"] = 1;
            t["WindowPadding"] = 2;
            t["WindowRounding"] = 3;
            t["WindowBorderSize"] = 4;
            t["WindowMinSize"] = 5;
            t["WindowTitleAlign"] = 6;
            t["ChildRounding"] = 7;
            t["ChildBorderSize"] = 8;
            t["PopupRounding"] = 9;
            t["PopupBorderSize"] = 10;
            t["FramePadding"] = 11;
            t["FrameRounding"] = 12;
            t["FrameBorderSize"] = 13;
            t["ItemSpacing"] = 14;
            t["ItemInnerSpacing"] = 15;
            t["IndentSpacing"] = 16;
            t["CellPadding"] = 17;
            t["ScrollbarSize"] = 18;
            t["ScrollbarRounding"] = 19;
            t["ScrollbarPadding"] = 20;
            t["GrabMinSize"] = 21;
            t["GrabRounding"] = 22;
            t["ImageBorderSize"] = 23;
            t["TabRounding"] = 24;
            t["TabBorderSize"] = 25;
            t["TabMinWidthBase"] = 26;
            t["TabMinWidthShrink"] = 27;
            t["TabBarBorderSize"] = 28;
            t["TabBarOverlineSize"] = 29;
            t["TableAngledHeadersAngle"] = 30;
            t["TableAngledHeadersTextAlign"] = 31;
            t["TreeLinesSize"] = 32;
            t["TreeLinesRounding"] = 33;
            t["ButtonTextAlign"] = 34;
            t["SelectableTextAlign"] = 35;
            t["SeparatorTextBorderSize"] = 36;
            t["SeparatorTextAlign"] = 37;
            t["SeparatorTextPadding"] = 38;
            t["DockingSeparatorSize"] = 39;
            imgui["StyleVar"] = t;
        }
        {
            auto t = lua.create_table();
            t["None"] = 0;
            t["Resizable"] = 1;
            t["Reorderable"] = 2;
            t["Hideable"] = 4;
            t["Sortable"] = 8;
            t["NoSavedSettings"] = 16;
            t["ContextMenuInBody"] = 32;
            t["RowBg"] = 64;
            t["BordersInnerH"] = 128;
            t["BordersOuterH"] = 256;
            t["BordersInnerV"] = 512;
            t["BordersOuterV"] = 1024;
            t["BordersH"] = 384;
            t["BordersV"] = 1536;
            t["BordersInner"] = 640;
            t["BordersOuter"] = 1280;
            t["Borders"] = 1920;
            t["NoBordersInBody"] = 2048;
            t["NoBordersInBodyUntilResize"] = 4096;
            t["SizingFixedFit"] = 8192;
            t["SizingFixedSame"] = 16384;
            t["SizingStretchProp"] = 24576;
            t["SizingStretchSame"] = 32768;
            t["NoHostExtendX"] = 65536;
            t["NoHostExtendY"] = 131072;
            t["NoKeepColumnsVisible"] = 262144;
            t["PreciseWidths"] = 524288;
            t["NoClip"] = 1048576;
            t["PadOuterX"] = 2097152;
            t["NoPadOuterX"] = 4194304;
            t["NoPadInnerX"] = 8388608;
            t["ScrollX"] = 16777216;
            t["ScrollY"] = 33554432;
            t["SortMulti"] = 67108864;
            t["SortTristate"] = 134217728;
            t["HighlightHoveredColumn"] = 268435456;
            imgui["TableFlags"] = t;
        }
        {
            auto t = lua.create_table();
            t["None"] = 0;
            t["Disabled"] = 1;
            t["DefaultHide"] = 2;
            t["DefaultSort"] = 4;
            t["WidthStretch"] = 8;
            t["WidthFixed"] = 16;
            t["NoResize"] = 32;
            t["NoReorder"] = 64;
            t["NoHide"] = 128;
            t["NoClip"] = 256;
            t["NoSort"] = 512;
            t["NoSortAscending"] = 1024;
            t["NoSortDescending"] = 2048;
            t["NoHeaderLabel"] = 4096;
            t["NoHeaderWidth"] = 8192;
            t["PreferSortAscending"] = 16384;
            t["PreferSortDescending"] = 32768;
            t["IndentEnable"] = 65536;
            t["IndentDisable"] = 131072;
            t["AngledHeader"] = 262144;
            t["IsEnabled"] = 16777216;
            t["IsVisible"] = 33554432;
            t["IsSorted"] = 67108864;
            t["IsHovered"] = 134217728;
            imgui["TableColumnFlags"] = t;
        }
        {
            auto t = lua.create_table();
            t["None"] = 0;
            t["Headers"] = 1;
            imgui["TableRowFlags"] = t;
        }
        {
            auto t = lua.create_table();
            t["None"] = 0;
            t["NoAutoClosePopups"] = 1;
            t["SpanAllColumns"] = 2;
            t["AllowDoubleClick"] = 4;
            t["Disabled"] = 8;
            t["AllowOverlap"] = 16;
            t["Highlight"] = 32;
            t["SelectOnNav"] = 64;
            t["DontClosePopups"] = 1;
            imgui["SelectableFlags"] = t;
        }
        {
            auto t = lua.create_table();
            t["None"] = 0;
            t["PopupAlignLeft"] = 1;
            t["HeightSmall"] = 2;
            t["HeightRegular"] = 4;
            t["HeightLarge"] = 8;
            t["HeightLargest"] = 16;
            t["NoArrowButton"] = 32;
            t["NoPreview"] = 64;
            t["WidthFitPreview"] = 128;
            imgui["ComboFlags"] = t;
        }
        {
            auto t = lua.create_table();
            t["None"] = 0;
            t["Selected"] = 1;
            t["Framed"] = 2;
            t["AllowOverlap"] = 4;
            t["NoTreePushOnOpen"] = 8;
            t["NoAutoOpenOnLog"] = 16;
            t["DefaultOpen"] = 32;
            t["OpenOnDoubleClick"] = 64;
            t["OpenOnArrow"] = 128;
            t["Leaf"] = 256;
            t["Bullet"] = 512;
            t["FramePadding"] = 1024;
            t["SpanAvailWidth"] = 2048;
            t["SpanFullWidth"] = 4096;
            t["SpanLabelWidth"] = 8192;
            t["SpanAllColumns"] = 16384;
            t["LabelSpanAllColumns"] = 32768;
            t["NavLeftJumpsToParent"] = 131072;
            t["CollapsingHeader"] = 26;
            t["DrawLinesNone"] = 262144;
            t["DrawLinesFull"] = 524288;
            t["DrawLinesToNodes"] = 1048576;
            t["NavLeftJumpsBackHere"] = 131072;
            t["SpanTextWidth"] = 8192;
            imgui["TreeNodeFlags"] = t;
        }
        {
            auto t = lua.create_table();
            t["None"] = 0;
            t["MouseButtonLeft"] = 0;
            t["MouseButtonRight"] = 1;
            t["MouseButtonMiddle"] = 2;
            t["NoReopen"] = 32;
            t["NoOpenOverExistingPopup"] = 128;
            t["NoOpenOverItems"] = 256;
            t["AnyPopupId"] = 1024;
            t["AnyPopupLevel"] = 2048;
            t["AnyPopup"] = 3072;
            imgui["PopupFlags"] = t;
        }
        {
            auto t = lua.create_table();
            t["None"] = 0;
            t["ChildWindows"] = 1;
            t["RootWindow"] = 2;
            t["AnyWindow"] = 4;
            t["NoPopupHierarchy"] = 8;
            t["DockHierarchy"] = 16;
            t["AllowWhenBlockedByPopup"] = 32;
            t["AllowWhenBlockedByActiveItem"] = 128;
            t["AllowWhenOverlappedByItem"] = 256;
            t["AllowWhenOverlappedByWindow"] = 512;
            t["AllowWhenDisabled"] = 1024;
            t["NoNavOverride"] = 2048;
            t["AllowWhenOverlapped"] = 768;
            t["RectOnly"] = 928;
            t["RootAndChildWindows"] = 3;
            t["ForTooltip"] = 4096;
            t["Stationary"] = 8192;
            t["DelayNone"] = 16384;
            t["DelayShort"] = 32768;
            t["DelayNormal"] = 65536;
            t["NoSharedDelay"] = 131072;
            imgui["HoveredFlags"] = t;
        }
        {
            auto t = lua.create_table();
            t["None"] = 0;
            t["CharsDecimal"] = 1;
            t["CharsHexadecimal"] = 2;
            t["CharsScientific"] = 4;
            t["CharsUppercase"] = 8;
            t["CharsNoBlank"] = 16;
            t["AllowTabInput"] = 32;
            t["EnterReturnsTrue"] = 64;
            t["EscapeClearsAll"] = 128;
            t["CtrlEnterForNewLine"] = 256;
            t["ReadOnly"] = 512;
            t["Password"] = 1024;
            t["AlwaysOverwrite"] = 2048;
            t["AutoSelectAll"] = 4096;
            t["ParseEmptyRefVal"] = 8192;
            t["DisplayEmptyRefVal"] = 16384;
            t["NoHorizontalScroll"] = 32768;
            t["NoUndoRedo"] = 65536;
            t["ElideLeft"] = 131072;
            t["CallbackCompletion"] = 262144;
            t["CallbackHistory"] = 524288;
            t["CallbackAlways"] = 1048576;
            t["CallbackCharFilter"] = 2097152;
            t["CallbackResize"] = 4194304;
            t["CallbackEdit"] = 8388608;
            t["WordWrap"] = 16777216;
            imgui["InputTextFlags"] = t;
        }
        {
            auto t = lua.create_table();
            t["None"] = 0;
            t["Logarithmic"] = 32;
            t["NoRoundToFormat"] = 64;
            t["NoInput"] = 128;
            t["WrapAround"] = 256;
            t["ClampOnInput"] = 512;
            t["ClampZeroRange"] = 1024;
            t["NoSpeedTweaks"] = 2048;
            t["AlwaysClamp"] = 1536;
            imgui["SliderFlags"] = t;
        }
        {
            auto t = lua.create_table();
            t["None"] = 0;
            t["Reorderable"] = 1;
            t["AutoSelectNewTabs"] = 2;
            t["TabListPopupButton"] = 4;
            t["NoCloseWithMiddleMouseButton"] = 8;
            t["NoTabListScrollingButtons"] = 16;
            t["NoTooltip"] = 32;
            t["DrawSelectedOverline"] = 64;
            t["FittingPolicyMixed"] = 128;
            t["FittingPolicyShrink"] = 256;
            t["FittingPolicyScroll"] = 512;
            t["FittingPolicyResizeDown"] = 256;
            imgui["TabBarFlags"] = t;
        }
        {
            auto t = lua.create_table();
            t["None"] = 0;
            t["UnsavedDocument"] = 1;
            t["SetSelected"] = 2;
            t["NoCloseWithMiddleMouseButton"] = 4;
            t["NoPushId"] = 8;
            t["NoTooltip"] = 16;
            t["NoReorder"] = 32;
            t["Leading"] = 64;
            t["Trailing"] = 128;
            t["NoAssumedClosure"] = 256;
            imgui["TabItemFlags"] = t;
        }
    }
} // namespace vultra
