// GENERATED by tools/python/extract_bindings.py + bindgen.backends.lua_sol2 -- DO NOT EDIT.
// Source of truth: tools/bindings/ir/bindings.ir.json (from VBIND_* annotations).

#include "vultra/function/scripting/bindings/script_animation_binding.hpp"

#include "vultra/function/scripting/bindings/script_binding_common.hpp"
#include "vultra/function/scripting/script_context.hpp"
#include "vultra/function/scripting/script_types.hpp"
#include "vultra/function/world/world.hpp"
#include "vultra/function/scripting/bindings/script_animation_shim.hpp"

#include <cstdint>
#include <string>

namespace vultra
{
    void registerScriptAnimationBindings(sol::state& lua, ScriptContext& ctx)
    {
        (void)ctx;
        lua.new_usertype<ScriptAnimatorPlaybackState>(
            "AnimatorPlaybackState",
            "valid",
            &ScriptAnimatorPlaybackState::valid,
            "playing",
            &ScriptAnimatorPlaybackState::playing,
            "loop",
            &ScriptAnimatorPlaybackState::loop,
            "speed",
            &ScriptAnimatorPlaybackState::speed,
            "time",
            &ScriptAnimatorPlaybackState::time,
            "duration",
            &ScriptAnimatorPlaybackState::duration,
            "normalizedTime",
            &ScriptAnimatorPlaybackState::normalizedTime,
            "skeleton",
            &ScriptAnimatorPlaybackState::skeleton,
            "animation",
            &ScriptAnimatorPlaybackState::animation);

        lua.new_usertype<ScriptAnimatorRef>(
            "Animator",
            "valid",
            script_binding::readonlyProperty([&ctx](const ScriptAnimatorRef& self) {
                auto* world = ctx.world();
                return world && world->registry().all_of<AnimatorComponent>(self.entity);
            }),
            "skeleton",
            script_binding::property([&ctx](const ScriptAnimatorRef& self) { return animatorGetSkeleton(ctx, self); },
            [&ctx](const ScriptAnimatorRef& self, std::string value) { animatorSetSkeleton(ctx, self, value); }),
            "animation",
            script_binding::property([&ctx](const ScriptAnimatorRef& self) { return animatorGetAnimation(ctx, self); },
            [&ctx](const ScriptAnimatorRef& self, std::string value) { animatorSetAnimation(ctx, self, value); }),
            "playing",
            script_binding::property([&ctx](const ScriptAnimatorRef& self) { return animatorGetPlaying(ctx, self); },
            [&ctx](const ScriptAnimatorRef& self, bool value) { animatorSetPlaying(ctx, self, value); }),
            "loop",
            script_binding::property([&ctx](const ScriptAnimatorRef& self) { return animatorGetLoop(ctx, self); },
            [&ctx](const ScriptAnimatorRef& self, bool value) { animatorSetLoop(ctx, self, value); }),
            "speed",
            script_binding::property([&ctx](const ScriptAnimatorRef& self) { return animatorGetSpeed(ctx, self); },
            [&ctx](const ScriptAnimatorRef& self, float value) { animatorSetSpeed(ctx, self, value); }),
            "time",
            script_binding::property([&ctx](const ScriptAnimatorRef& self) { return animatorGetTime(ctx, self); },
            [&ctx](const ScriptAnimatorRef& self, float value) { animatorSetTime(ctx, self, value); }),
            "play",
            [&ctx](const ScriptAnimatorRef & self, sol::optional<bool> restart) {
                return animatorPlay(ctx, self, restart);
            },
            "pause",
            [&ctx](const ScriptAnimatorRef & self) {
                return animatorPause(ctx, self);
            },
            "stop",
            [&ctx](const ScriptAnimatorRef & self) {
                return animatorStop(ctx, self);
            },
            "setNormalizedTime",
            [&ctx](const ScriptAnimatorRef & self, float normalizedTime) {
                return animatorSetNormalizedTime(ctx, self, normalizedTime);
            },
            "state",
            [&ctx](const ScriptAnimatorRef & self) {
                return animatorState(ctx, self);
            });

        {
            auto ns = script_binding::getOrCreateTable(lua, "Animation");
            ns.set_function("play",
                [&ctx](const ScriptEntity & entity, sol::optional<bool> restart) {
                    return animationPlay(ctx, entity, restart);
                });
            ns.set_function("pause",
                [&ctx](const ScriptEntity & entity) {
                    return animationPause(ctx, entity);
                });
            ns.set_function("stop",
                [&ctx](const ScriptEntity & entity) {
                    return animationStop(ctx, entity);
                });
            ns.set_function("setAnimation",
                [&ctx](const ScriptEntity & entity, const std::string & animationUuid, sol::optional<bool> restart) {
                    return animationSetAnimation(ctx, entity, animationUuid, restart);
                });
            ns.set_function("setTime",
                [&ctx](const ScriptEntity & entity, float seconds) {
                    return animationSetTime(ctx, entity, seconds);
                });
            ns.set_function("setNormalizedTime",
                [&ctx](const ScriptEntity & entity, float normalizedTime) {
                    return animationSetNormalizedTime(ctx, entity, normalizedTime);
                });
            ns.set_function("setSpeed",
                [&ctx](const ScriptEntity & entity, float speed) {
                    return animationSetSpeed(ctx, entity, speed);
                });
            ns.set_function("setLoop",
                [&ctx](const ScriptEntity & entity, bool loop) {
                    return animationSetLoop(ctx, entity, loop);
                });
            ns.set_function("state",
                [&ctx](const ScriptEntity & entity) {
                    return animationState(ctx, entity);
                });
            ns.set_function("jointCount",
                [&ctx](const std::string & skeletonUuid) {
                    return animationJointCount(ctx, skeletonUuid);
                });
            ns.set_function("duration",
                [&ctx](const std::string & animationUuid) {
                    return animationDuration(ctx, animationUuid);
                });
            ns.set_function("setFloat",
                [&ctx](const ScriptEntity & entity, const std::string & name, float value) {
                    return animationSetFloat(ctx, entity, name, value);
                });
            ns.set_function("setBool",
                [&ctx](const ScriptEntity & entity, const std::string & name, bool value) {
                    return animationSetBool(ctx, entity, name, value);
                });
            ns.set_function("setTrigger",
                [&ctx](const ScriptEntity & entity, const std::string & name) {
                    return animationSetTrigger(ctx, entity, name);
                });
            ns.set_function("getFloat",
                [&ctx](const ScriptEntity & entity, const std::string & name) {
                    return animationGetFloat(ctx, entity, name);
                });
            ns.set_function("getBool",
                [&ctx](const ScriptEntity & entity, const std::string & name) {
                    return animationGetBool(ctx, entity, name);
                });
            ns.set_function("currentState",
                [&ctx](sol::this_state luaState, const ScriptEntity & entity) {
                    return animationCurrentState(ctx, luaState, entity);
                });
        }

    }
} // namespace vultra
