// GENERATED by tools/python/extract_bindings.py + bindgen.backends.lua_sol2 -- DO NOT EDIT.
// Source of truth: tools/bindings/ir/bindings.ir.json (from VBIND_* annotations).

#include "vultra/function/scripting/bindings/script_i18n_binding.hpp"

#include "vultra/function/scripting/bindings/script_binding_common.hpp"
#include "vultra/function/scripting/script_context.hpp"
#include "vultra/function/scripting/script_types.hpp"
#include "vultra/function/scripting/bindings/script_i18n_shim.hpp"

#include <cstdint>
#include <string>

namespace vultra
{
    void registerScriptI18nBindings(sol::state& lua, ScriptContext& ctx)
    {
        (void)ctx;
        {
            auto ns = script_binding::getOrCreateTable(lua, "I18n");
            ns.set_function("tr",
                [&ctx](const std::string & key) {
                    return i18nTr(ctx, key);
                });
            ns.set_function("setLanguage",
                [&ctx](const std::string & locale) {
                    return i18nSetLanguage(ctx, locale);
                });
            ns.set_function("language",
                [&ctx]() {
                    return i18nLanguage(ctx);
                });
            ns.set_function("languages",
                [&ctx](sol::this_state luaState) {
                    return i18nLanguages(ctx, luaState);
                });
            ns.set_function("displayName",
                [&ctx](const std::string & locale) {
                    return i18nDisplayName(ctx, locale);
                });
            ns.set_function("setPseudolocalize",
                [&ctx](bool enabled) {
                    i18nSetPseudolocalize(ctx, enabled);
                });
        }

    }
} // namespace vultra
