// GENERATED by tools/python/extract_bindings.py + bindgen.backends.lua_sol2 -- DO NOT EDIT.
// Source of truth: tools/bindings/ir/bindings.ir.json (from VBIND_* annotations).

#include "vultra/function/scripting/bindings/script_audio_binding.hpp"

#include "vultra/function/scripting/bindings/script_binding_common.hpp"
#include "vultra/function/scripting/script_context.hpp"
#include "vultra/function/scripting/script_types.hpp"
#include "vultra/function/scripting/bindings/script_audio_shim.hpp"

#include <cstdint>
#include <string>

namespace vultra
{
    void registerScriptAudioBindings(sol::state& lua, ScriptContext& ctx)
    {
        (void)ctx;
        {
            auto ns = script_binding::getOrCreateTable(lua, "Audio");
            ns.set_function("preloadClip",
                [&ctx](const std::string & clip) {
                    return audioPreloadClip(ctx, clip);
                });
            ns.set_function("playOneShot",
                [&ctx](const std::string & clip, sol::optional<float> volume, sol::optional<float> pitch) {
                    return audioPlayOneShot(ctx, clip, volume, pitch);
                });
            ns.set_function("playOneShotAt",
                [&ctx](const std::string & clip, const glm::vec3 & position, sol::optional<float> volume, sol::optional<float> pitch) {
                    return audioPlayOneShotAt(ctx, clip, position, volume, pitch);
                });
            ns.set_function("playMusic",
                [&ctx](const std::string & clip, sol::optional<sol::table> options) {
                    return audioPlayMusic(ctx, clip, options);
                });
            ns.set_function("stopMusic",
                [&ctx](sol::optional<float> fadeOutMs) {
                    audioStopMusic(ctx, fadeOutMs);
                });
            ns.set_function("stopSound",
                [&ctx](SoundId id, sol::optional<float> fadeOutMs) {
                    audioStopSound(ctx, id, fadeOutMs);
                });
            ns.set_function("pauseSound",
                [&ctx](SoundId id) {
                    audioPauseSound(ctx, id);
                });
            ns.set_function("resumeSound",
                [&ctx](SoundId id) {
                    audioResumeSound(ctx, id);
                });
            ns.set_function("setVolume",
                [&ctx](SoundId id, float volume) {
                    audioSetVolume(ctx, id, volume);
                });
            ns.set_function("setPitch",
                [&ctx](SoundId id, float pitch) {
                    audioSetPitch(ctx, id, pitch);
                });
            ns.set_function("setLooping",
                [&ctx](SoundId id, bool loop) {
                    audioSetLooping(ctx, id, loop);
                });
            ns.set_function("isPlaying",
                [&ctx](SoundId id) {
                    return audioIsPlaying(ctx, id);
                });
            ns.set_function("play",
                [&ctx](const ScriptEntity & entity, sol::optional<bool> restart) {
                    return audioPlay(ctx, entity, restart);
                });
            ns.set_function("pause",
                [&ctx](const ScriptEntity & entity) {
                    return audioPause(ctx, entity);
                });
            ns.set_function("stop",
                [&ctx](const ScriptEntity & entity) {
                    return audioStop(ctx, entity);
                });
            ns.set_function("setMasterVolume",
                [&ctx](float volume) {
                    audioSetMasterVolume(ctx, volume);
                });
            ns.set_function("masterVolume",
                [&ctx]() {
                    return audioMasterVolume(ctx);
                });
            ns.set_function("backendReady",
                [&ctx]() {
                    return audioBackendReady(ctx);
                });
        }

    }
} // namespace vultra
