// GENERATED by tools/python/extract_bindings.py + bindgen.backends.lua_sol2 -- DO NOT EDIT.
// Source of truth: tools/bindings/ir/bindings.ir.json (from VBIND_* annotations).

#include "vultra/function/scripting/bindings/script_input_binding.hpp"

#include "vultra/function/scripting/bindings/script_binding_common.hpp"
#include "vultra/function/scripting/script_context.hpp"
#include "vultra/function/scripting/script_types.hpp"
#include "vultra/core/input/input_structs.hpp"
#include "vultra/core/services/input_service.hpp"

#include <glm/vec2.hpp>

#include <cstdint>
#include <string>

namespace vultra
{
    namespace
    {
        [[maybe_unused]] ScriptVec2 toScript(const glm::vec2& v) { return {v.x, v.y}; }
        [[maybe_unused]] glm::vec2 fromScript(const ScriptVec2& v) { return {v.x, v.y}; }
    } // namespace

    void registerScriptInputBindings(sol::state& lua, ScriptContext& ctx)
    {
        (void)ctx;
        {
            auto ns = script_binding::getOrCreateTable(lua, "Input");
            ns.set_function("isKeyHeld",
                [&ctx](int key) {
                    return ctx.inputService ? ctx.inputService->isKeyHeld(static_cast<vultra::KeyCode>(key)) : false;
                });
            ns.set_function("isKeyPressed",
                [&ctx](int key) {
                    return ctx.inputService ? ctx.inputService->isKeyPressed(static_cast<vultra::KeyCode>(key)) : false;
                });
            ns.set_function("isKeyReleased",
                [&ctx](int key) {
                    return ctx.inputService ? ctx.inputService->isKeyReleased(static_cast<vultra::KeyCode>(key)) : false;
                });
            ns.set_function("isKeyRepeated",
                [&ctx](int key) {
                    return ctx.inputService ? ctx.inputService->isKeyRepeated(static_cast<vultra::KeyCode>(key)) : false;
                });
            ns.set_function("isMouseButtonHeld",
                [&ctx](int button) {
                    return ctx.inputService ? ctx.inputService->isMouseButtonHeld(static_cast<vultra::MouseCode>(button)) : false;
                });
            ns.set_function("isMouseButtonPressed",
                [&ctx](int button) {
                    return ctx.inputService ? ctx.inputService->isMouseButtonPressed(static_cast<vultra::MouseCode>(button)) : false;
                });
            ns.set_function("isMouseButtonReleased",
                [&ctx](int button) {
                    return ctx.inputService ? ctx.inputService->isMouseButtonReleased(static_cast<vultra::MouseCode>(button)) : false;
                });
            ns.set_function("mouseButtonClicks",
                [&ctx](int button) {
                    return ctx.inputService ? ctx.inputService->mouseButtonClicks(static_cast<vultra::MouseCode>(button)) : 0;
                });
            ns.set_function("mousePosition",
                [&ctx]() {
                    return ctx.inputService ? toScript(ctx.inputService->mousePosition()) : ScriptVec2 {};
                });
            ns.set_function("mousePositionFlipY",
                [&ctx]() {
                    return ctx.inputService ? toScript(ctx.inputService->mousePositionFlipY()) : ScriptVec2 {};
                });
            ns.set_function("mousePositionDelta",
                [&ctx]() {
                    return ctx.inputService ? toScript(ctx.inputService->mousePositionDelta()) : ScriptVec2 {};
                });
            ns.set_function("mouseScrollDelta",
                [&ctx]() {
                    return ctx.inputService ? toScript(ctx.inputService->mouseScrollDelta()) : ScriptVec2 {};
                });
        }

        script_binding::bindEnumTable<vultra::KeyCode>(lua, "KeyCode");
        script_binding::bindEnumTable<vultra::MouseCode>(lua, "MouseCode");
    }
} // namespace vultra
