// GENERATED by tools/python/extract_bindings.py + bindgen.backends.lua_sol2 -- DO NOT EDIT.
// Source of truth: tools/bindings/ir/bindings.ir.json (from VBIND_* annotations).

#include "vultra/function/scripting/bindings/script_world_binding.hpp"

#include "vultra/function/scripting/bindings/script_binding_common.hpp"
#include "vultra/function/scripting/script_context.hpp"
#include "vultra/function/scripting/script_types.hpp"
#include "vultra/function/world/world.hpp"
#include "vultra/function/scripting/bindings/script_entity_shim.hpp"
#include "vultra/function/scripting/bindings/script_world_shim.hpp"

#include <cstdint>
#include <string>

namespace vultra
{
    void registerScriptWorldBindings(sol::state& lua, ScriptContext& ctx)
    {
        (void)ctx;
        lua.new_usertype<ScriptMeshRef>(
            "Mesh",
            "valid",
            script_binding::readonlyProperty([&ctx](const ScriptMeshRef& self) {
                auto* world = ctx.world();
                return world && world->registry().all_of<MeshComponent>(self.entity);
            }),
            "builtinGeometry",
            script_binding::property([&ctx](const ScriptMeshRef& self) { return meshGetBuiltinGeometry(ctx, self); },
            [&ctx](const ScriptMeshRef& self, std::uint32_t value) { meshSetBuiltinGeometry(ctx, self, value); }),
            "setMaterial",
            [&ctx](const ScriptMeshRef & self, std::uint32_t slot, const std::string & uri) {
                meshSetMaterial(ctx, self, slot, uri);
            },
            "setMaterialFloat",
            [&ctx](const ScriptMeshRef & self, std::uint32_t slot, const std::string & name, float value) {
                meshSetMaterialFloat(ctx, self, slot, name, value);
            },
            "setMaterialColor",
            [&ctx](const ScriptMeshRef & self, std::uint32_t slot, const std::string & name, const ScriptVec4 & value) {
                meshSetMaterialColor(ctx, self, slot, name, value);
            },
            "setMaterialTexture",
            [&ctx](const ScriptMeshRef & self, std::uint32_t slot, const std::string & name, const std::string & uri) {
                meshSetMaterialTexture(ctx, self, slot, name, uri);
            },
            "clearMaterialProperty",
            [&ctx](const ScriptMeshRef & self, std::uint32_t slot, const std::string & name) {
                meshClearMaterialProperty(ctx, self, slot, name);
            },
            "clearMaterialProperties",
            [&ctx](const ScriptMeshRef & self, std::uint32_t slot) {
                meshClearMaterialProperties(ctx, self, slot);
            });

        {
            auto ns = script_binding::getOrCreateTable(lua, "World");
            ns.set_function("create",
                [&ctx](sol::optional<std::string> name) {
                    return worldCreate(ctx, name);
                });
            ns.set_function("destroy",
                [&ctx](const ScriptEntity & entity) {
                    worldDestroy(ctx, entity);
                });
            ns.set_function("count",
                [&ctx]() {
                    return worldCount(ctx);
                });
            ns.set_function("findByName",
                [&ctx](const std::string & name) {
                    return worldFindByName(ctx, name);
                });
            ns.set_function("findByNamePrefix",
                [&ctx](sol::this_state luaState, const std::string & prefix) {
                    return worldFindByNamePrefix(ctx, luaState, prefix);
                });
            ns.set_function("entities",
                [&ctx](sol::this_state luaState) {
                    return worldEntities(ctx, luaState);
                });
        }

        script_binding::bindEnumTable<vultra::ScriptComponentType>(lua, "Component");
        worldRegisterLayerTable(lua, ctx);
        worldRegisterHelpers(lua, ctx);
    }
} // namespace vultra
