// GENERATED by tools/python/extract_bindings.py + bindgen.backends.lua_sol2 -- DO NOT EDIT.
// Source of truth: tools/bindings/ir/bindings.ir.json (from VBIND_* annotations).

#include "vultra/function/scripting/bindings/script_transform_binding.hpp"

#include "vultra/function/scripting/bindings/script_binding_common.hpp"
#include "vultra/function/scripting/script_context.hpp"
#include "vultra/function/scripting/script_types.hpp"
#include "vultra/function/scripting/bindings/script_transform_shim.hpp"

#include <cstdint>
#include <string>

namespace vultra
{
    void registerScriptTransformBindings(sol::state& lua, ScriptContext& ctx)
    {
        (void)ctx;
        lua.new_usertype<ScriptTransformRef>(
            "Transform",
            "position",
            script_binding::property([&ctx](const ScriptTransformRef& self) { return transformGetPosition(ctx, self); },
            [&ctx](const ScriptTransformRef& self, ScriptVec3 value) { transformSetPosition(ctx, self, value); }),
            "scale",
            script_binding::property([&ctx](const ScriptTransformRef& self) { return transformGetScale(ctx, self); },
            [&ctx](const ScriptTransformRef& self, ScriptVec3 value) { transformSetScale(ctx, self, value); }),
            "rotation",
            script_binding::property([&ctx](const ScriptTransformRef& self) { return transformGetRotation(ctx, self); },
            [&ctx](const ScriptTransformRef& self, ScriptVec3 value) { transformSetRotation(ctx, self, value); }),
            "rotationEuler",
            script_binding::property([&ctx](const ScriptTransformRef& self) { return transformGetRotationEuler(ctx, self); },
            [&ctx](const ScriptTransformRef& self, ScriptVec3 value) { transformSetRotationEuler(ctx, self, value); }),
            "translate",
            [&ctx](const ScriptTransformRef & self, const ScriptVec3 & delta) {
                transformTranslate(ctx, self, delta);
            },
            "setEulerDegrees",
            [&ctx](const ScriptTransformRef & self, const ScriptVec3 & value) {
                transformSetEulerDegrees(ctx, self, value);
            },
            "lookAt",
            [&ctx](const ScriptTransformRef & self, const ScriptVec3 & target) {
                transformLookAt(ctx, self, target);
            });

    }
} // namespace vultra
