// GENERATED by tools/python/extract_bindings.py + bindgen.backends.lua_sol2 -- DO NOT EDIT.
// Source of truth: tools/bindings/ir/bindings.ir.json (from VBIND_* annotations).

#include "vultra/function/scripting/bindings/script_upscaler_binding.hpp"

#include "vultra/function/scripting/bindings/script_binding_common.hpp"
#include "vultra/function/scripting/script_context.hpp"
#include "vultra/function/scripting/script_types.hpp"
#include "vultra/function/scripting/bindings/script_upscaler_shim.hpp"

#include <cstdint>
#include <string>

namespace vultra
{
    void registerScriptUpscalerBindings(sol::state& lua, ScriptContext& ctx)
    {
        (void)ctx;
        {
            auto ns = script_binding::getOrCreateTable(lua, "Upscaler");
            ns.set_function("providers",
                [&ctx](sol::this_state state) {
                    return upscalerProviders(ctx, state);
                });
            ns.set_function("active",
                [&ctx](sol::this_state state) {
                    return upscalerActive(ctx, state);
                });
            ns.set_function("setActive",
                [&ctx](const std::string & name) {
                    return upscalerSetActive(ctx, name);
                });
            ns.set_function("setEnabled",
                [&ctx](bool enabled) {
                    upscalerSetEnabled(ctx, enabled);
                });
            ns.set_function("setMode",
                [&ctx](const std::string & mode) {
                    upscalerSetMode(ctx, mode);
                });
            ns.set_function("status",
                [&ctx](sol::this_state state) {
                    return upscalerStatus(ctx, state);
                });
        }

    }
} // namespace vultra
