// GENERATED by tools/python/extract_bindings.py + bindgen.backends.lua_sol2 -- DO NOT EDIT.
// Source of truth: tools/bindings/ir/bindings.ir.json (from VBIND_* annotations).

#include "vultra/function/scripting/bindings/script_save_binding.hpp"

#include "vultra/function/scripting/bindings/script_binding_common.hpp"
#include "vultra/function/scripting/script_context.hpp"
#include "vultra/function/scripting/script_types.hpp"
#include "vultra/function/scripting/bindings/script_save_shim.hpp"

#include <cstdint>
#include <string>

namespace vultra
{
    void registerScriptSaveBindings(sol::state& lua, ScriptContext& ctx)
    {
        (void)ctx;
        {
            auto ns = script_binding::getOrCreateTable(lua, "Save");
            ns.set_function("set",
                [&ctx](const std::string & key, sol::object value) {
                    saveSet(ctx, key, value);
                });
            ns.set_function("get",
                [&ctx](sol::this_state luaState, const std::string & key, sol::object fallback) {
                    return saveGet(ctx, luaState, key, fallback);
                });
            ns.set_function("has",
                [&ctx](const std::string & key) {
                    return saveHas(ctx, key);
                });
            ns.set_function("remove",
                [&ctx](const std::string & key) {
                    saveRemove(ctx, key);
                });
            ns.set_function("clear",
                [&ctx]() {
                    saveClear(ctx);
                });
            ns.set_function("save",
                [&ctx](const std::string & slot) {
                    return saveSave(ctx, slot);
                });
            ns.set_function("load",
                [&ctx](const std::string & slot) {
                    return saveLoad(ctx, slot);
                });
            ns.set_function("hasSlot",
                [&ctx](const std::string & slot) {
                    return saveHasSlot(ctx, slot);
                });
            ns.set_function("deleteSlot",
                [&ctx](const std::string & slot) {
                    return saveDeleteSlot(ctx, slot);
                });
            ns.set_function("listSlots",
                [&ctx](sol::this_state luaState) {
                    return saveListSlots(ctx, luaState);
                });
        }

    }
} // namespace vultra
