// GENERATED by tools/python/extract_bindings.py + bindgen.backends.lua_sol2 -- DO NOT EDIT.
// Source of truth: tools/bindings/ir/bindings.ir.json (from VBIND_* annotations).

#include "vultra/function/scripting/bindings/script_entity_binding.hpp"

#include "vultra/function/scripting/bindings/script_binding_common.hpp"
#include "vultra/function/scripting/script_context.hpp"
#include "vultra/function/scripting/script_types.hpp"
#include "vultra/function/scripting/bindings/script_entity_shim.hpp"

#include <cstdint>
#include <string>

namespace vultra
{
    void registerScriptEntityBindings(sol::state& lua, ScriptContext& ctx)
    {
        (void)ctx;
        lua.new_usertype<ScriptEntity>(
            "Entity",
            "valid",
            script_binding::readonlyProperty([&ctx](const ScriptEntity& self) { return entityGetValid(ctx, self); }),
            "id",
            script_binding::readonlyProperty([&ctx](const ScriptEntity& self) { return entityGetId(ctx, self); }),
            "name",
            script_binding::property([&ctx](const ScriptEntity& self) { return entityGetName(ctx, self); },
            [&ctx](const ScriptEntity& self, std::string value) { entitySetName(ctx, self, value); }),
            "active",
            script_binding::property([&ctx](const ScriptEntity& self) { return entityGetActive(ctx, self); },
            [&ctx](const ScriptEntity& self, bool value) { entitySetActive(ctx, self, value); }),
            "visible",
            script_binding::property([&ctx](const ScriptEntity& self) { return entityGetVisible(ctx, self); },
            [&ctx](const ScriptEntity& self, bool value) { entitySetVisible(ctx, self, value); }),
            "transform",
            script_binding::readonlyProperty([&ctx](const ScriptEntity& self) { return entityTransform(ctx, self); }),
            "destroy",
            [&ctx](const ScriptEntity & self) {
                entityDestroy(ctx, self);
            },
            "parent",
            [&ctx](const ScriptEntity & self) {
                return entityParent(ctx, self);
            },
            "firstChild",
            [&ctx](const ScriptEntity & self) {
                return entityFirstChild(ctx, self);
            },
            "nextSibling",
            [&ctx](const ScriptEntity & self) {
                return entityNextSibling(ctx, self);
            },
            "setParent",
            [&ctx](const ScriptEntity & self, const ScriptEntity & parent) {
                entitySetParent(ctx, self, parent);
            });

        entityRegisterComponentApi(lua, ctx);
    }
} // namespace vultra
