// Generated by scripts/codegen.py. Do not edit.
#pragma once
#include <vultra/core/base/property.hpp>
#include <vultra/scene/render_nodes.hpp>

namespace vultra
{
    const ObjectTypeInfo& cameraSettingsType();
    const ObjectTypeInfo& environmentSettingsType();
    const ObjectTypeInfo& lightSettingsType();
} // namespace vultra
