-- Lua API conformance burn-down baseline. Generated by
-- test-lua-api-conformance --dump. May only shrink; see
-- doc/lua_api_design.md.
return {
    ["stub.missing:Layer"] = true,
    ["stub.missing:Layer.All"] = true,
    ["stub.missing:Layer.Default"] = true,
    ["stub.missing:Layer.UI"] = true,
    ["stub.missing:UI"] = true,
    ["stub.missing:UI.events"] = true,
    ["stub.missing:UI.hoveredEntity"] = true,
    ["stub.missing:UI.isPointerOverUI"] = true,
    ["stub.missing:UI.pressedEntity"] = true,
    ["stub.missing:UI.raycast"] = true,
    ["stub.missing:Ui"] = true,
    ["stub.missing:UiEvent"] = true,
    ["stub.missing:UiProgressBar"] = true,
    ["stub.missing:UiRaycastHit"] = true,
    ["stub.missing:UiSlider"] = true,
}
