// Generated by scripts/codegen.py. Do not edit.
#include <vultra/assets/material_properties.generated.hpp>

#include <array>

namespace vultra
{
    const ObjectTypeInfo& materialParametersType()
    {
        static const std::array<PropertyInfo, 23> properties = {{
            {"baseRed",
             "Base red",
             "MaterialParameters.baseRed",
             "/base_color/0",
             PropertyKind::eFloat,
             PropertyFlags::eSerialize | PropertyFlags::eInspect | PropertyFlags::eBind,
             PropertyWidget::eSlider,
             0,
             0,
             4,
             1,
             {},
             {},
             [](const void* object) -> PropertyValue
             {
                 return static_cast<const MaterialParameters*>(object)->baseRed;
             },
             [](void* object, const PropertyValue& value)
             {
                 static_cast<MaterialParameters*>(object)->baseRed = std::get<float>(value);
             },
             []() -> PropertyValue
             {
                 return MaterialParameters {}.baseRed;
             }},
            {"baseGreen",
             "Base green",
             "MaterialParameters.baseGreen",
             "/base_color/1",
             PropertyKind::eFloat,
             PropertyFlags::eSerialize | PropertyFlags::eInspect | PropertyFlags::eBind,
             PropertyWidget::eSlider,
             0,
             0,
             4,
             1,
             {},
             {},
             [](const void* object) -> PropertyValue
             {
                 return static_cast<const MaterialParameters*>(object)->baseGreen;
             },
             [](void* object, const PropertyValue& value)
             {
                 static_cast<MaterialParameters*>(object)->baseGreen = std::get<float>(value);
             },
             []() -> PropertyValue
             {
                 return MaterialParameters {}.baseGreen;
             }},
            {"baseBlue",
             "Base blue",
             "MaterialParameters.baseBlue",
             "/base_color/2",
             PropertyKind::eFloat,
             PropertyFlags::eSerialize | PropertyFlags::eInspect | PropertyFlags::eBind,
             PropertyWidget::eSlider,
             0,
             0,
             4,
             1,
             {},
             {},
             [](const void* object) -> PropertyValue
             {
                 return static_cast<const MaterialParameters*>(object)->baseBlue;
             },
             [](void* object, const PropertyValue& value)
             {
                 static_cast<MaterialParameters*>(object)->baseBlue = std::get<float>(value);
             },
             []() -> PropertyValue
             {
                 return MaterialParameters {}.baseBlue;
             }},
            {"baseAlpha",
             "Base alpha",
             "MaterialParameters.baseAlpha",
             "/base_color/3",
             PropertyKind::eFloat,
             PropertyFlags::eSerialize | PropertyFlags::eInspect | PropertyFlags::eBind,
             PropertyWidget::eSlider,
             0,
             0,
             1,
             1,
             {},
             {},
             [](const void* object) -> PropertyValue
             {
                 return static_cast<const MaterialParameters*>(object)->baseAlpha;
             },
             [](void* object, const PropertyValue& value)
             {
                 static_cast<MaterialParameters*>(object)->baseAlpha = std::get<float>(value);
             },
             []() -> PropertyValue
             {
                 return MaterialParameters {}.baseAlpha;
             }},
            {"baseWeight",
             "Base weight",
             "MaterialParameters.baseWeight",
             "/base_weight",
             PropertyKind::eFloat,
             PropertyFlags::eSerialize | PropertyFlags::eInspect | PropertyFlags::eBind,
             PropertyWidget::eSlider,
             0,
             0,
             1,
             1,
             {},
             {},
             [](const void* object) -> PropertyValue
             {
                 return static_cast<const MaterialParameters*>(object)->baseWeight;
             },
             [](void* object, const PropertyValue& value)
             {
                 static_cast<MaterialParameters*>(object)->baseWeight = std::get<float>(value);
             },
             []() -> PropertyValue
             {
                 return MaterialParameters {}.baseWeight;
             }},
            {"baseMetalness",
             "Metalness",
             "MaterialParameters.baseMetalness",
             "/metalness",
             PropertyKind::eFloat,
             PropertyFlags::eSerialize | PropertyFlags::eInspect | PropertyFlags::eBind,
             PropertyWidget::eSlider,
             0,
             0,
             1,
             1,
             {},
             {},
             [](const void* object) -> PropertyValue
             {
                 return static_cast<const MaterialParameters*>(object)->baseMetalness;
             },
             [](void* object, const PropertyValue& value)
             {
                 static_cast<MaterialParameters*>(object)->baseMetalness = std::get<float>(value);
             },
             []() -> PropertyValue
             {
                 return MaterialParameters {}.baseMetalness;
             }},
            {"baseDiffuseRoughness",
             "Diffuse roughness",
             "MaterialParameters.baseDiffuseRoughness",
             "/diffuse_roughness",
             PropertyKind::eFloat,
             PropertyFlags::eSerialize | PropertyFlags::eInspect | PropertyFlags::eBind,
             PropertyWidget::eSlider,
             0,
             0,
             1,
             1,
             {},
             {},
             [](const void* object) -> PropertyValue
             {
                 return static_cast<const MaterialParameters*>(object)->baseDiffuseRoughness;
             },
             [](void* object, const PropertyValue& value)
             {
                 static_cast<MaterialParameters*>(object)->baseDiffuseRoughness = std::get<float>(value);
             },
             []() -> PropertyValue
             {
                 return MaterialParameters {}.baseDiffuseRoughness;
             }},
            {"specularWeight",
             "Specular weight",
             "MaterialParameters.specularWeight",
             "/specular_weight",
             PropertyKind::eFloat,
             PropertyFlags::eSerialize | PropertyFlags::eInspect | PropertyFlags::eBind,
             PropertyWidget::eSlider,
             0,
             0,
             1,
             1,
             {},
             {},
             [](const void* object) -> PropertyValue
             {
                 return static_cast<const MaterialParameters*>(object)->specularWeight;
             },
             [](void* object, const PropertyValue& value)
             {
                 static_cast<MaterialParameters*>(object)->specularWeight = std::get<float>(value);
             },
             []() -> PropertyValue
             {
                 return MaterialParameters {}.specularWeight;
             }},
            {"specularRed",
             "Specular red",
             "MaterialParameters.specularRed",
             "/specular_color/0",
             PropertyKind::eFloat,
             PropertyFlags::eSerialize | PropertyFlags::eInspect | PropertyFlags::eBind,
             PropertyWidget::eSlider,
             0,
             0,
             4,
             1,
             {},
             {},
             [](const void* object) -> PropertyValue
             {
                 return static_cast<const MaterialParameters*>(object)->specularRed;
             },
             [](void* object, const PropertyValue& value)
             {
                 static_cast<MaterialParameters*>(object)->specularRed = std::get<float>(value);
             },
             []() -> PropertyValue
             {
                 return MaterialParameters {}.specularRed;
             }},
            {"specularGreen",
             "Specular green",
             "MaterialParameters.specularGreen",
             "/specular_color/1",
             PropertyKind::eFloat,
             PropertyFlags::eSerialize | PropertyFlags::eInspect | PropertyFlags::eBind,
             PropertyWidget::eSlider,
             0,
             0,
             4,
             1,
             {},
             {},
             [](const void* object) -> PropertyValue
             {
                 return static_cast<const MaterialParameters*>(object)->specularGreen;
             },
             [](void* object, const PropertyValue& value)
             {
                 static_cast<MaterialParameters*>(object)->specularGreen = std::get<float>(value);
             },
             []() -> PropertyValue
             {
                 return MaterialParameters {}.specularGreen;
             }},
            {"specularBlue",
             "Specular blue",
             "MaterialParameters.specularBlue",
             "/specular_color/2",
             PropertyKind::eFloat,
             PropertyFlags::eSerialize | PropertyFlags::eInspect | PropertyFlags::eBind,
             PropertyWidget::eSlider,
             0,
             0,
             4,
             1,
             {},
             {},
             [](const void* object) -> PropertyValue
             {
                 return static_cast<const MaterialParameters*>(object)->specularBlue;
             },
             [](void* object, const PropertyValue& value)
             {
                 static_cast<MaterialParameters*>(object)->specularBlue = std::get<float>(value);
             },
             []() -> PropertyValue
             {
                 return MaterialParameters {}.specularBlue;
             }},
            {"specularRoughness",
             "Roughness",
             "MaterialParameters.specularRoughness",
             "/roughness",
             PropertyKind::eFloat,
             PropertyFlags::eSerialize | PropertyFlags::eInspect | PropertyFlags::eBind,
             PropertyWidget::eSlider,
             0,
             0,
             1,
             1,
             {},
             {},
             [](const void* object) -> PropertyValue
             {
                 return static_cast<const MaterialParameters*>(object)->specularRoughness;
             },
             [](void* object, const PropertyValue& value)
             {
                 static_cast<MaterialParameters*>(object)->specularRoughness = std::get<float>(value);
             },
             []() -> PropertyValue
             {
                 return MaterialParameters {}.specularRoughness;
             }},
            {"specularIor",
             "Specular IOR",
             "MaterialParameters.specularIor",
             "/specular_ior",
             PropertyKind::eFloat,
             PropertyFlags::eSerialize | PropertyFlags::eInspect | PropertyFlags::eBind,
             PropertyWidget::eSlider,
             0,
             1,
             3,
             1,
             {},
             {},
             [](const void* object) -> PropertyValue
             {
                 return static_cast<const MaterialParameters*>(object)->specularIor;
             },
             [](void* object, const PropertyValue& value)
             {
                 static_cast<MaterialParameters*>(object)->specularIor = std::get<float>(value);
             },
             []() -> PropertyValue
             {
                 return MaterialParameters {}.specularIor;
             }},
            {"coatWeight",
             "Coat weight",
             "MaterialParameters.coatWeight",
             "/coat_weight",
             PropertyKind::eFloat,
             PropertyFlags::eSerialize | PropertyFlags::eInspect | PropertyFlags::eBind,
             PropertyWidget::eSlider,
             0,
             0,
             1,
             1,
             {},
             {},
             [](const void* object) -> PropertyValue
             {
                 return static_cast<const MaterialParameters*>(object)->coatWeight;
             },
             [](void* object, const PropertyValue& value)
             {
                 static_cast<MaterialParameters*>(object)->coatWeight = std::get<float>(value);
             },
             []() -> PropertyValue
             {
                 return MaterialParameters {}.coatWeight;
             }},
            {"coatRoughness",
             "Coat roughness",
             "MaterialParameters.coatRoughness",
             "/coat_roughness",
             PropertyKind::eFloat,
             PropertyFlags::eSerialize | PropertyFlags::eInspect | PropertyFlags::eBind,
             PropertyWidget::eSlider,
             0,
             0,
             1,
             1,
             {},
             {},
             [](const void* object) -> PropertyValue
             {
                 return static_cast<const MaterialParameters*>(object)->coatRoughness;
             },
             [](void* object, const PropertyValue& value)
             {
                 static_cast<MaterialParameters*>(object)->coatRoughness = std::get<float>(value);
             },
             []() -> PropertyValue
             {
                 return MaterialParameters {}.coatRoughness;
             }},
            {"coatIor",
             "Coat IOR",
             "MaterialParameters.coatIor",
             "/coat_ior",
             PropertyKind::eFloat,
             PropertyFlags::eSerialize | PropertyFlags::eInspect | PropertyFlags::eBind,
             PropertyWidget::eSlider,
             0,
             1,
             3,
             1,
             {},
             {},
             [](const void* object) -> PropertyValue
             {
                 return static_cast<const MaterialParameters*>(object)->coatIor;
             },
             [](void* object, const PropertyValue& value)
             {
                 static_cast<MaterialParameters*>(object)->coatIor = std::get<float>(value);
             },
             []() -> PropertyValue
             {
                 return MaterialParameters {}.coatIor;
             }},
            {"emissionRed",
             "Emission red",
             "MaterialParameters.emissionRed",
             "/emission_color/0",
             PropertyKind::eFloat,
             PropertyFlags::eSerialize | PropertyFlags::eInspect | PropertyFlags::eBind,
             PropertyWidget::eSlider,
             0,
             0,
             4,
             1,
             {},
             {},
             [](const void* object) -> PropertyValue
             {
                 return static_cast<const MaterialParameters*>(object)->emissionRed;
             },
             [](void* object, const PropertyValue& value)
             {
                 static_cast<MaterialParameters*>(object)->emissionRed = std::get<float>(value);
             },
             []() -> PropertyValue
             {
                 return MaterialParameters {}.emissionRed;
             }},
            {"emissionGreen",
             "Emission green",
             "MaterialParameters.emissionGreen",
             "/emission_color/1",
             PropertyKind::eFloat,
             PropertyFlags::eSerialize | PropertyFlags::eInspect | PropertyFlags::eBind,
             PropertyWidget::eSlider,
             0,
             0,
             4,
             1,
             {},
             {},
             [](const void* object) -> PropertyValue
             {
                 return static_cast<const MaterialParameters*>(object)->emissionGreen;
             },
             [](void* object, const PropertyValue& value)
             {
                 static_cast<MaterialParameters*>(object)->emissionGreen = std::get<float>(value);
             },
             []() -> PropertyValue
             {
                 return MaterialParameters {}.emissionGreen;
             }},
            {"emissionBlue",
             "Emission blue",
             "MaterialParameters.emissionBlue",
             "/emission_color/2",
             PropertyKind::eFloat,
             PropertyFlags::eSerialize | PropertyFlags::eInspect | PropertyFlags::eBind,
             PropertyWidget::eSlider,
             0,
             0,
             4,
             1,
             {},
             {},
             [](const void* object) -> PropertyValue
             {
                 return static_cast<const MaterialParameters*>(object)->emissionBlue;
             },
             [](void* object, const PropertyValue& value)
             {
                 static_cast<MaterialParameters*>(object)->emissionBlue = std::get<float>(value);
             },
             []() -> PropertyValue
             {
                 return MaterialParameters {}.emissionBlue;
             }},
            {"emissionLuminance",
             "Emission luminance",
             "MaterialParameters.emissionLuminance",
             "/emission_luminance",
             PropertyKind::eFloat,
             PropertyFlags::eSerialize | PropertyFlags::eInspect | PropertyFlags::eBind,
             PropertyWidget::eSlider,
             0,
             0,
             100,
             1,
             {},
             {},
             [](const void* object) -> PropertyValue
             {
                 return static_cast<const MaterialParameters*>(object)->emissionLuminance;
             },
             [](void* object, const PropertyValue& value)
             {
                 static_cast<MaterialParameters*>(object)->emissionLuminance = std::get<float>(value);
             },
             []() -> PropertyValue
             {
                 return MaterialParameters {}.emissionLuminance;
             }},
            {"normalScale",
             "Normal scale",
             "MaterialParameters.normalScale",
             "/normal_scale",
             PropertyKind::eFloat,
             PropertyFlags::eSerialize | PropertyFlags::eInspect | PropertyFlags::eBind,
             PropertyWidget::eSlider,
             0,
             0,
             4,
             1,
             {},
             {},
             [](const void* object) -> PropertyValue
             {
                 return static_cast<const MaterialParameters*>(object)->normalScale;
             },
             [](void* object, const PropertyValue& value)
             {
                 static_cast<MaterialParameters*>(object)->normalScale = std::get<float>(value);
             },
             []() -> PropertyValue
             {
                 return MaterialParameters {}.normalScale;
             }},
            {"occlusionStrength",
             "Occlusion strength",
             "MaterialParameters.occlusionStrength",
             "/occlusion_strength",
             PropertyKind::eFloat,
             PropertyFlags::eSerialize | PropertyFlags::eInspect | PropertyFlags::eBind,
             PropertyWidget::eSlider,
             0,
             0,
             1,
             1,
             {},
             {},
             [](const void* object) -> PropertyValue
             {
                 return static_cast<const MaterialParameters*>(object)->occlusionStrength;
             },
             [](void* object, const PropertyValue& value)
             {
                 static_cast<MaterialParameters*>(object)->occlusionStrength = std::get<float>(value);
             },
             []() -> PropertyValue
             {
                 return MaterialParameters {}.occlusionStrength;
             }},
            {"alphaCutoff",
             "Alpha cutoff",
             "MaterialParameters.alphaCutoff",
             "/alpha_cutoff",
             PropertyKind::eFloat,
             PropertyFlags::eSerialize | PropertyFlags::eInspect | PropertyFlags::eBind,
             PropertyWidget::eSlider,
             0,
             -1,
             1,
             1,
             {},
             {},
             [](const void* object) -> PropertyValue
             {
                 return static_cast<const MaterialParameters*>(object)->alphaCutoff;
             },
             [](void* object, const PropertyValue& value)
             {
                 static_cast<MaterialParameters*>(object)->alphaCutoff = std::get<float>(value);
             },
             []() -> PropertyValue
             {
                 return MaterialParameters {}.alphaCutoff;
             }},
        }};
        static const ObjectTypeInfo               type       = {"MaterialParameters", properties};
        return type;
    }

} // namespace vultra
