target("test-camera")
    set_kind("binary")
    set_default(false)
    add_deps("vultra")
    add_files("camera.cpp", "../examples/common/colored_mesh.cpp")
    set_rundir("$(projectdir)")
    add_tests("default")
target_end()

target("test-benchmark")
    set_kind("binary")
    set_default(false)
    add_deps("vultra")
    add_files("benchmark.cpp")
    set_rundir("$(projectdir)")
    add_tests("default")
target_end()

target("test-cli")
    set_kind("binary")
    set_default(false)
    add_deps("vultra")
    add_files("command_line.cpp")
    set_rundir("$(projectdir)")
    add_tests("default")
target_end()

target("test-asset-pipeline")
    set_kind("binary")
    set_default(false)
    add_deps("vultra")
    add_files("asset_pipeline.cpp")
    set_rundir("$(projectdir)")
    add_tests("default")
target_end()

target("test-asset-formats")
    set_kind("binary")
    set_default(false)
    add_deps("vultra")
    add_files("asset_formats.cpp")
    set_rundir("$(projectdir)")
    add_tests("default")
target_end()

target("test-desktop")
    set_kind("binary")
    set_default(false)
    add_deps("vultra")
    add_files("desktop.cpp")
    set_rundir("$(projectdir)")
    add_tests("default")
target_end()

target("test-image")
    set_kind("binary")
    set_default(false)
    add_deps("vultra")
    add_files("image.cpp")
    set_rundir("$(projectdir)")
    add_tests("default")
target_end()

target("test-rendering")
    set_kind("binary")
    set_default(false)
    add_deps("vultra", "openpbr")
    add_files("rendering.cpp")
    set_rundir("$(projectdir)")
    add_tests("default")
target_end()

target("test-gltf-materials")
    set_kind("binary")
    set_default(false)
    add_deps("vultra")
    add_files("gltf_materials.cpp")
    set_rundir("$(projectdir)")
    add_tests("default")
target_end()

target("test-debugdraw")
    set_kind("binary")
    set_default(false)
    add_deps("vultra")
    add_files("debug_draw.cpp", "../examples/common/colored_mesh.cpp")
    set_rundir("$(projectdir)")
    add_tests("default")
target_end()

target("test-meshlets")
    set_kind("binary")
    set_default(false)
    add_deps("vultra")
    add_files("meshlets.cpp")
    set_rundir("$(projectdir)")
    add_tests("default")
target_end()

target("test-gpu")
    set_kind("binary")
    set_default(false)
    add_deps("vultra")
    add_files("gpu.cpp")
    set_rundir("$(projectdir)")
    add_tests("default")
target_end()


target("test-display")
    set_kind("binary")
    set_default(false)
    add_deps("vultra")
    add_files("display.cpp", "../examples/common/colored_mesh.cpp")
    set_rundir("$(projectdir)")
    add_tests("default")
target_end()


target("test-gui-settings")
    set_kind("binary")
    set_default(false)
    add_deps("vultra")
    add_files("gui_settings.cpp")
    set_rundir("$(projectdir)")
    add_tests("default")
target_end()

if is_plat("linux") then
    -- Exercise POSIX replacement while a concurrent reader holds the previous file open.
    target("test-platform")
        set_kind("binary")
        set_default(false)
        add_deps("vultra")
        add_files("platform.cpp")
        set_rundir("$(projectdir)")
        add_tests("default")
    target_end()
end

target("test-window")
    set_kind("binary")
    set_default(false)
    add_deps("vultra")
    add_files("window.cpp")
    set_rundir("$(projectdir)")
    add_tests("default")
target_end()

target("test-native-plugin-bad")
    set_kind("shared")
    set_default(false)
    set_languages("c11")
    add_includedirs("../source/api/include")
    add_files("native_plugin_bad.c")
target_end()

target("test-native-plugin")
    set_kind("binary")
    set_default(false)
    add_deps("vultra")
    add_deps("example-native-plugin", "test-native-plugin-bad", {inherit = false})
    add_files("native_plugin.cpp")
    set_rundir("$(projectdir)")
    add_tests("default")
target_end()

target("test-scene")
    set_kind("binary")
    set_default(false)
    add_deps("vultra")
    add_files("scene.cpp")
    set_rundir("$(projectdir)")
    add_tests("default")
target_end()

target("test-vpk")
    set_kind("binary")
    set_default(false)
    add_deps("vultra")
    add_files("vpk.cpp")
    set_rundir("$(projectdir)")
    add_tests("default")
target_end()

target("test-native-script-classes")
    set_kind("shared")
    set_default(false)
    add_includedirs("../source/api/include", "../source/scripting/include")
    add_files("native_script_classes.cpp")
target_end()

target("test-native-script-classes-replacement")
    set_kind("shared")
    set_default(false)
    add_includedirs("../source/api/include", "../source/scripting/include")
    add_files("native_script_classes_replacement.cpp")
target_end()

target("test-script-host")
    set_kind("binary")
    set_default(false)
    add_deps("vultra-scripting")
    add_deps("example-native-plugin", "example-native-cpp-plugin", "test-native-plugin-bad", "test-native-script-classes",
             "test-native-script-classes-replacement", {inherit = false})
    add_files("script_host.cpp")
    set_rundir("$(projectdir)")
    add_tests("default")
target_end()
