target("test-shader-surface")
    set_kind("binary")
    set_default(false)
    add_deps("vultra")
    add_files("shader_surface.cpp")
    set_rundir("$(projectdir)")
    add_tests("default")
target_end()

target("test-shader-material")
    set_kind("binary")
    set_default(false)
    add_deps("vultra")
    add_files("shader_material.cpp")
    set_rundir("$(projectdir)")
    add_tests("default")
target_end()

target("test-shader-asset")
    set_kind("binary")
    set_default(false)
    add_deps("vultra")
    add_files("shader_asset.cpp")
    set_rundir("$(projectdir)")
    add_tests("default")
target_end()

target("test-camera")
    set_kind("binary")
    set_default(false)
    add_deps("vultra")
    add_files("camera.cpp", "../examples/common/colored_mesh.cpp")
    set_rundir("$(projectdir)")
    add_tests("default")
    add_tests("offline", {runargs = {"--offline"}})
target_end()

target("test-benchmark")
    set_kind("binary")
    set_default(false)
    add_deps("vultra")
    add_files("benchmark.cpp")
    set_rundir("$(projectdir)")
    add_tests("default")
target_end()

target("test-cli")
    set_kind("binary")
    set_default(false)
    add_deps("vultra")
    add_files("command_line.cpp")
    set_rundir("$(projectdir)")
    add_tests("default")
target_end()

target("test-asset-pipeline")
    set_kind("binary")
    set_default(false)
    add_deps("vultra")
    add_files("asset_pipeline.cpp")
    set_rundir("$(projectdir)")
    add_tests("default")
target_end()

target("test-asset-formats")
    set_kind("binary")
    set_default(false)
    add_deps("vultra")
    add_files("asset_formats.cpp")
    set_rundir("$(projectdir)")
    add_tests("default")
target_end()

target("test-desktop")
    set_kind("binary")
    set_default(false)
    add_deps("vultra")
    add_files("desktop.cpp")
    set_rundir("$(projectdir)")
    add_tests("default")
target_end()

target("test-image")
    set_kind("binary")
    set_default(false)
    add_deps("vultra")
    add_files("image.cpp")
    set_rundir("$(projectdir)")
    add_tests("default")
target_end()

target("test-rendering")
    set_kind("binary")
    set_default(false)
    add_deps("vultra", "openpbr")
    add_files("rendering.cpp")
    set_rundir("$(projectdir)")
    add_tests("default")
target_end()

target("test-graph-definition")
    set_kind("binary")
    set_default(false)
    add_deps("vultra")
    add_files("graph_definition.cpp", "../examples/research/color_gain.cpp")
    set_rundir("$(projectdir)")
    add_tests("default")
target_end()

target("test-experiment-description")
    set_kind("binary")
    set_default(false)
    add_deps("vultra")
    add_packages("nlohmann_json")
    add_files("experiment_description.cpp")
    set_rundir("$(projectdir)")
    add_tests("default")
target_end()

target("test-experiment-session")
    set_kind("binary")
    set_default(false)
    add_deps("vultra")
    add_files("experiment_session.cpp", "../examples/research/color_gain.cpp")
    set_rundir("$(projectdir)")
    add_tests("default")
target_end()

target("test-experiment-host")
    set_kind("binary")
    set_default(false)
    add_deps("vultra-scripting")
    add_files("experiment_host.cpp", "../examples/research/color_gain.cpp")
    set_rundir("$(projectdir)")
    add_tests("default")
target_end()

target("test-graph-editor")
    set_kind("binary")
    set_default(false)
    add_deps("vultra")
    add_packages("nlohmann_json", "imgui-node-editor")
    add_files("graph_editor.cpp", "../editor/src/graph_editor.cpp", "../editor/src/research_workspace.cpp",
              "../examples/research/color_gain.cpp")
    set_rundir("$(projectdir)")
    add_tests("default")
target_end()

target("test-scene-inspector")
    set_kind("binary")
    set_default(false)
    add_deps("vultra")
    add_packages("nlohmann_json")
    add_files("scene_inspector.cpp", "../editor/src/scene_inspector.cpp", "../editor/src/research_workspace.cpp",
              "../examples/research/color_gain.cpp")
    set_rundir("$(projectdir)")
    add_tests("default")
target_end()

target("test-research-workspace")
    set_kind("binary")
    set_default(false)
    add_deps("vultra")
    add_packages("nlohmann_json")
    add_files("research_workspace.cpp", "../editor/src/research_workspace.cpp", "../examples/research/color_gain.cpp")
    set_rundir("$(projectdir)")
    add_tests("default")
target_end()

target("test-gltf-materials")
    set_kind("binary")
    set_default(false)
    add_deps("vultra")
    add_files("gltf_materials.cpp")
    set_rundir("$(projectdir)")
    add_tests("default")
target_end()

target("test-debugdraw")
    set_kind("binary")
    set_default(false)
    add_deps("vultra")
    add_files("debug_draw.cpp", "../examples/common/colored_mesh.cpp")
    set_rundir("$(projectdir)")
    add_tests("default")
target_end()

target("test-meshlets")
    set_kind("binary")
    set_default(false)
    add_deps("vultra")
    add_deps("vultra-builtin-pack", {inherit = false})
    add_files("meshlets.cpp")
    set_rundir("$(projectdir)")
    add_tests("default")
    add_tests("cooked", {runargs = {"--cooked"}})
target_end()

target("test-gpu")
    set_kind("binary")
    set_default(false)
    add_deps("vultra")
    add_files("gpu.cpp")
    add_packages("nlohmann_json")
    set_rundir("$(projectdir)")
    add_tests("default")
    add_tests("offline", {runargs = {"--offline"}})
target_end()


target("test-display")
    set_kind("binary")
    set_default(false)
    add_deps("vultra")
    add_files("display.cpp", "../examples/common/colored_mesh.cpp")
    set_rundir("$(projectdir)")
    add_tests("default")
target_end()


target("test-gui-settings")
    set_kind("binary")
    set_default(false)
    add_deps("vultra")
    add_files("gui_settings.cpp")
    set_rundir("$(projectdir)")
    add_tests("default")
target_end()

target("test-gui-offscreen")
    set_kind("binary")
    set_default(false)
    add_deps("vultra")
    add_files("gui_offscreen.cpp")
    set_rundir("$(projectdir)")
    add_tests("default")
target_end()

target("test-vgui-offscreen")
    set_kind("binary")
    set_default(false)
    add_deps("vultra-vgui")
    add_files("vgui_offscreen.cpp")
    set_rundir("$(projectdir)")
    add_tests("default")
target_end()

if is_plat("linux") then
    -- Exercise POSIX replacement while a concurrent reader holds the previous file open.
    target("test-platform")
        set_kind("binary")
        set_default(false)
        add_deps("vultra")
        add_files("platform.cpp")
        set_rundir("$(projectdir)")
        add_tests("default")
    target_end()
end

target("test-window")
    set_kind("binary")
    set_default(false)
    add_deps("vultra")
    add_files("window.cpp")
    set_rundir("$(projectdir)")
    add_tests("default")
target_end()

target("test-native-plugin-bad")
    set_kind("shared")
    set_default(false)
    set_languages("c11")
    add_includedirs("../source/api/include")
    add_files("native_plugin_bad.c")
target_end()

target("test-native-plugin")
    set_kind("binary")
    set_default(false)
    add_deps("vultra")
    add_includedirs("../source/scripting/include")
    add_deps("example-native-plugin", "test-native-plugin-bad", {inherit = false})
    add_files("native_plugin.cpp")
    set_rundir("$(projectdir)")
    add_tests("default")
target_end()

target("test-properties")
    set_kind("binary")
    set_default(false)
    add_deps("vultra")
    add_packages("nlohmann_json")
    add_files("properties.cpp")
    set_rundir("$(projectdir)")
    add_tests("default")
target_end()

target("test-scene")
    set_kind("binary")
    set_default(false)
    add_deps("vultra")
    add_packages("nlohmann_json")
    add_files("scene.cpp")
    set_rundir("$(projectdir)")
    add_tests("default")
target_end()

target("test-vpk")
    set_kind("binary")
    set_default(false)
    add_deps("vultra")
    add_files("vpk.cpp")
    set_rundir("$(projectdir)")
    add_tests("default")
target_end()

target("test-native-script-classes")
    set_kind("shared")
    set_default(false)
    add_includedirs("../source/api/include", "../source/scripting/include")
    add_files("native_script_classes.cpp")
target_end()

target("test-native-script-classes-replacement")
    set_kind("shared")
    set_default(false)
    add_includedirs("../source/api/include", "../source/scripting/include")
    add_files("native_script_classes_replacement.cpp")
target_end()

target("test-script-host")
    set_kind("binary")
    set_default(false)
    add_deps("vultra-scripting")
    add_deps("example-native-plugin", "example-native-cpp-plugin", "test-native-plugin-bad", "test-native-script-classes",
             "test-native-script-classes-replacement", {inherit = false})
    add_files("script_host.cpp")
    set_rundir("$(projectdir)")
    add_tests("default")
target_end()

target("test-native-scene-script")
    set_kind("shared")
    set_default(false)
    add_includedirs("../source/api/include", "../source/scripting/include")
    add_files("scene_scripts/native.cpp")
target_end()

target("test-managed-scene-script")
    set_kind("phony")
    set_default(false)
    add_deps("vultra-managed-host", {inherit = false})
    on_build(function ()
        local output = path.join(os.projectdir(), "build", ".tmp", "scripting-managed")
        os.execv("dotnet", {"build", path.join(os.projectdir(), "tests", "scene_scripts", "Vultra.SceneScripts.csproj"),
                           "-c", "Release", "-o", output, "--nologo", "--no-dependencies"})
    end)
target_end()

target("test-scene-rendering")
    set_kind("binary")
    set_default(false)
    add_deps("vultra-scripting")
    add_deps("test-native-scene-script", "test-managed-scene-script", {inherit = false})
    add_files("scene_rendering.cpp")
    set_rundir("$(projectdir)")
    add_tests("default")
target_end()

target("test-graph-resources")
    set_kind("binary")
    set_default(false)
    add_deps("vultra")
    add_files("graph_resources.cpp")
    set_rundir("$(projectdir)")
    add_tests("default")
target_end()

target("test-reference-path-tracer")
    set_kind("binary")
    set_default(false)
    add_deps("vultra", "openpbr")
    add_files("reference_path_tracer.cpp")
    set_rundir("$(projectdir)")
    add_tests("default")
target_end()

target("test-shader-program")
    set_kind("binary")
    set_default(false)
    add_deps("vultra")
    add_packages("nlohmann_json", "xxhash")
    add_files("shader_program.cpp")
    set_rundir("$(projectdir)")
    add_tests("default")
target_end()

target("test-shader-project")
    set_kind("binary")
    set_default(false)
    add_deps("vultra")
    add_files("shader_project.cpp")
    set_rundir("$(projectdir)")
    add_tests("default")
target_end()

target("test-shader-layout")
    set_kind("binary")
    set_default(false)
    add_deps("vultra")
    add_files("shader_layout.cpp")
    set_rundir("$(projectdir)")
    add_tests("default")
target_end()

target("test-shader-textures")
    set_kind("binary")
    set_default(false)
    add_deps("vultra")
    add_files("shader_textures.cpp")
    set_rundir("$(projectdir)")
    add_tests("default")
target_end()

target("test-shader-inspector")
    set_kind("binary")
    set_default(false)
    add_deps("vultra")
    add_files("shader_inspector.cpp")
    set_rundir("$(projectdir)")
    add_tests("default")
target_end()

target("test-shader-compiler")
    set_kind("binary")
    set_default(false)
    add_deps("vultra")
    add_packages("nlohmann_json", "xxhash")
    add_files("shader_compiler.cpp")
    set_rundir("$(projectdir)")
    add_tests("default")
target_end()
