target("test-camera")
    set_kind("binary")
    set_default(false)
    add_deps("vultra")
    add_files("camera.cpp", "../examples/common/colored_mesh.cpp")
    set_rundir("$(projectdir)")
    add_tests("default")
target_end()

target("test-cli")
    set_kind("binary")
    set_default(false)
    add_deps("vultra")
    add_files("command_line.cpp")
    set_rundir("$(projectdir)")
    add_tests("default")
target_end()

target("test-asset-pipeline")
    set_kind("binary")
    set_default(false)
    add_deps("vultra-renderer")
    add_files("asset_pipeline.cpp")
    set_rundir("$(projectdir)")
    add_tests("default")
target_end()

target("test-asset-formats")
    set_kind("binary")
    set_default(false)
    add_deps("vultra-renderer")
    add_files("asset_formats.cpp")
    set_rundir("$(projectdir)")
    add_tests("default")
target_end()

target("test-desktop")
    set_kind("binary")
    set_default(false)
    add_deps("vultra")
    add_files("desktop.cpp")
    set_rundir("$(projectdir)")
    add_tests("default")
target_end()

target("test-image")
    set_kind("binary")
    set_default(false)
    add_deps("vultra")
    add_files("image.cpp")
    set_rundir("$(projectdir)")
    add_tests("default")
target_end()

target("test-rendering")
    set_kind("binary")
    set_default(false)
    add_deps("vultra-renderer")
    add_files("rendering.cpp")
    add_includedirs("../external/openpbr", {system = true})
    set_rundir("$(projectdir)")
    add_tests("default")
target_end()

target("test-debugdraw")
    set_kind("binary")
    set_default(false)
    add_deps("vultra-renderer")
    add_files("debug_draw.cpp", "../examples/common/colored_mesh.cpp")
    set_rundir("$(projectdir)")
    add_tests("default")
target_end()

target("test-meshlets")
    set_kind("binary")
    set_default(false)
    add_deps("vultra-renderer")
    add_files("meshlets.cpp")
    set_rundir("$(projectdir)")
    add_tests("default")
target_end()

target("test-gpu")
    set_kind("binary")
    set_default(false)
    add_deps("vultra")
    add_files("gpu.cpp")
    set_rundir("$(projectdir)")
    add_tests("default")
target_end()


target("test-display")
    set_kind("binary")
    set_default(false)
    add_deps("vultra")
    add_files("display.cpp")
    set_rundir("$(projectdir)")
    add_tests("default")
target_end()


target("test-gui-settings")
    set_kind("binary")
    set_default(false)
    add_deps("vultra")
    add_files("gui_settings.cpp")
    set_rundir("$(projectdir)")
    add_tests("default")
target_end()
