// Generated by scripts/codegen.py. Do not edit.
#pragma once

namespace vultra
{
    enum class ReflectedPropertyKind
    {
        eBool,
        eFloat,
        eEnum
    };

    struct ReflectedProperty
    {
        const char*           name;
        const char*           label;
        ReflectedPropertyKind kind;
        float                 min;
        float                 max;
    };
} // namespace vultra
