// Generated by scripts/codegen.py. Do not edit.
#pragma once
#include <vultra/api/property_metadata.generated.hpp>
#include <vultra/servers/rendering/builtin/builtin_renderer.hpp>
#include <vultra/ui/editor_gui_inspector.hpp>

#include <span>

namespace vultra
{
    std::span<const ReflectedProperty> renderSettingsProperties();
    bool                               drawRenderSettings(EditorGuiInspector& inspector, RenderSettings& settings);
} // namespace vultra
