// Generated by scripts/codegen.py. Do not edit.
#pragma once
#include <vultra/servers/rendering/builtin/builtin_renderer.hpp>
#include <vultra/ui/editor_gui_inspector.hpp>

#include <span>

namespace vultra
{
    enum class ReflectedPropertyKind
    {
        eBool,
        eFloat,
        eEnum
    };

    struct ReflectedProperty
    {
        const char*           name;
        const char*           label;
        ReflectedPropertyKind kind;
        float                 min;
        float                 max;
    };

    std::span<const ReflectedProperty> renderSettingsProperties();
    bool                               drawRenderSettings(EditorGuiInspector& inspector, RenderSettings& settings);
} // namespace vultra
