// Generated by scripts/codegen.py. Do not edit.
#pragma once
#include <vultra/api/property_metadata.generated.hpp>
#include <vultra/assets/material_parameters.hpp>
#include <vultra/scene/render_nodes.hpp>
#include <vultra/ui/editor_gui_inspector.hpp>

#include <span>

namespace vultra
{
    std::span<const ReflectedProperty> cameraSettingsProperties();
    bool                               drawCameraSettings(EditorGuiInspector& inspector, CameraSettings& settings);
    std::span<const ReflectedProperty> environmentSettingsProperties();
    bool drawEnvironmentSettings(EditorGuiInspector& inspector, EnvironmentSettings& settings);
    std::span<const ReflectedProperty> lightSettingsProperties();
    bool                               drawLightSettings(EditorGuiInspector& inspector, LightSettings& settings);
    std::span<const ReflectedProperty> materialParametersProperties();
    bool drawMaterialParameters(EditorGuiInspector& inspector, MaterialParameters& settings);
} // namespace vultra
