// Generated by scripts/codegen.py. Do not edit.
#pragma once
#include <vultra/assets/material_parameters.hpp>
#include <vultra/scene/render_nodes.hpp>
#include <vultra/ui/editor_gui_inspector.hpp>

namespace vultra
{
    bool drawCameraSettings(EditorGuiInspector& inspector, CameraSettings& settings);
    bool drawEnvironmentSettings(EditorGuiInspector& inspector, EnvironmentSettings& settings);
    bool drawLightSettings(EditorGuiInspector& inspector, LightSettings& settings);
    bool drawMaterialParameters(EditorGuiInspector& inspector, MaterialParameters& settings);
} // namespace vultra
