/* Generated by scripts/codegen.py. Do not edit. */
#ifndef VULTRA_UI_GENERATED_H
#define VULTRA_UI_GENERATED_H
#include <vultra/api/vultra_abi.generated.h>
#ifdef __cplusplus
extern "C"
{
#endif
    typedef struct VultraUiFrame
    {
        void*    context; /* Borrowed; valid only during the on_gui callback. */
        uint64_t serial;
    } VultraUiFrame;

    typedef struct VultraUiApi
    {
        uint32_t version;
        uint32_t struct_size;
        VultraStatus (*button)(VultraUiFrame frame, const char* label, uint64_t labelSize, uint8_t* changed);
        VultraStatus (
            *checkbox)(VultraUiFrame frame, const char* label, uint64_t labelSize, uint8_t* value, uint8_t* changed);
        VultraStatus (*combo)(VultraUiFrame frame,
                              const char*   label,
                              uint64_t      labelSize,
                              int32_t*      value,
                              const char*   items,
                              uint64_t      itemsSize,
                              uint8_t*      changed);
        VultraStatus (*header)(VultraUiFrame frame,
                               const char*   label,
                               uint64_t      labelSize,
                               int32_t       initiallyOpen,
                               uint8_t*      changed);
        VultraStatus (*integerslider)(VultraUiFrame frame,
                                      const char*   label,
                                      uint64_t      labelSize,
                                      int32_t*      value,
                                      int32_t       minimum,
                                      int32_t       maximum,
                                      uint8_t*      changed);
        VultraStatus (*separator)(VultraUiFrame frame, const char* label, uint64_t labelSize);
        VultraStatus (*slider)(VultraUiFrame frame,
                               const char*   label,
                               uint64_t      labelSize,
                               double*       value,
                               double        minimum,
                               double        maximum,
                               uint8_t*      changed);
        VultraStatus (*text)(VultraUiFrame frame, const char* text, uint64_t textSize);
        VultraStatus (*textwrapped)(VultraUiFrame frame, const char* text, uint64_t textSize);
        VultraStatus (*tooltip)(VultraUiFrame frame, const char* text, uint64_t textSize);
    } VultraUiApi;
#ifdef __cplusplus
}
#endif
#endif
