/* Generated by scripts/codegen.py. Do not edit. */
#ifndef VULTRA_SCENE_GENERATED_H
#define VULTRA_SCENE_GENERATED_H
#include <vultra/api/vultra_abi.generated.h>
#ifdef __cplusplus
extern "C"
{
#endif
    typedef struct VultraSceneFrame
    {
        void*    context; /* Borrowed; valid only during the update callback. */
        uint64_t serial;
    } VultraSceneFrame;

    typedef struct VultraSceneTranslation
    {
        float x;
        float y;
        float z;
    } VultraSceneTranslation;

    typedef struct VultraSceneApi
    {
        uint32_t version;
        uint32_t struct_size;
        VultraStatus (*child_count)(VultraSceneFrame frame, uint64_t parent, uint64_t* value);
        VultraStatus (*child_id)(VultraSceneFrame frame, uint64_t parent, uint64_t index, uint64_t* value);
        VultraStatus (*node_name)(VultraSceneFrame frame, uint64_t node, const char** data, uint64_t* size);
        VultraStatus (*node_translation)(VultraSceneFrame frame, uint64_t node, VultraSceneTranslation* value);
        VultraStatus (*root_id)(VultraSceneFrame frame, uint64_t* value);
        VultraStatus (*set_node_translation)(VultraSceneFrame frame, uint64_t node, VultraSceneTranslation translation);
    } VultraSceneApi;
#ifdef __cplusplus
}
#endif
#endif
