/* Generated by scripts/codegen.py. Do not edit. */
#ifndef VULTRA_UI_GENERATED_H
#define VULTRA_UI_GENERATED_H
#include <vultra/api/vultra_abi.generated.h>
#ifdef __cplusplus
extern "C"
{
#endif
    typedef struct VultraUiFrame
    {
        void*    context; /* Borrowed; valid only during the on_gui callback. */
        uint64_t serial;
    } VultraUiFrame;

    typedef struct VultraUiApi
    {
        uint32_t version;
        uint32_t struct_size;
        VultraStatus (*button)(VultraUiFrame frame, const char* text, uint64_t text_size, uint8_t* changed);
        VultraStatus (*text)(VultraUiFrame frame, const char* text, uint64_t text_size);
    } VultraUiApi;
#ifdef __cplusplus
}
#endif
#endif
