/* Generated by scripts/codegen.py. Do not edit. */
#ifndef VULTRA_ABI_GENERATED_H
#define VULTRA_ABI_GENERATED_H
#include <stdint.h>
#ifdef __cplusplus
extern "C"
{
#endif
#define VULTRA_ABI_VERSION 1u

    typedef enum VultraStatus
    {
        VULTRA_STATUS_OK               = 0,
        VULTRA_STATUS_INVALID_ARGUMENT = 1,
        VULTRA_STATUS_INVALID_FRAME    = 2,
        VULTRA_STATUS_ERROR            = 3
    } VultraStatus;
#ifdef __cplusplus
}
#endif
#endif
