# Generated by scripts/codegen.py. Do not edit.
import ctypes
import math
from dataclasses import dataclass
from numbers import Real

from ._bindings_generated import VultraCameraSettings, VultraEnvironmentSettings, VultraLightSettings, VultraMaterialParameters

def _scene_id(value):
    if not isinstance(value, str) or not value or '\0' in value:
        raise ValueError("identifier must be a persistent UUID string")
    return value.encode("utf-8")

def _finite_float(value):
    if isinstance(value, bool) or not isinstance(value, Real) or not math.isfinite(float(value)):
        raise ValueError("settings require finite numeric values")
    stored = ctypes.c_float(float(value)).value
    if not math.isfinite(stored):
        raise ValueError("settings value exceeds float32")
    return stored

@dataclass(frozen=True)
class CameraSettings:
    vertical_fov: float = 1.04719755
    near_plane: float = 0.01
    far_plane: float = 100

    @classmethod
    def _from_native(cls, value):
        return cls(value.verticalFov, value.nearPlane, value.farPlane)

    def _to_native(self):
        return VultraCameraSettings(_finite_float(self.vertical_fov), _finite_float(self.near_plane), _finite_float(self.far_plane))

@dataclass(frozen=True)
class EnvironmentSettings:
    intensity: float = 1

    @classmethod
    def _from_native(cls, value):
        return cls(value.intensity)

    def _to_native(self):
        return VultraEnvironmentSettings(_finite_float(self.intensity))

@dataclass(frozen=True)
class LightSettings:
    red: float = 1
    green: float = 1
    blue: float = 1
    intensity: float = 1
    range: float = 10
    inner_cone: float = 0.35
    outer_cone: float = 0.6

    @classmethod
    def _from_native(cls, value):
        return cls(value.red, value.green, value.blue, value.intensity, value.range, value.innerCone, value.outerCone)

    def _to_native(self):
        return VultraLightSettings(_finite_float(self.red), _finite_float(self.green), _finite_float(self.blue), _finite_float(self.intensity), _finite_float(self.range), _finite_float(self.inner_cone), _finite_float(self.outer_cone))

@dataclass(frozen=True)
class MaterialParameters:
    base_red: float = 1
    base_green: float = 1
    base_blue: float = 1
    base_alpha: float = 1
    base_weight: float = 1
    base_metalness: float = 0
    base_diffuse_roughness: float = 0
    specular_weight: float = 1
    specular_red: float = 1
    specular_green: float = 1
    specular_blue: float = 1
    specular_roughness: float = 0.3
    specular_ior: float = 1.5
    coat_weight: float = 0
    coat_roughness: float = 0.1
    coat_ior: float = 1.5
    emission_red: float = 0
    emission_green: float = 0
    emission_blue: float = 0
    emission_luminance: float = 1
    normal_scale: float = 1
    occlusion_strength: float = 1
    alpha_cutoff: float = -1

    @classmethod
    def _from_native(cls, value):
        return cls(value.baseRed, value.baseGreen, value.baseBlue, value.baseAlpha, value.baseWeight, value.baseMetalness, value.baseDiffuseRoughness, value.specularWeight, value.specularRed, value.specularGreen, value.specularBlue, value.specularRoughness, value.specularIor, value.coatWeight, value.coatRoughness, value.coatIor, value.emissionRed, value.emissionGreen, value.emissionBlue, value.emissionLuminance, value.normalScale, value.occlusionStrength, value.alphaCutoff)

    def _to_native(self):
        return VultraMaterialParameters(_finite_float(self.base_red), _finite_float(self.base_green), _finite_float(self.base_blue), _finite_float(self.base_alpha), _finite_float(self.base_weight), _finite_float(self.base_metalness), _finite_float(self.base_diffuse_roughness), _finite_float(self.specular_weight), _finite_float(self.specular_red), _finite_float(self.specular_green), _finite_float(self.specular_blue), _finite_float(self.specular_roughness), _finite_float(self.specular_ior), _finite_float(self.coat_weight), _finite_float(self.coat_roughness), _finite_float(self.coat_ior), _finite_float(self.emission_red), _finite_float(self.emission_green), _finite_float(self.emission_blue), _finite_float(self.emission_luminance), _finite_float(self.normal_scale), _finite_float(self.occlusion_strength), _finite_float(self.alpha_cutoff))

class ExperimentSceneControls:
    def camera_settings(self, identifier: str) -> CameraSettings:
        self._check()
        text = _scene_id(identifier)
        value = VultraCameraSettings()
        self._host._status(self._host._api.camera_settings(
            self._host._native.context, self._id, text, len(text), ctypes.byref(value)))
        return CameraSettings._from_native(value)

    def environment_settings(self, identifier: str) -> EnvironmentSettings:
        self._check()
        text = _scene_id(identifier)
        value = VultraEnvironmentSettings()
        self._host._status(self._host._api.environment_settings(
            self._host._native.context, self._id, text, len(text), ctypes.byref(value)))
        return EnvironmentSettings._from_native(value)

    def light_settings(self, identifier: str) -> LightSettings:
        self._check()
        text = _scene_id(identifier)
        value = VultraLightSettings()
        self._host._status(self._host._api.light_settings(
            self._host._native.context, self._id, text, len(text), ctypes.byref(value)))
        return LightSettings._from_native(value)

    def material_parameters(self, identifier: str) -> MaterialParameters:
        self._check()
        text = _scene_id(identifier)
        value = VultraMaterialParameters()
        self._host._status(self._host._api.material_parameters(
            self._host._native.context, self._id, text, len(text), ctypes.byref(value)))
        return MaterialParameters._from_native(value)

    def set_camera_settings(self, identifier: str, value: CameraSettings) -> None:
        self._check()
        text = _scene_id(identifier)
        if type(value) is not CameraSettings:
            raise TypeError('value must be CameraSettings')
        self._host._status(self._host._api.set_camera_settings(
            self._host._native.context, self._id, text, len(text), value._to_native()))

    def set_environment_settings(self, identifier: str, value: EnvironmentSettings) -> None:
        self._check()
        text = _scene_id(identifier)
        if type(value) is not EnvironmentSettings:
            raise TypeError('value must be EnvironmentSettings')
        self._host._status(self._host._api.set_environment_settings(
            self._host._native.context, self._id, text, len(text), value._to_native()))

    def set_light_settings(self, identifier: str, value: LightSettings) -> None:
        self._check()
        text = _scene_id(identifier)
        if type(value) is not LightSettings:
            raise TypeError('value must be LightSettings')
        self._host._status(self._host._api.set_light_settings(
            self._host._native.context, self._id, text, len(text), value._to_native()))

    def set_material_parameters(self, identifier: str, value: MaterialParameters) -> None:
        self._check()
        text = _scene_id(identifier)
        if type(value) is not MaterialParameters:
            raise TypeError('value must be MaterialParameters')
        self._host._status(self._host._api.set_material_parameters(
            self._host._native.context, self._id, text, len(text), value._to_native()))
