#include "editor_app/runtime_mcp_tool_registry.hpp"

#include <nlohmann/json.hpp>

namespace vultra_app::runtime_mcp
{
    nlohmann::json toolsList()
    {
        const auto emptyObject = nlohmann::json {{"type", "object"}};
        return {
            {"tools",
             nlohmann::json::array({
                 {{"name", "vultra.runtime.status"},
                  {"description", "Inspect the live Vultra editor/runtime state."},
                  {"inputSchema", emptyObject}},
                 {{"name", "vultra.sim.reset"},
                  {"description", "Reset the live simulation world and optionally load a scene URI."},
                  {"inputSchema",
                   {{"type", "object"},
                    {"properties",
                     {{"scene", {{"type", "string"}}},
                      {"seed", {{"type", "integer"}}},
                      {"play", {{"type", "boolean"}}}}}}}},
                 {{"name", "vultra.sim.step"},
                  {"description", "Advance the live simulation by a small batch of engine frames and return state summary."},
                  {"inputSchema",
                   {{"type", "object"},
                    {"properties",
                     {{"frames", {{"type", "integer"}}},
                      {"actions", {{"type", "array"}}},
                      {"includeState", {{"type", "boolean"}}}}}}}},
                 {{"name", "vultra.sim.get_state_batch"},
                  {"description", "Read transform, status, and rigid-body state for a batch of entities."},
                  {"inputSchema",
                   {{"type", "object"},
                    {"properties",
                     {{"entities", {{"type", "array"}}},
                      {"limit", {{"type", "integer"}}},
                      {"includeInactive", {{"type", "boolean"}}},
                      {"includeVelocity", {{"type", "boolean"}}}}}}}},
                 {{"name", "vultra.sim.set_state_batch"},
                  {"description", "Write transform, velocity, and active/visible state for a batch of entities."},
                  {"inputSchema",
                   {{"type", "object"},
                    {"properties", {{"states", {{"type", "array"}}}}},
                    {"required", {"states"}}}}},
                 {{"name", "vultra.sim.apply_actions_batch"},
                  {"description", "Apply batched AI actions: force, impulse, target_velocity, or teleport."},
                  {"inputSchema",
                   {{"type", "object"},
                    {"properties", {{"actions", {{"type", "array"}}}}},
                    {"required", {"actions"}}}}},
                 {{"name", "vultra.sim.raycast"},
                  {"description",
                   "Cast a ray through the physics world (real Jolt geometry). Returns the closest hit "
                   "(entity, point, normal, distance) or all hits when all=true. layerMask scopes layers."},
                  {"inputSchema",
                   {{"type", "object"},
                    {"properties",
                     {{"origin", {{"type", "array"}}},
                      {"direction", {{"type", "array"}}},
                      {"maxDistance", {{"type", "number"}}},
                      {"layerMask", {{"type", "integer"}}},
                      {"activeOnly", {{"type", "boolean"}}},
                      {"all", {{"type", "boolean"}}}}},
                    {"required", {"origin", "direction"}}}}},
                 {{"name", "vultra.sim.overlap"},
                  {"description",
                   "Find entities overlapping a sphere/box/capsule shape (real Jolt geometry). "
                   "shape=sphere|box|capsule; layerMask scopes layers."},
                  {"inputSchema",
                   {{"type", "object"},
                    {"properties",
                     {{"shape", {{"type", "string"}}},
                      {"center", {{"type", "array"}}},
                      {"radius", {{"type", "number"}}},
                      {"halfHeight", {{"type", "number"}}},
                      {"halfExtents", {{"type", "array"}}},
                      {"layerMask", {{"type", "integer"}}},
                      {"activeOnly", {{"type", "boolean"}}}}},
                    {"required", {"center"}}}}},
                 {{"name", "vultra.sim.contact_events"},
                  {"description",
                   "Drain physics contact/trigger events since last call: each {type:enter|exit, a, b, "
                   "isSensor}. Enter/exit on a sensor body are trigger enter/exit."},
                  {"inputSchema", {{"type", "object"}, {"properties", nlohmann::json::object()}}}},
                 {{"name", "vultra.animator.set_param"},
                  {"description",
                   "Set an animator-graph parameter on an entity's AnimatorComponent (graph mode). "
                   "type=float|bool|trigger (default float); float/bool use `value`."},
                  {"inputSchema",
                   {{"type", "object"},
                    {"properties",
                     {{"entity", {{"type", "integer"}}},
                      {"name", {{"type", "string"}}},
                      {"type", {{"type", "string"}}},
                      {"value", {{"type", "number"}}}}},
                    {"required", {"entity", "name"}}}}},
                 {{"name", "vultra.animator.state"},
                  {"description",
                   "Read the animator-graph state-machine status (current/next state, transition "
                   "progress, normalized time) for an entity."},
                  {"inputSchema",
                   {{"type", "object"},
                    {"properties", {{"entity", {{"type", "integer"}}}}},
                    {"required", {"entity"}}}}},
                 {{"name", "vultra.render.capture_rgb"},
                  {"description", "Capture the current rendered RGB output to a PNG file."},
                  {"inputSchema",
                   {{"type", "object"},
                    {"properties",
                     {{"outputFile", {{"type", "string"}}},
                      {"camera", {{"type", "string"}}},
                      {"width", {{"type", "integer"}}},
                      {"height", {{"type", "integer"}}}}}}}},
                 {{"name", "vultra.render.capture_depth"},
                  {"description", "Capture depth-like frame resources when rendering is enabled."},
                  {"inputSchema",
                   {{"type", "object"},
                    {"properties",
                     {{"outputDirectory", {{"type", "string"}}},
                      {"camera", {{"type", "string"}}},
                      {"maxTextures", {{"type", "integer"}}}}}}}},
                 {{"name", "vultra.render.stream"},
                  {"description", "Start, stop, or inspect an HTTP MJPEG stream of the rendered output."},
                  {"inputSchema",
                   {{"type", "object"},
                    {"properties",
                     {{"action", {{"type", "string"}, {"enum", {"start", "stop", "status"}}}},
                      {"fps", {{"type", "integer"}, {"description", "0 or omitted streams every available engine frame; positive values cap stream FPS."}}},
                      {"jpegQuality", {{"type", "integer"}}},
                      {"maxWidth", {{"type", "integer"}, {"description", "0 or omitted means no width cap; output aspect ratio is preserved."}}},
                      {"maxHeight", {{"type", "integer"}, {"description", "0 or omitted means no height cap; output aspect ratio is preserved."}}}}},
                    {"required", {"action"}}}}},
                 {{"name", "vultra.project.info"},
                  {"description", "Inspect the currently opened Vultra project."},
                  {"inputSchema", emptyObject}},
                 {{"name", "vultra.editor.command"},
                  {"description", "Execute an editor command through the shared UI/MCP command model."},
                  {"inputSchema",
                   {{"type", "object"},
                    {"properties",
                     {{"name", {{"type", "string"}}}, {"arguments", {{"type", "object"}}}}},
                    {"required", {"name"}}}}},
                 {{"name", "vultra.editor.command_batch"},
                  {"description", "Execute multiple editor commands while preserving per-command history boundaries."},
                  {"inputSchema",
                   {{"type", "object"},
                    {"properties",
                     {{"commands", {{"type", "array"}}}, {"stopOnError", {{"type", "boolean"}}}}},
                    {"required", {"commands"}}}}},
                 {{"name", "vultra.editor.back_to_launcher"},
                  {"description", "Return the editor shell to the project launcher."},
                  {"inputSchema", emptyObject}},
                 {{"name", "vultra.editor.window"},
                 {"description", "Inspect or control the editor window: status, focus, fullscreen, resize, move, maximize, minimize, restore, close."},
                 {"inputSchema",
                  {{"type", "object"},
                    {"properties",
                     {{"action",
                       {{"type", "string"},
                        {"enum",
                         {"status",
                          "focus",
                          "fullscreen",
                          "resize",
                          "move",
                          "center",
                          "maximize",
                          "minimize",
                          "restore",
                          "decorated",
                          "resizable",
                          "visible",
                          "close"}}}},
                      {"enabled", {{"type", "boolean"}}},
                      {"width", {{"type", "integer"}}},
                      {"height", {{"type", "integer"}}},
                      {"x", {{"type", "integer"}}},
                      {"y", {{"type", "integer"}}},
                      {"target", {{"type", "string"}}}}}}}},
                 {{"name", "vultra.editor.scene_view"},
                  {"description", "Inspect or control Scene View editor-only settings such as 2D/3D view mode and active transform tool."},
                  {"inputSchema",
                   {{"type", "object"},
                    {"properties",
                     {{"mode", {{"type", "string"}, {"enum", {"2d", "3d", "ui2d", "view3d"}}}},
                      {"tool", {{"type", "string"}, {"enum", {"select", "move", "rotate", "scale", "rect", "transform"}}}}}}}}},
                 {{"name", "vultra.project.create_empty"},
                 {"description", "Create and open an empty Vultra project."},
                  {"inputSchema",
                   {{"type", "object"},
                    {"properties",
                     {{"projectDir", {{"type", "string"}}},
                      {"name", {{"type", "string"}}},
                      {"template", {{"type", "string"}, {"enum", {"empty", "minimal"}}}},
                      {"allowCreate", {{"type", "boolean"}}}}},
                    {"required", {"projectDir", "allowCreate"}}}}},
                 {{"name", "vultra.scene.new"},
                  {"description", "Create a new scene workspace in the current project."},
                  {"inputSchema",
                   {{"type", "object"},
                    {"properties",
                     {{"uri", {{"type", "string"}}}, {"withDefaults", {{"type", "boolean"}}}}}}}},
                 {{"name", "vultra.scene.list_entity_kinds"},
                  {"description", "List entity templates available to scene.add_entity."},
                  {"inputSchema", emptyObject}},
                 {{"name", "vultra.scene.list_component_kinds"},
                  {"description", "List component kinds available to scene component commands."},
                  {"inputSchema", emptyObject}},
                 {{"name", "vultra.scene.component_metadata"},
                  {"description",
                   "Return component field metadata for scene component tools. Pass component_kind for one kind, or omit it for all kinds."},
                  {"inputSchema",
                   {{"type", "object"},
                    // Canonical key is snake_case component_kind, matching every other scene
                    // component tool. The command still tolerates componentKind/kind aliases, but
                    // the published schema advertises only the canonical form.
                    {"properties", {{"component_kind", {{"type", "string"}}}}}}}},
                 {{"name", "vultra.scene.get_component"},
                  {"description", "Read an entity component as update_component-compatible JSON."},
                  {"inputSchema",
                   {{"type", "object"},
                    {"properties", {{"entity", {}}, {"component_kind", {{"type", "string"}}}}},
                    {"required", {"entity", "component_kind"}}}}},
                 {{"name", "vultra.scene.add_entity"},
                  {"description", "Create an entity from an entity_kind template."},
                  {"inputSchema",
                   {{"type", "object"},
                    {"properties",
                     {{"entity_kind", {{"type", "string"}}},
                      {"primitive", {{"type", "string"}}},
                      {"light_kind", {{"type", "string"}}},
                      {"parent", {}},
                      {"name", {{"type", "string"}}},
                      {"position", {{"type", "array"}}},
                      {"rotation", {}},
                      {"scale", {{"type", "array"}}}}}}}},
                 {{"name", "vultra.scene.remove_entity"},
                  {"description", "Remove an entity and its children."},
                  {"inputSchema",
                   {{"type", "object"}, {"properties", {{"entity", {}}}}, {"required", {"entity"}}}}},
                 {{"name", "vultra.scene.add_component"},
                  {"description", "Add a component to an entity."},
                  {"inputSchema",
                   {{"type", "object"},
                    {"properties", {{"entity", {}}, {"component_kind", {{"type", "string"}}}, {"properties", {{"type", "object"}}}}},
                    {"required", {"entity", "component_kind"}}}}},
                 {{"name", "vultra.scene.update_component"},
                  {"description", "Update an existing component on an entity."},
                  {"inputSchema",
                   {{"type", "object"},
                    {"properties", {{"entity", {}}, {"component_kind", {{"type", "string"}}}, {"properties", {{"type", "object"}}}}},
                    {"required", {"entity", "component_kind"}}}}},
                 {{"name", "vultra.scene.remove_component"},
                  {"description", "Remove an optional component from an entity."},
                  {"inputSchema",
                   {{"type", "object"},
                    {"properties", {{"entity", {}}, {"component_kind", {{"type", "string"}}}}},
                    {"required", {"entity", "component_kind"}}}}},
                 {{"name", "vultra.scene.select_entity"},
                  {"description", "Select or clear an entity selection."},
                  {"inputSchema",
                   {{"type", "object"}, {"properties", {{"entity", {}}, {"clear", {{"type", "boolean"}}}}}}}},
                 {{"name", "vultra.scene.move_entity"},
                  {"description", "Move an entity to root, under a parent, or before/after a sibling."},
                  {"inputSchema",
                   {{"type", "object"},
                    {"properties",
                     {{"entity", {}},
                      {"mode", {{"type", "string"}, {"enum", {"root", "parent", "before", "after"}}}},
                      {"parent", {}},
                      {"sibling", {}}}},
                    {"required", {"entity", "mode"}}}}},
                 {{"name", "vultra.scene.instantiate_asset"},
                  {"description", "Instantiate a registered asset into the scene using the same path as Content Browser drag-and-drop."},
                  {"inputSchema",
                   {{"type", "object"},
                    {"properties",
                     {{"asset", {{"type", "string"}}},
                      {"assetUuid", {{"type", "string"}}},
                      {"uri", {{"type", "string"}}},
                      {"parent", {}},
                      {"beforeSibling", {}},
                      {"afterSibling", {}},
                      {"name", {{"type", "string"}}},
                      {"position", {{"type", "array"}}},
                      {"rotation", {}},
                      {"scale", {{"type", "array"}}},
                      {"keepPosition", {{"type", "boolean"}}},
                      {"keepRotation", {{"type", "boolean"}}},
                      {"keepScale", {{"type", "boolean"}}}}}}}},
                 {{"name", "vultra.scene.save"},
                  {"description", "Save the current world as the current or specified scene asset."},
                  {"inputSchema",
                   {{"type", "object"}, {"properties", {{"uri", {{"type", "string"}}}}}}}},
                 {{"name", "vultra.assets.list"},
                  {"description", "List assets from the live asset registry."},
                  {"inputSchema",
                   {{"type", "object"},
                    {"properties",
                     {{"type", {{"type", "string"}}},
                      {"query", {{"type", "string"}}},
                      {"limit", {{"type", "integer"}}}}}}}},
                 {{"name", "vultra.assets.read"},
                  {"description", "Read a text asset from the current project or asset service."},
                  {"inputSchema",
                   {{"type", "object"}, {"properties", {{"uri", {{"type", "string"}}}}}, {"required", {"uri"}}}}},
                 {{"name", "vultra.assets.write"},
                  {"description", "Write a text asset under the current project asset root."},
                  {"inputSchema",
                   {{"type", "object"},
                    {"properties",
                     {{"uri", {{"type", "string"}}},
                      {"text", {{"type", "string"}}},
                      {"allowWrite", {{"type", "boolean"}}},
                      {"reimport", {{"type", "boolean"}}}}},
                    {"required", {"uri", "text", "allowWrite"}}}}},
                 {{"name", "vultra.material_graph.list_nodes"},
                  {"description", "List project-defined Material Graph custom node descriptors from .vmatnode.json assets."},
                  {"inputSchema", emptyObject}},
                 {{"name", "vultra.material_graph.compile"},
                  {"description", "Compile a project .vmatgraph.json with project-defined .vmatnode.json descriptors."},
                  {"inputSchema",
                   {{"type", "object"},
                    {"properties",
                     {{"uri", {{"type", "string"}}},
                      {"graph", {{"type", "string"}}},
                      {"includeSource", {{"type", "boolean"}}}}},
                    {"required", {"uri"}}}}},
                 {{"name", "vultra.assets.import"},
                  {"description", "Import or reimport one asset already under the current project asset root."},
                  {"inputSchema",
                   {{"type", "object"},
                    {"properties",
                     {{"uri", {{"type", "string"}}},
                      {"path", {{"type", "string"}}},
                      {"force", {{"type", "boolean"}}}}}}}},
                 {{"name", "vultra.assets.import_from_web"},
                  {"description", "Download an HTTP/HTTPS asset into the current project asset root and optionally import it."},
                  {"inputSchema",
                   {{"type", "object"},
                    {"properties",
                     {{"url", {{"type", "string"}}},
                      {"targetUri", {{"type", "string"}}},
                      {"targetDirectory", {{"type", "string"}}},
                      {"allowOverwrite", {{"type", "boolean"}}},
                      {"reimport", {{"type", "boolean"}}},
                      {"force", {{"type", "boolean"}}},
                      {"maxBytes", {{"type", "integer"}}},
                      {"timeoutSeconds", {{"type", "integer"}}}}},
                    {"required", {"url"}}}}},
                 {{"name", "vultra.assets.import_package"},
                  {"description", "Import a .vultrapackage into the current project asset root."},
                  {"inputSchema",
                   {{"type", "object"}, {"properties", {{"path", {{"type", "string"}}}}}, {"required", {"path"}}}}},
                 {{"name", "vultra.editor.capture"},
                  {"description", "Capture the current editor backbuffer to a PNG file."},
                  {"inputSchema",
                   {{"type", "object"}, {"properties", {{"outputFile", {{"type", "string"}}}}}}}},
                 {{"name", "vultra.editor.recording"},
                  {"description", "Record the editor backbuffer to a frame sequence and optionally encode a video."},
                  {"inputSchema",
                   {{"type", "object"},
                    {"properties",
                     {{"action", {{"type", "string"}, {"enum", {"start", "stop", "status"}}}},
                      {"outputFile", {{"type", "string"}}},
                      {"frameDirectory", {{"type", "string"}}},
                      {"mode", {{"type", "string"}, {"enum", {"stream", "frames"}}}},
                      {"fps", {{"type", "integer"}}},
                      {"maxFrames", {{"type", "integer"}}},
                      {"maxQueuedFrames", {{"type", "integer"}}},
                      {"encodeOnStop", {{"type", "boolean"}}}}},
                    {"required", {"action"}}}}},
                 {{"name", "vultra.editor.input"},
                  {"description", "Inject basic ImGui mouse/keyboard/text input for editor UI automation."},
                  {"inputSchema", {{"type", "object"}}}},
                 {{"name", "vultra.editor.quit"},
                  {"description", "Request the editor window to close."},
                  {"inputSchema", emptyObject}},
                 {{"name", "vultra.runtime.playback"},
                  {"description", "Control editor playback: play, pause, resume, stop, or step."},
                  {"inputSchema",
                   {{"type", "object"},
                    {"properties",
                     {{"action", {{"type", "string"}, {"enum", {"play", "pause", "resume", "stop", "step"}}}}}},
                    {"required", {"action"}}}}},
                 {{"name", "vultra.runtime.profiler"},
                  {"description", "Read the latest RuntimeProfiler frame stats."},
                  {"inputSchema", emptyObject}},
                 {{"name", "vultra.runtime.framegraph_snapshot"},
                  {"description", "Enable frame graph snapshot capture and return the latest snapshot text."},
                  {"inputSchema", emptyObject}},
                 {{"name", "vultra.runtime.frame_resources"},
                  {"description", "Inspect frame graph debug texture/resource metadata."},
                  {"inputSchema", emptyObject}},
                 {{"name", "vultra.runtime.scene_context"},
                  {"description", "Inspect the open scene, main camera, and its renderer render graph."},
                  {"inputSchema",
                   {{"type", "object"}, {"properties", {{"includeRenderGraphSource", {{"type", "boolean"}}}}}}}},
                 {{"name", "vultra.runtime.rendergraph_source"},
                  {"description", "Read the render graph source for a renderer key or graph URI."},
                  {"inputSchema",
                   {{"type", "object"},
                    {"properties",
                     {{"rendererKey", {{"type", "string"}}},
                      {"uri", {{"type", "string"}}},
                      {"includeSource", {{"type", "boolean"}}}}}}}},
                 {{"name", "vultra.runtime.dump_frame_textures"},
                  {"description", "Dump captured frame debug textures to PNG files."},
                  {"inputSchema",
                   {{"type", "object"},
                    {"properties",
                     {{"outputDirectory", {{"type", "string"}}},
                      {"filter", {{"type", "string"}}},
                      {"camera", {{"type", "string"}}},
                      {"renderer", {{"type", "string"}}},
                      {"maxTextures", {{"type", "integer"}}},
                      {"captureFrames", {{"type", "integer"}}},
                      {"maxPreviewExtent", {{"type", "integer"}, {"description", "0 dumps full preview resolution"}}}}}}}},
                 {{"name", "vultra.runtime.reload_pipeline"},
                  {"description", "Reload the current or specified render graph pipeline."},
                  {"inputSchema",
                   {{"type", "object"},
                    {"properties",
                     {{"asset", {{"type", "string"}}}, {"rendererKey", {{"type", "string"}}}}}}}},
                 {{"name", "vultra.runtime.capture_frame"},
                  {"description", "Request a RenderDoc frame capture when available."},
                  {"inputSchema", emptyObject}},
             })},
        };
    }
} // namespace vultra_app::runtime_mcp
