// Generated by scripts/codegen.py. Do not edit.
using System.Runtime.InteropServices;

namespace Vultra.Interop;

internal static class VultraAbi
{
    public const uint Version = 3;
}

internal enum VultraStatus : int
{
    Ok = 0,
    InvalidArgument = 1,
    InvalidFrame = 2,
    Error = 3
}

[StructLayout(LayoutKind.Sequential)]
internal unsafe struct VultraUiFrame
{
    public void* Context;
    public ulong Serial;
}

[StructLayout(LayoutKind.Sequential)]
internal unsafe struct VultraSceneFrame
{
    public void* Context;
    public ulong Serial;
}

[StructLayout(LayoutKind.Sequential)]
internal unsafe struct VultraUiApi
{
    public uint Version;
    public uint StructSize;
    public delegate* unmanaged[Cdecl]<VultraUiFrame, byte*, ulong, byte*, VultraStatus> Button;
    public delegate* unmanaged[Cdecl]<VultraUiFrame, byte*, ulong, VultraStatus> Text;
}

[StructLayout(LayoutKind.Sequential)]
internal struct VultraSceneTranslation
{
    public float X;
    public float Y;
    public float Z;
}

[StructLayout(LayoutKind.Sequential)]
internal unsafe struct VultraSceneApi
{
    public uint Version;
    public uint StructSize;
    public delegate* unmanaged[Cdecl]<VultraSceneFrame, ulong, ulong*, VultraStatus> ChildCount;
    public delegate* unmanaged[Cdecl]<VultraSceneFrame, ulong, ulong, ulong*, VultraStatus> ChildId;
    public delegate* unmanaged[Cdecl]<VultraSceneFrame, ulong, byte**, ulong*, VultraStatus> NodeName;
    public delegate* unmanaged[Cdecl]<VultraSceneFrame, ulong, VultraSceneTranslation*, VultraStatus> NodeTranslation;
    public delegate* unmanaged[Cdecl]<VultraSceneFrame, ulong*, VultraStatus> RootId;
    public delegate* unmanaged[Cdecl]<VultraSceneFrame, ulong, VultraSceneTranslation, VultraStatus> SetNodeTranslation;
}

[StructLayout(LayoutKind.Sequential)]
internal unsafe struct VultraScriptRegistrationApi
{
    public uint Version;
    public uint StructSize;
    public void* UserData;
    public delegate* unmanaged[Cdecl]<void*, byte*, ulong, VultraStatus> RegisterClass;
}

[StructLayout(LayoutKind.Sequential)]
internal unsafe struct VultraHostApi
{
    public uint Version;
    public uint StructSize;
    public VultraUiApi* Ui;
    public VultraSceneApi* Scene;
    public VultraScriptRegistrationApi* Scripts;
}

[StructLayout(LayoutKind.Sequential)]
internal unsafe struct VultraPluginApi
{
    public uint Version;
    public uint StructSize;
    public void* UserData;
    public delegate* unmanaged[Cdecl]<void*, VultraSceneFrame, float, VultraStatus> Update;
    public delegate* unmanaged[Cdecl]<void*, VultraUiFrame, VultraStatus> OnGui;
    public delegate* unmanaged[Cdecl]<void*, VultraStatus> Stop;
}
