// Generated by scripts/codegen.py. Do not edit.
using System.Numerics;
using Vultra.Interop;

namespace Vultra.Scripting;

public readonly record struct CameraSettings
{
    public float VerticalFov { get; init; } = 1.04719755f;
    public float NearPlane { get; init; } = 0.01f;
    public float FarPlane { get; init; } = 100f;

    public CameraSettings() { }

    public CameraSettings(float verticalFov, float nearPlane, float farPlane)
    {
        VerticalFov = verticalFov;
        NearPlane = nearPlane;
        FarPlane = farPlane;
    }

    internal static CameraSettings FromAbi(VultraCameraSettings value) => new()
    {
        VerticalFov = value.VerticalFov,
        NearPlane = value.NearPlane,
        FarPlane = value.FarPlane,
    };

    internal VultraCameraSettings ToAbi() => new()
    {
        VerticalFov = VerticalFov,
        NearPlane = NearPlane,
        FarPlane = FarPlane,
    };
}

public readonly record struct EnvironmentSettings
{
    public float Intensity { get; init; } = 1f;

    public EnvironmentSettings() { }

    public EnvironmentSettings(float intensity)
    {
        Intensity = intensity;
    }

    internal static EnvironmentSettings FromAbi(VultraEnvironmentSettings value) => new()
    {
        Intensity = value.Intensity,
    };

    internal VultraEnvironmentSettings ToAbi() => new()
    {
        Intensity = Intensity,
    };
}

public readonly record struct LightSettings
{
    public Vector3 Color { get; init; } = new(1f, 1f, 1f);
    public float Intensity { get; init; } = 1f;
    public float Range { get; init; } = 10f;
    public float InnerCone { get; init; } = 0.35f;
    public float OuterCone { get; init; } = 0.6f;

    public LightSettings() { }

    public LightSettings(Vector3 color, float intensity, float range, float innerCone, float outerCone)
    {
        Color = color;
        Intensity = intensity;
        Range = range;
        InnerCone = innerCone;
        OuterCone = outerCone;
    }

    internal static LightSettings FromAbi(VultraLightSettings value) => new()
    {
        Color = new Vector3(value.Red, value.Green, value.Blue),
        Intensity = value.Intensity,
        Range = value.Range,
        InnerCone = value.InnerCone,
        OuterCone = value.OuterCone,
    };

    internal VultraLightSettings ToAbi() => new()
    {
        Red = Color.X,
        Green = Color.Y,
        Blue = Color.Z,
        Intensity = Intensity,
        Range = Range,
        InnerCone = InnerCone,
        OuterCone = OuterCone,
    };
}

public readonly record struct MaterialParameters
{
    public Vector4 BaseColor { get; init; } = new(1f, 1f, 1f, 1f);
    public float BaseWeight { get; init; } = 1f;
    public float Metalness { get; init; } = 0f;
    public float DiffuseRoughness { get; init; } = 0f;
    public float SpecularWeight { get; init; } = 1f;
    public Vector3 SpecularColor { get; init; } = new(1f, 1f, 1f);
    public float Roughness { get; init; } = 0.3f;
    public float SpecularIor { get; init; } = 1.5f;
    public float CoatWeight { get; init; } = 0f;
    public float CoatRoughness { get; init; } = 0.1f;
    public float CoatIor { get; init; } = 1.5f;
    public Vector3 EmissionColor { get; init; } = new(0f, 0f, 0f);
    public float EmissionLuminance { get; init; } = 1f;
    public float NormalScale { get; init; } = 1f;
    public float OcclusionStrength { get; init; } = 1f;
    public float AlphaCutoff { get; init; } = -1f;

    public MaterialParameters() { }

    public MaterialParameters(Vector4 baseColor, float baseWeight, float metalness, float diffuseRoughness, float specularWeight, Vector3 specularColor, float roughness, float specularIor, float coatWeight, float coatRoughness, float coatIor, Vector3 emissionColor, float emissionLuminance, float normalScale, float occlusionStrength, float alphaCutoff)
    {
        BaseColor = baseColor;
        BaseWeight = baseWeight;
        Metalness = metalness;
        DiffuseRoughness = diffuseRoughness;
        SpecularWeight = specularWeight;
        SpecularColor = specularColor;
        Roughness = roughness;
        SpecularIor = specularIor;
        CoatWeight = coatWeight;
        CoatRoughness = coatRoughness;
        CoatIor = coatIor;
        EmissionColor = emissionColor;
        EmissionLuminance = emissionLuminance;
        NormalScale = normalScale;
        OcclusionStrength = occlusionStrength;
        AlphaCutoff = alphaCutoff;
    }

    internal static MaterialParameters FromAbi(VultraMaterialParameters value) => new()
    {
        BaseColor = new Vector4(value.BaseRed, value.BaseGreen, value.BaseBlue, value.BaseAlpha),
        BaseWeight = value.BaseWeight,
        Metalness = value.BaseMetalness,
        DiffuseRoughness = value.BaseDiffuseRoughness,
        SpecularWeight = value.SpecularWeight,
        SpecularColor = new Vector3(value.SpecularRed, value.SpecularGreen, value.SpecularBlue),
        Roughness = value.SpecularRoughness,
        SpecularIor = value.SpecularIor,
        CoatWeight = value.CoatWeight,
        CoatRoughness = value.CoatRoughness,
        CoatIor = value.CoatIor,
        EmissionColor = new Vector3(value.EmissionRed, value.EmissionGreen, value.EmissionBlue),
        EmissionLuminance = value.EmissionLuminance,
        NormalScale = value.NormalScale,
        OcclusionStrength = value.OcclusionStrength,
        AlphaCutoff = value.AlphaCutoff,
    };

    internal VultraMaterialParameters ToAbi() => new()
    {
        BaseRed = BaseColor.X,
        BaseGreen = BaseColor.Y,
        BaseBlue = BaseColor.Z,
        BaseAlpha = BaseColor.W,
        BaseWeight = BaseWeight,
        BaseMetalness = Metalness,
        BaseDiffuseRoughness = DiffuseRoughness,
        SpecularWeight = SpecularWeight,
        SpecularRed = SpecularColor.X,
        SpecularGreen = SpecularColor.Y,
        SpecularBlue = SpecularColor.Z,
        SpecularRoughness = Roughness,
        SpecularIor = SpecularIor,
        CoatWeight = CoatWeight,
        CoatRoughness = CoatRoughness,
        CoatIor = CoatIor,
        EmissionRed = EmissionColor.X,
        EmissionGreen = EmissionColor.Y,
        EmissionBlue = EmissionColor.Z,
        EmissionLuminance = EmissionLuminance,
        NormalScale = NormalScale,
        OcclusionStrength = OcclusionStrength,
        AlphaCutoff = AlphaCutoff,
    };
}
