// Generated by scripts/codegen.py. Do not edit.
using System.Runtime.InteropServices;

namespace Vultra.Interop;

internal static class VultraAbi
{
    public const uint Version = 1;
}

internal enum VultraStatus : int
{
    Ok = 0,
    InvalidArgument = 1,
    InvalidFrame = 2,
    Error = 3
}

[StructLayout(LayoutKind.Sequential)]
internal unsafe struct VultraUiFrame
{
    public void* Context;
    public ulong Serial;
}

[StructLayout(LayoutKind.Sequential)]
internal unsafe struct VultraSceneFrame
{
    public void* Context;
    public ulong Serial;
}

[StructLayout(LayoutKind.Sequential)]
internal unsafe struct VultraUiApi
{
    public uint Version;
    public uint StructSize;
    public delegate* unmanaged[Cdecl]<VultraUiFrame, byte*, ulong, byte*, VultraStatus> Button;
    public delegate* unmanaged[Cdecl]<VultraUiFrame, byte*, ulong, byte*, byte*, VultraStatus> Checkbox;
    public delegate* unmanaged[Cdecl]<VultraUiFrame, byte*, ulong, int*, byte*, ulong, byte*, VultraStatus> Combo;
    public delegate* unmanaged[Cdecl]<VultraUiFrame, byte*, ulong, int, byte*, VultraStatus> Header;
    public delegate* unmanaged[Cdecl]<VultraUiFrame, byte*, ulong, int*, int, int, byte*, VultraStatus> IntegerSlider;
    public delegate* unmanaged[Cdecl]<VultraUiFrame, byte*, ulong, VultraStatus> Separator;
    public delegate* unmanaged[Cdecl]<VultraUiFrame, byte*, ulong, double*, double, double, byte*, VultraStatus> Slider;
    public delegate* unmanaged[Cdecl]<VultraUiFrame, byte*, ulong, VultraStatus> Text;
    public delegate* unmanaged[Cdecl]<VultraUiFrame, byte*, ulong, VultraStatus> TextWrapped;
    public delegate* unmanaged[Cdecl]<VultraUiFrame, byte*, ulong, VultraStatus> Tooltip;
}

[StructLayout(LayoutKind.Sequential)]
internal struct VultraCameraSettings
{
    public float VerticalFov;
    public float NearPlane;
    public float FarPlane;
}

[StructLayout(LayoutKind.Sequential)]
internal struct VultraEnvironmentSettings
{
    public float Intensity;
}

[StructLayout(LayoutKind.Sequential)]
internal struct VultraLightSettings
{
    public float Red;
    public float Green;
    public float Blue;
    public float Intensity;
    public float Range;
    public float InnerCone;
    public float OuterCone;
}

[StructLayout(LayoutKind.Sequential)]
internal struct VultraMaterialParameters
{
    public float BaseRed;
    public float BaseGreen;
    public float BaseBlue;
    public float BaseAlpha;
    public float BaseWeight;
    public float BaseMetalness;
    public float BaseDiffuseRoughness;
    public float SpecularWeight;
    public float SpecularRed;
    public float SpecularGreen;
    public float SpecularBlue;
    public float SpecularRoughness;
    public float SpecularIor;
    public float CoatWeight;
    public float CoatRoughness;
    public float CoatIor;
    public float EmissionRed;
    public float EmissionGreen;
    public float EmissionBlue;
    public float EmissionLuminance;
    public float NormalScale;
    public float OcclusionStrength;
    public float AlphaCutoff;
}

[StructLayout(LayoutKind.Sequential)]
internal struct VultraSceneTranslation
{
    public float X;
    public float Y;
    public float Z;
}


[StructLayout(LayoutKind.Sequential)]
internal unsafe struct VultraSceneApi
{
    public uint Version;
    public uint StructSize;
    public delegate* unmanaged[Cdecl]<VultraSceneFrame, ulong, VultraCameraSettings*, VultraStatus> CameraSettings;
    public delegate* unmanaged[Cdecl]<VultraSceneFrame, ulong, ulong*, VultraStatus> ChildCount;
    public delegate* unmanaged[Cdecl]<VultraSceneFrame, ulong, ulong, ulong*, VultraStatus> ChildId;
    public delegate* unmanaged[Cdecl]<VultraSceneFrame, ulong, ulong, VultraStatus> CopyMeshModel;
    public delegate* unmanaged[Cdecl]<VultraSceneFrame, ulong, byte*, ulong, ulong*, VultraStatus> CreateCamera;
    public delegate* unmanaged[Cdecl]<VultraSceneFrame, ulong, byte*, ulong, ulong*, VultraStatus> CreateEnvironment;
    public delegate* unmanaged[Cdecl]<VultraSceneFrame, ulong, byte*, ulong, ulong, ulong*, VultraStatus> CreateLight;
    public delegate* unmanaged[Cdecl]<VultraSceneFrame, byte*, ulong, ulong*, VultraStatus> CreateMaterial;
    public delegate* unmanaged[Cdecl]<VultraSceneFrame, ulong, byte*, ulong, byte*, ulong, ulong*, VultraStatus> CreateMesh;
    public delegate* unmanaged[Cdecl]<VultraSceneFrame, ulong, byte*, ulong, ulong*, VultraStatus> CreateNode;
    public delegate* unmanaged[Cdecl]<VultraSceneFrame, ulong*, VultraStatus> CurrentCamera;
    public delegate* unmanaged[Cdecl]<VultraSceneFrame, ulong*, VultraStatus> CurrentEnvironment;
    public delegate* unmanaged[Cdecl]<VultraSceneFrame, ulong, ulong, ulong*, VultraStatus> DuplicateMesh;
    public delegate* unmanaged[Cdecl]<VultraSceneFrame, ulong, VultraEnvironmentSettings*, VultraStatus> EnvironmentSettings;
    public delegate* unmanaged[Cdecl]<VultraSceneFrame, ulong, ulong*, VultraStatus> LightKind;
    public delegate* unmanaged[Cdecl]<VultraSceneFrame, ulong, VultraLightSettings*, VultraStatus> LightSettings;
    public delegate* unmanaged[Cdecl]<VultraSceneFrame, ulong, byte**, ulong*, VultraStatus> MaterialName;
    public delegate* unmanaged[Cdecl]<VultraSceneFrame, ulong, VultraMaterialParameters*, VultraStatus> MaterialParameters;
    public delegate* unmanaged[Cdecl]<VultraSceneFrame, ulong, ulong, ulong*, VultraStatus> MeshMaterial;
    public delegate* unmanaged[Cdecl]<VultraSceneFrame, ulong, byte**, ulong*, VultraStatus> NodeName;
    public delegate* unmanaged[Cdecl]<VultraSceneFrame, ulong, VultraSceneTranslation*, VultraStatus> NodeTranslation;
    public delegate* unmanaged[Cdecl]<VultraSceneFrame, ulong, VultraStatus> RemoveMaterial;
    public delegate* unmanaged[Cdecl]<VultraSceneFrame, ulong, VultraStatus> RemoveNode;
    public delegate* unmanaged[Cdecl]<VultraSceneFrame, ulong, ulong, VultraStatus> ReparentNode;
    public delegate* unmanaged[Cdecl]<VultraSceneFrame, ulong*, VultraStatus> RootId;
    public delegate* unmanaged[Cdecl]<VultraSceneFrame, ulong, VultraCameraSettings, VultraStatus> SetCameraSettings;
    public delegate* unmanaged[Cdecl]<VultraSceneFrame, ulong, VultraStatus> SetCurrentCamera;
    public delegate* unmanaged[Cdecl]<VultraSceneFrame, ulong, VultraStatus> SetCurrentEnvironment;
    public delegate* unmanaged[Cdecl]<VultraSceneFrame, ulong, byte*, ulong, VultraStatus> SetEnvironmentAsset;
    public delegate* unmanaged[Cdecl]<VultraSceneFrame, ulong, VultraEnvironmentSettings, VultraStatus> SetEnvironmentSettings;
    public delegate* unmanaged[Cdecl]<VultraSceneFrame, ulong, VultraLightSettings, VultraStatus> SetLightSettings;
    public delegate* unmanaged[Cdecl]<VultraSceneFrame, ulong, VultraMaterialParameters, VultraStatus> SetMaterialParameters;
    public delegate* unmanaged[Cdecl]<VultraSceneFrame, ulong, ulong, ulong, VultraStatus> SetMeshMaterial;
    public delegate* unmanaged[Cdecl]<VultraSceneFrame, ulong, byte*, ulong, VultraStatus> SetMeshModel;
    public delegate* unmanaged[Cdecl]<VultraSceneFrame, ulong, VultraSceneTranslation, VultraStatus> SetNodeTranslation;
}

[StructLayout(LayoutKind.Sequential)]
internal unsafe struct VultraScriptRegistrationApi
{
    public uint Version;
    public uint StructSize;
    public void* UserData;
    public delegate* unmanaged[Cdecl]<void*, byte*, ulong, VultraStatus> RegisterClass;
}

[StructLayout(LayoutKind.Sequential)]
internal unsafe struct VultraHostApi
{
    public uint Version;
    public uint StructSize;
    public VultraUiApi* Ui;
    public VultraSceneApi* Scene;
    public VultraScriptRegistrationApi* Scripts;
    public void* Research;
}

[StructLayout(LayoutKind.Sequential)]
internal unsafe struct VultraPluginApi
{
    public uint Version;
    public uint StructSize;
    public void* UserData;
    public delegate* unmanaged[Cdecl]<void*, VultraSceneFrame, float, VultraStatus> Update;
    public delegate* unmanaged[Cdecl]<void*, VultraUiFrame, VultraStatus> OnGui;
    public delegate* unmanaged[Cdecl]<void*, VultraStatus> Stop;
}
