// Generated by scripts/codegen.py. Do not edit.
#pragma once
#include <vultra/core/base/property.hpp>
#include <vultra/servers/rendering/builtin/builtin_renderer.hpp>

namespace vultra
{
    const ObjectTypeInfo& renderSettingsType();
} // namespace vultra
