struct RayVertex
{
    float4 position;
    float4 normal;
    float4 color;
    float4 emission;
};
struct RayParameters
{
    column_major float4x4 inverseViewProjection;
    float4 cameraPosition;
    float4 missColor;
    float4 lightPositionArea;
    float4 lightNormal;
    float4 lightEmission;
};
struct ColorPayload { float3 color; };
struct ShadowPayload { bool blocked; };

[[vk::binding(0, 0)]] RaytracingAccelerationStructure scene;
[[vk::binding(1, 0)]] RWTexture2D<float4> outputImage;
[[vk::binding(2, 0)]] StructuredBuffer<RayVertex> vertices;
[[vk::binding(3, 0)]] ConstantBuffer<RayParameters> parameters;

[shader("miss")]
void missMain(inout ColorPayload payload)
{
    payload.color = parameters.missColor.rgb;
}
