// Generated by scripts/codegen.py. Do not edit.
#include <vultra/api/render_settings.generated.hpp>

#include <array>

namespace vultra
{
    std::span<const ReflectedProperty> renderSettingsProperties()
    {
        static constexpr std::array<ReflectedProperty, 5> properties = {{
            {"path", "Path", ReflectedPropertyKind::eEnum, 0, 0},
            {"lightIntensity", "Sun intensity", ReflectedPropertyKind::eFloat, 0, 10},
            {"exposure", "Exposure (EV)", ReflectedPropertyKind::eFloat, -4, 4},
            {"ibl", "IBL", ReflectedPropertyKind::eBool, 0, 0},
            {"skybox", "Skybox", ReflectedPropertyKind::eBool, 0, 0},
        }};
        return properties;
    }

    bool drawRenderSettings(EditorGuiInspector& inspector, RenderSettings& settings)
    {
        bool              changed   = false;
        int               selected  = settings.path == RenderPath::eNaiveDeferred ? 0 : 1;
        const char* const options[] = {"NaiveDeferred", "NaiveForward"};
        if (inspector.choice({"path", "Path"}, &selected, options, 2))
        {
            settings.path = static_cast<RenderPath>(selected);
            changed       = true;
        }
        changed |= inspector.floatSlider({"lightIntensity", "Sun intensity"}, &settings.lightIntensity, 0, 10);
        changed |= inspector.floatSlider({"exposure", "Exposure (EV)"}, &settings.exposure, -4, 4);
        changed |= inspector.boolField({"ibl", "IBL"}, &settings.ibl);
        changed |= inspector.boolField({"skybox", "Skybox"}, &settings.skybox);
        return changed;
    }
} // namespace vultra
