// Generated by scripts/codegen.py. Do not edit.
#include <vultra/api/render_settings.generated.hpp>
#include <vultra/servers/rendering/builtin/render_properties.generated.hpp>

namespace vultra
{
    bool drawRenderSettings(EditorGuiInspector& inspector, RenderSettings& settings)
    {
        return inspector.properties(renderSettingsType(), &settings);
    }

} // namespace vultra
