// Generated by scripts/codegen.py. Do not edit.
#include <vultra/api/scene_properties.generated.hpp>
#include <vultra/assets/material_properties.generated.hpp>
#include <vultra/scene/render_properties.generated.hpp>

namespace vultra
{
    bool drawCameraSettings(EditorGuiInspector& inspector, CameraSettings& settings)
    {
        return inspector.properties(cameraSettingsType(), &settings);
    }

    bool drawEnvironmentSettings(EditorGuiInspector& inspector, EnvironmentSettings& settings)
    {
        return inspector.properties(environmentSettingsType(), &settings);
    }

    bool drawLightSettings(EditorGuiInspector& inspector, LightSettings& settings)
    {
        return inspector.properties(lightSettingsType(), &settings);
    }

    bool drawMaterialParameters(EditorGuiInspector& inspector, MaterialParameters& settings)
    {
        return inspector.properties(materialParametersType(), &settings);
    }

} // namespace vultra
