// Generated by scripts/codegen.py. Do not edit.
#include <vultra/api/scene_properties.generated.hpp>

#include <array>

namespace vultra
{
    std::span<const ReflectedProperty> cameraSettingsProperties()
    {
        static constexpr std::array<ReflectedProperty, 3> properties = {{
            {"verticalFov", "FOV (rad)", ReflectedPropertyKind::eFloat, 0.01, 3.13},
            {"nearPlane", "Near plane", ReflectedPropertyKind::eFloat, 0.0001, 1000000},
            {"farPlane", "Far plane", ReflectedPropertyKind::eFloat, 0.0001, 1000000},
        }};
        return properties;
    }

    bool drawCameraSettings(EditorGuiInspector& inspector, CameraSettings& settings)
    {
        bool changed = false;
        changed |=
            inspector.floatSlider({"CameraSettings.verticalFov", "FOV (rad)"}, &settings.verticalFov, 0.01, 3.13);
        changed |= inspector.floatField({"CameraSettings.nearPlane", "Near plane"},
                                        &settings.nearPlane,
                                        0.01,
                                        0.0001,
                                        1000000);
        changed |=
            inspector.floatField({"CameraSettings.farPlane", "Far plane"}, &settings.farPlane, 0.1, 0.0001, 1000000);
        return changed;
    }

    std::span<const ReflectedProperty> environmentSettingsProperties()
    {
        static constexpr std::array<ReflectedProperty, 1> properties = {{
            {"intensity", "Intensity", ReflectedPropertyKind::eFloat, 0, 4},
        }};
        return properties;
    }

    bool drawEnvironmentSettings(EditorGuiInspector& inspector, EnvironmentSettings& settings)
    {
        bool changed = false;
        changed |= inspector.floatSlider({"EnvironmentSettings.intensity", "Intensity"}, &settings.intensity, 0, 4);
        return changed;
    }

    std::span<const ReflectedProperty> lightSettingsProperties()
    {
        static constexpr std::array<ReflectedProperty, 7> properties = {{
            {"red", "Red", ReflectedPropertyKind::eFloat, 0, 4},
            {"green", "Green", ReflectedPropertyKind::eFloat, 0, 4},
            {"blue", "Blue", ReflectedPropertyKind::eFloat, 0, 4},
            {"intensity", "Intensity", ReflectedPropertyKind::eFloat, 0, 100},
            {"range", "Range", ReflectedPropertyKind::eFloat, 0.001, 1000000},
            {"innerCone", "Inner cone (rad)", ReflectedPropertyKind::eFloat, 0, 1.56},
            {"outerCone", "Outer cone (rad)", ReflectedPropertyKind::eFloat, 0.001, 1.56},
        }};
        return properties;
    }

    bool drawLightSettings(EditorGuiInspector& inspector, LightSettings& settings)
    {
        bool changed = false;
        changed |= inspector.floatSlider({"LightSettings.red", "Red"}, &settings.red, 0, 4);
        changed |= inspector.floatSlider({"LightSettings.green", "Green"}, &settings.green, 0, 4);
        changed |= inspector.floatSlider({"LightSettings.blue", "Blue"}, &settings.blue, 0, 4);
        changed |= inspector.floatField({"LightSettings.intensity", "Intensity"}, &settings.intensity, 0.1, 0, 100);
        changed |= inspector.floatField({"LightSettings.range", "Range"}, &settings.range, 0.1, 0.001, 1000000);
        changed |= inspector.floatSlider({"LightSettings.innerCone", "Inner cone (rad)"}, &settings.innerCone, 0, 1.56);
        changed |=
            inspector.floatSlider({"LightSettings.outerCone", "Outer cone (rad)"}, &settings.outerCone, 0.001, 1.56);
        return changed;
    }

    std::span<const ReflectedProperty> materialParametersProperties()
    {
        static constexpr std::array<ReflectedProperty, 23> properties = {{
            {"baseRed", "Base red", ReflectedPropertyKind::eFloat, 0, 4},
            {"baseGreen", "Base green", ReflectedPropertyKind::eFloat, 0, 4},
            {"baseBlue", "Base blue", ReflectedPropertyKind::eFloat, 0, 4},
            {"baseAlpha", "Base alpha", ReflectedPropertyKind::eFloat, 0, 1},
            {"baseWeight", "Base weight", ReflectedPropertyKind::eFloat, 0, 1},
            {"baseMetalness", "Metalness", ReflectedPropertyKind::eFloat, 0, 1},
            {"baseDiffuseRoughness", "Diffuse roughness", ReflectedPropertyKind::eFloat, 0, 1},
            {"specularWeight", "Specular weight", ReflectedPropertyKind::eFloat, 0, 1},
            {"specularRed", "Specular red", ReflectedPropertyKind::eFloat, 0, 4},
            {"specularGreen", "Specular green", ReflectedPropertyKind::eFloat, 0, 4},
            {"specularBlue", "Specular blue", ReflectedPropertyKind::eFloat, 0, 4},
            {"specularRoughness", "Roughness", ReflectedPropertyKind::eFloat, 0, 1},
            {"specularIor", "Specular IOR", ReflectedPropertyKind::eFloat, 1, 3},
            {"coatWeight", "Coat weight", ReflectedPropertyKind::eFloat, 0, 1},
            {"coatRoughness", "Coat roughness", ReflectedPropertyKind::eFloat, 0, 1},
            {"coatIor", "Coat IOR", ReflectedPropertyKind::eFloat, 1, 3},
            {"emissionRed", "Emission red", ReflectedPropertyKind::eFloat, 0, 4},
            {"emissionGreen", "Emission green", ReflectedPropertyKind::eFloat, 0, 4},
            {"emissionBlue", "Emission blue", ReflectedPropertyKind::eFloat, 0, 4},
            {"emissionLuminance", "Emission luminance", ReflectedPropertyKind::eFloat, 0, 100},
            {"normalScale", "Normal scale", ReflectedPropertyKind::eFloat, 0, 4},
            {"occlusionStrength", "Occlusion strength", ReflectedPropertyKind::eFloat, 0, 1},
            {"alphaCutoff", "Alpha cutoff", ReflectedPropertyKind::eFloat, -1, 1},
        }};
        return properties;
    }

    bool drawMaterialParameters(EditorGuiInspector& inspector, MaterialParameters& settings)
    {
        bool changed = false;
        changed |= inspector.floatSlider({"MaterialParameters.baseRed", "Base red"}, &settings.baseRed, 0, 4);
        changed |= inspector.floatSlider({"MaterialParameters.baseGreen", "Base green"}, &settings.baseGreen, 0, 4);
        changed |= inspector.floatSlider({"MaterialParameters.baseBlue", "Base blue"}, &settings.baseBlue, 0, 4);
        changed |= inspector.floatSlider({"MaterialParameters.baseAlpha", "Base alpha"}, &settings.baseAlpha, 0, 1);
        changed |= inspector.floatSlider({"MaterialParameters.baseWeight", "Base weight"}, &settings.baseWeight, 0, 1);
        changed |=
            inspector.floatSlider({"MaterialParameters.baseMetalness", "Metalness"}, &settings.baseMetalness, 0, 1);
        changed |= inspector.floatSlider({"MaterialParameters.baseDiffuseRoughness", "Diffuse roughness"},
                                         &settings.baseDiffuseRoughness,
                                         0,
                                         1);
        changed |= inspector.floatSlider({"MaterialParameters.specularWeight", "Specular weight"},
                                         &settings.specularWeight,
                                         0,
                                         1);
        changed |=
            inspector.floatSlider({"MaterialParameters.specularRed", "Specular red"}, &settings.specularRed, 0, 4);
        changed |= inspector.floatSlider({"MaterialParameters.specularGreen", "Specular green"},
                                         &settings.specularGreen,
                                         0,
                                         4);
        changed |=
            inspector.floatSlider({"MaterialParameters.specularBlue", "Specular blue"}, &settings.specularBlue, 0, 4);
        changed |= inspector.floatSlider({"MaterialParameters.specularRoughness", "Roughness"},
                                         &settings.specularRoughness,
                                         0,
                                         1);
        changed |=
            inspector.floatSlider({"MaterialParameters.specularIor", "Specular IOR"}, &settings.specularIor, 1, 3);
        changed |= inspector.floatSlider({"MaterialParameters.coatWeight", "Coat weight"}, &settings.coatWeight, 0, 1);
        changed |= inspector.floatSlider({"MaterialParameters.coatRoughness", "Coat roughness"},
                                         &settings.coatRoughness,
                                         0,
                                         1);
        changed |= inspector.floatSlider({"MaterialParameters.coatIor", "Coat IOR"}, &settings.coatIor, 1, 3);
        changed |=
            inspector.floatSlider({"MaterialParameters.emissionRed", "Emission red"}, &settings.emissionRed, 0, 4);
        changed |= inspector.floatSlider({"MaterialParameters.emissionGreen", "Emission green"},
                                         &settings.emissionGreen,
                                         0,
                                         4);
        changed |=
            inspector.floatSlider({"MaterialParameters.emissionBlue", "Emission blue"}, &settings.emissionBlue, 0, 4);
        changed |= inspector.floatSlider({"MaterialParameters.emissionLuminance", "Emission luminance"},
                                         &settings.emissionLuminance,
                                         0,
                                         100);
        changed |=
            inspector.floatSlider({"MaterialParameters.normalScale", "Normal scale"}, &settings.normalScale, 0, 4);
        changed |= inspector.floatSlider({"MaterialParameters.occlusionStrength", "Occlusion strength"},
                                         &settings.occlusionStrength,
                                         0,
                                         1);
        changed |=
            inspector.floatSlider({"MaterialParameters.alphaCutoff", "Alpha cutoff"}, &settings.alphaCutoff, -1, 1);
        return changed;
    }
} // namespace vultra
