// Generated by scripts/codegen.py. Do not edit.
#include <vultra/api/ui_bridge.hpp>
#include <vultra/ui/editor_gui.hpp>
#include <vultra/ui/editor_gui_frame.hpp>

#include <cstddef>

static VultraStatus uiButton(VultraUiFrame frame, const char* text, uint64_t textSize, uint8_t* changed)
{
    if (!frame.context || (!text && textSize != 0) || !changed)
    {
        return VULTRA_STATUS_INVALID_ARGUMENT;
    }
    auto* gui = static_cast<vultra::EditorGui*>(frame.context);
    if (!gui->frameActive() || gui->frameSerial() != frame.serial)
    {
        return VULTRA_STATUS_INVALID_FRAME;
    }
    try
    {
        auto current = gui->frame();
        *changed     = vultra::guiButton(current, {text ? text : "", static_cast<size_t>(textSize)});
        return VULTRA_STATUS_OK;
    }
    catch (...)
    {
        return VULTRA_STATUS_ERROR;
    }
}

static VultraStatus uiText(VultraUiFrame frame, const char* text, uint64_t textSize)
{
    if (!frame.context || (!text && textSize != 0))
    {
        return VULTRA_STATUS_INVALID_ARGUMENT;
    }
    auto* gui = static_cast<vultra::EditorGui*>(frame.context);
    if (!gui->frameActive() || gui->frameSerial() != frame.serial)
    {
        return VULTRA_STATUS_INVALID_FRAME;
    }
    try
    {
        auto current = gui->frame();
        vultra::guiText(current, {text ? text : "", static_cast<size_t>(textSize)});
        return VULTRA_STATUS_OK;
    }
    catch (...)
    {
        return VULTRA_STATUS_ERROR;
    }
}

namespace vultra
{
    VultraUiFrame makeUiFrame(EditorGui& gui)
    {
        return {&gui, gui.frameSerial()};
    }

    const VultraUiApi& uiApi()
    {
        static const VultraUiApi api {VULTRA_ABI_VERSION, sizeof(VultraUiApi), uiButton, uiText};
        return api;
    }
} // namespace vultra
