// Generated by scripts/codegen.py. Do not edit.
#include <vultra/api/scene_bridge.hpp>
#include <vultra/scene/scene_api.hpp>

#include <stdexcept>

static VultraStatus abiSceneChildCount(VultraSceneFrame frame, uint64_t parent, uint64_t* value)
{
    if (!frame.context || !value)
    {
        return VULTRA_STATUS_INVALID_ARGUMENT;
    }
    auto* access = static_cast<vultra::SceneAccess*>(frame.context);
    if (!access->active || access->serial != frame.serial || !access->scene)
    {
        return VULTRA_STATUS_INVALID_FRAME;
    }
    try
    {
        *value = vultra::sceneChildCount(*access->scene, vultra::ObjectId {parent});
        return VULTRA_STATUS_OK;
    }
    catch (const std::invalid_argument&)
    {
        return VULTRA_STATUS_INVALID_ARGUMENT;
    }
    catch (...)
    {
        return VULTRA_STATUS_ERROR;
    }
}

static VultraStatus abiSceneChildId(VultraSceneFrame frame, uint64_t parent, uint64_t index, uint64_t* value)
{
    if (!frame.context || !value)
    {
        return VULTRA_STATUS_INVALID_ARGUMENT;
    }
    auto* access = static_cast<vultra::SceneAccess*>(frame.context);
    if (!access->active || access->serial != frame.serial || !access->scene)
    {
        return VULTRA_STATUS_INVALID_FRAME;
    }
    try
    {
        *value = vultra::sceneChildId(*access->scene, vultra::ObjectId {parent}, index).value;
        return VULTRA_STATUS_OK;
    }
    catch (const std::invalid_argument&)
    {
        return VULTRA_STATUS_INVALID_ARGUMENT;
    }
    catch (...)
    {
        return VULTRA_STATUS_ERROR;
    }
}

static VultraStatus abiSceneNodeName(VultraSceneFrame frame, uint64_t node, const char** data, uint64_t* size)
{
    if (!frame.context || !data || !size)
    {
        return VULTRA_STATUS_INVALID_ARGUMENT;
    }
    auto* access = static_cast<vultra::SceneAccess*>(frame.context);
    if (!access->active || access->serial != frame.serial || !access->scene)
    {
        return VULTRA_STATUS_INVALID_FRAME;
    }
    try
    {
        const auto result = vultra::sceneNodeName(*access->scene, vultra::ObjectId {node});
        *data             = result.data();
        *size             = result.size();
        return VULTRA_STATUS_OK;
    }
    catch (const std::invalid_argument&)
    {
        return VULTRA_STATUS_INVALID_ARGUMENT;
    }
    catch (...)
    {
        return VULTRA_STATUS_ERROR;
    }
}

static VultraStatus abiSceneNodeTranslation(VultraSceneFrame frame, uint64_t node, VultraSceneTranslation* value)
{
    if (!frame.context || !value)
    {
        return VULTRA_STATUS_INVALID_ARGUMENT;
    }
    auto* access = static_cast<vultra::SceneAccess*>(frame.context);
    if (!access->active || access->serial != frame.serial || !access->scene)
    {
        return VULTRA_STATUS_INVALID_FRAME;
    }
    try
    {
        const auto result = vultra::sceneNodeTranslation(*access->scene, vultra::ObjectId {node});
        *value            = {result.x, result.y, result.z};
        return VULTRA_STATUS_OK;
    }
    catch (const std::invalid_argument&)
    {
        return VULTRA_STATUS_INVALID_ARGUMENT;
    }
    catch (...)
    {
        return VULTRA_STATUS_ERROR;
    }
}

static VultraStatus abiSceneRootId(VultraSceneFrame frame, uint64_t* value)
{
    if (!frame.context || !value)
    {
        return VULTRA_STATUS_INVALID_ARGUMENT;
    }
    auto* access = static_cast<vultra::SceneAccess*>(frame.context);
    if (!access->active || access->serial != frame.serial || !access->scene)
    {
        return VULTRA_STATUS_INVALID_FRAME;
    }
    try
    {
        *value = vultra::sceneRootId(*access->scene).value;
        return VULTRA_STATUS_OK;
    }
    catch (const std::invalid_argument&)
    {
        return VULTRA_STATUS_INVALID_ARGUMENT;
    }
    catch (...)
    {
        return VULTRA_STATUS_ERROR;
    }
}

static VultraStatus
abiSceneSetNodeTranslation(VultraSceneFrame frame, uint64_t node, VultraSceneTranslation translation)
{
    if (!frame.context)
    {
        return VULTRA_STATUS_INVALID_ARGUMENT;
    }
    auto* access = static_cast<vultra::SceneAccess*>(frame.context);
    if (!access->active || access->serial != frame.serial || !access->scene)
    {
        return VULTRA_STATUS_INVALID_FRAME;
    }
    try
    {
        vultra::sceneSetNodeTranslation(*access->scene,
                                        vultra::ObjectId {node},
                                        vultra::SceneTranslation {translation.x, translation.y, translation.z});
        return VULTRA_STATUS_OK;
    }
    catch (const std::invalid_argument&)
    {
        return VULTRA_STATUS_INVALID_ARGUMENT;
    }
    catch (...)
    {
        return VULTRA_STATUS_ERROR;
    }
}

namespace vultra
{
    const VultraSceneApi& sceneApi()
    {
        static const VultraSceneApi api {VULTRA_ABI_VERSION,
                                         sizeof(VultraSceneApi),
                                         abiSceneChildCount,
                                         abiSceneChildId,
                                         abiSceneNodeName,
                                         abiSceneNodeTranslation,
                                         abiSceneRootId,
                                         abiSceneSetNodeTranslation};
        return api;
    }
} // namespace vultra
