// Generated by scripts/codegen.py. Do not edit.
#include <vultra/scene/render_properties.generated.hpp>

#include <array>

namespace vultra
{
    const ObjectTypeInfo& cameraSettingsType()
    {
        static const std::array<PropertyInfo, 3> properties = {{
            {"verticalFov",
             "FOV (rad)",
             "CameraSettings.verticalFov",
             "/vertical_fov",
             PropertyKind::eFloat,
             PropertyFlags::eSerialize | PropertyFlags::eInspect | PropertyFlags::eBind,
             PropertyWidget::eSlider,
             0,
             0.01,
             3.13,
             1,
             {},
             {},
             [](const void* object) -> PropertyValue
             {
                 return static_cast<const CameraSettings*>(object)->verticalFov;
             },
             [](void* object, const PropertyValue& value)
             {
                 static_cast<CameraSettings*>(object)->verticalFov = std::get<float>(value);
             },
             []() -> PropertyValue
             {
                 return CameraSettings {}.verticalFov;
             }},
            {"nearPlane",
             "Near plane",
             "CameraSettings.nearPlane",
             "/near",
             PropertyKind::eFloat,
             PropertyFlags::eSerialize | PropertyFlags::eInspect | PropertyFlags::eBind,
             PropertyWidget::eDrag,
             0,
             0.0001,
             1000000,
             0.01,
             {},
             {},
             [](const void* object) -> PropertyValue
             {
                 return static_cast<const CameraSettings*>(object)->nearPlane;
             },
             [](void* object, const PropertyValue& value)
             {
                 static_cast<CameraSettings*>(object)->nearPlane = std::get<float>(value);
             },
             []() -> PropertyValue
             {
                 return CameraSettings {}.nearPlane;
             }},
            {"farPlane",
             "Far plane",
             "CameraSettings.farPlane",
             "/far",
             PropertyKind::eFloat,
             PropertyFlags::eSerialize | PropertyFlags::eInspect | PropertyFlags::eBind,
             PropertyWidget::eDrag,
             0,
             0.0001,
             1000000,
             0.1,
             {},
             {},
             [](const void* object) -> PropertyValue
             {
                 return static_cast<const CameraSettings*>(object)->farPlane;
             },
             [](void* object, const PropertyValue& value)
             {
                 static_cast<CameraSettings*>(object)->farPlane = std::get<float>(value);
             },
             []() -> PropertyValue
             {
                 return CameraSettings {}.farPlane;
             }},
        }};
        static const ObjectTypeInfo              type       = {"CameraSettings", properties};
        return type;
    }

    const ObjectTypeInfo& environmentSettingsType()
    {
        static const std::array<PropertyInfo, 1> properties = {{
            {"intensity",
             "Intensity",
             "EnvironmentSettings.intensity",
             "/intensity",
             PropertyKind::eFloat,
             PropertyFlags::eSerialize | PropertyFlags::eInspect | PropertyFlags::eBind,
             PropertyWidget::eSlider,
             0,
             0,
             4,
             1,
             {},
             {},
             [](const void* object) -> PropertyValue
             {
                 return static_cast<const EnvironmentSettings*>(object)->intensity;
             },
             [](void* object, const PropertyValue& value)
             {
                 static_cast<EnvironmentSettings*>(object)->intensity = std::get<float>(value);
             },
             []() -> PropertyValue
             {
                 return EnvironmentSettings {}.intensity;
             }},
        }};
        static const ObjectTypeInfo              type       = {"EnvironmentSettings", properties};
        return type;
    }

    const ObjectTypeInfo& lightSettingsType()
    {
        static const std::array<PropertyInfo, 7> properties = {{
            {"red",
             "Red",
             "LightSettings.red",
             "/color/0",
             PropertyKind::eFloat,
             PropertyFlags::eSerialize | PropertyFlags::eInspect | PropertyFlags::eBind,
             PropertyWidget::eSlider,
             0,
             0,
             4,
             1,
             {},
             {},
             [](const void* object) -> PropertyValue
             {
                 return static_cast<const LightSettings*>(object)->red;
             },
             [](void* object, const PropertyValue& value)
             {
                 static_cast<LightSettings*>(object)->red = std::get<float>(value);
             },
             []() -> PropertyValue
             {
                 return LightSettings {}.red;
             }},
            {"green",
             "Green",
             "LightSettings.green",
             "/color/1",
             PropertyKind::eFloat,
             PropertyFlags::eSerialize | PropertyFlags::eInspect | PropertyFlags::eBind,
             PropertyWidget::eSlider,
             0,
             0,
             4,
             1,
             {},
             {},
             [](const void* object) -> PropertyValue
             {
                 return static_cast<const LightSettings*>(object)->green;
             },
             [](void* object, const PropertyValue& value)
             {
                 static_cast<LightSettings*>(object)->green = std::get<float>(value);
             },
             []() -> PropertyValue
             {
                 return LightSettings {}.green;
             }},
            {"blue",
             "Blue",
             "LightSettings.blue",
             "/color/2",
             PropertyKind::eFloat,
             PropertyFlags::eSerialize | PropertyFlags::eInspect | PropertyFlags::eBind,
             PropertyWidget::eSlider,
             0,
             0,
             4,
             1,
             {},
             {},
             [](const void* object) -> PropertyValue
             {
                 return static_cast<const LightSettings*>(object)->blue;
             },
             [](void* object, const PropertyValue& value)
             {
                 static_cast<LightSettings*>(object)->blue = std::get<float>(value);
             },
             []() -> PropertyValue
             {
                 return LightSettings {}.blue;
             }},
            {"intensity",
             "Intensity",
             "LightSettings.intensity",
             "/intensity",
             PropertyKind::eFloat,
             PropertyFlags::eSerialize | PropertyFlags::eInspect | PropertyFlags::eBind,
             PropertyWidget::eDrag,
             0,
             0,
             100,
             0.1,
             {},
             {},
             [](const void* object) -> PropertyValue
             {
                 return static_cast<const LightSettings*>(object)->intensity;
             },
             [](void* object, const PropertyValue& value)
             {
                 static_cast<LightSettings*>(object)->intensity = std::get<float>(value);
             },
             []() -> PropertyValue
             {
                 return LightSettings {}.intensity;
             }},
            {"range",
             "Range",
             "LightSettings.range",
             "/range",
             PropertyKind::eFloat,
             PropertyFlags::eSerialize | PropertyFlags::eInspect | PropertyFlags::eBind,
             PropertyWidget::eDrag,
             0,
             0.001,
             1000000,
             0.1,
             {},
             {},
             [](const void* object) -> PropertyValue
             {
                 return static_cast<const LightSettings*>(object)->range;
             },
             [](void* object, const PropertyValue& value)
             {
                 static_cast<LightSettings*>(object)->range = std::get<float>(value);
             },
             []() -> PropertyValue
             {
                 return LightSettings {}.range;
             }},
            {"innerCone",
             "Inner cone (rad)",
             "LightSettings.innerCone",
             "/inner_cone",
             PropertyKind::eFloat,
             PropertyFlags::eSerialize | PropertyFlags::eInspect | PropertyFlags::eBind,
             PropertyWidget::eSlider,
             0,
             0,
             1.56,
             1,
             {},
             {},
             [](const void* object) -> PropertyValue
             {
                 return static_cast<const LightSettings*>(object)->innerCone;
             },
             [](void* object, const PropertyValue& value)
             {
                 static_cast<LightSettings*>(object)->innerCone = std::get<float>(value);
             },
             []() -> PropertyValue
             {
                 return LightSettings {}.innerCone;
             }},
            {"outerCone",
             "Outer cone (rad)",
             "LightSettings.outerCone",
             "/outer_cone",
             PropertyKind::eFloat,
             PropertyFlags::eSerialize | PropertyFlags::eInspect | PropertyFlags::eBind,
             PropertyWidget::eSlider,
             0,
             0.001,
             1.56,
             1,
             {},
             {},
             [](const void* object) -> PropertyValue
             {
                 return static_cast<const LightSettings*>(object)->outerCone;
             },
             [](void* object, const PropertyValue& value)
             {
                 static_cast<LightSettings*>(object)->outerCone = std::get<float>(value);
             },
             []() -> PropertyValue
             {
                 return LightSettings {}.outerCone;
             }},
        }};
        static const ObjectTypeInfo              type       = {"LightSettings", properties};
        return type;
    }

} // namespace vultra
