-- Shared build dependencies: prepare each source once even when several examples use it.
local function asset_target(name, source)
    target(name)
        set_kind("phony")
        set_default(false)
        add_deps("vultra-import", {inherit = false})
        on_build(function (target)
            import("private.action.run.runenvs")
            local importer = target:dep("vultra-import")
            local addenvs, setenvs = runenvs.make(importer)
            print("Preparing asset: %s", source)
            os.execv(path.absolute(importer:targetfile()),
                {source, "--cache-dir", path.join(os.projectdir(), ".vultra", "assets")},
                {curdir = os.projectdir(), addenvs = addenvs, setenvs = setenvs})
        end)
    target_end()
end

asset_target("asset-damaged-helmet", "resources/models/DamagedHelmet/DamagedHelmet.glb")
asset_target("asset-sponza", "resources/models/Sponza/Sponza.gltf")
asset_target("asset-rayquery", "resources/models/raytracing_shadow/raytracing_shadow.gltf")
asset_target("asset-cornell-box", "resources/models/CornellBox/CornellBox-Original.obj")

target("example-assets")
    set_kind("phony")
    set_default(false)
    add_deps("asset-damaged-helmet", "asset-sponza", "asset-rayquery", "asset-cornell-box", {inherit = false})
target_end()

target("example-research")
    set_kind("binary")
    set_default(true)
    add_deps("vultra")
    add_deps("asset-damaged-helmet", {inherit = false})
    add_files("research/main.cpp", "research/color_gain.cpp")
    set_rundir("$(projectdir)")
target_end()

target("example-native-plugin")
    set_kind("shared")
    set_default(false)
    set_languages("c11")
    add_includedirs("../source/api/include")
    add_files("ui/native_plugin.c")
target_end()

target("example-common")
    set_kind("static")
    set_default(false)
    add_deps("vultra", {public = true})
    add_files("common/colored_mesh.cpp")
target_end()

target("example-basics")
    set_kind("binary")
    set_default(true)
    add_deps("example-common")
    add_files("basics/*.cpp")
    set_rundir("$(projectdir)")
target_end()

target("example-ui")
    set_kind("binary")
    set_default(true)
    add_deps("example-common", "vultra-vgui")
    add_files("ui/main.cpp")
    set_rundir("$(projectdir)")
target_end()

target("example-scene")
    set_kind("binary")
    set_default(true)
    add_deps("vultra", "example-common")
    add_deps("asset-damaged-helmet", "asset-sponza", {inherit = false})
    add_files("scene/*.cpp")
    set_rundir("$(projectdir)")
target_end()

target("example-ray-common")
    set_kind("static")
    set_default(false)
    add_deps("vultra", {public = true})
    add_files("common/ray_scene.cpp", "common/ray_tracing_app.cpp")
target_end()

target("example-ray")
    set_kind("binary")
    set_default(true)
    add_deps("example-ray-common")
    add_deps("asset-rayquery", "asset-cornell-box", {inherit = false})
    add_files("ray/*.cpp")
    set_rundir("$(projectdir)")
target_end()

if has_config("libvultra_with_openxr") then
    target("example-xr-common")
        set_kind("static")
        set_default(false)
        add_deps("vultra", {public = true})
        add_files("common/xr_sample.cpp")
    target_end()

    target("example-xr")
        set_kind("binary")
        set_default(true)
        add_deps("example-xr-common", "vultra")
        add_deps("asset-sponza", {inherit = false})
        add_files("xr/*.cpp")
        set_rundir("$(projectdir)")
    target_end()
end

target("example-native-cpp-plugin")
    set_kind("shared")
    set_default(false)
    add_includedirs("../source/api/include", "../source/scripting/include")
    add_files("scripting/native_cpp.cpp")
target_end()

target("example-scripting")
    set_kind("binary")
    set_default(false)
    add_deps("example-common", "vultra-scripting")
    add_deps("vultra-managed-host", {inherit = false})
    add_deps("example-native-cpp-plugin", "example-native-plugin", {inherit = false})
    add_files("scripting/main.cpp")
    set_rundir("$(projectdir)")
    before_build(function ()
        local output = path.join(os.projectdir(), "build", ".tmp", "scripting-managed")
        os.mkdir(output)
        os.execv("dotnet", {"build", path.join(os.projectdir(), "examples", "scripting", "csharp", "VultraScript.csproj"),
            "-c", "Release", "-o", output, "--no-dependencies"})
    end)
target_end()
