#pragma once

struct FrameData
{
    float4x4 viewProjection;
    float4x4 inverseViewProjection;
    float4x4 view;
    float4x4 lightViewProjection[4];
    float4   cameraPosition;
    float4   lightDirection;
    float4   lightColor;
    float4   cascadeSplits;
    float4   cascadeWidths;
    float4   cascadeDepthRanges;
    float4   shadowParameters;
    float4   options;
    float4   cameraClip;
    float4   overrides; // Roughness, metalness, display transfer, meshlet display palette.
};

[[vk::binding(0, 0)]] ConstantBuffer<FrameData> frame;
[[vk::binding(1, 0)]] Texture2D<float>          shadow0;
[[vk::binding(2, 0)]] Texture2D<float>          shadow1;
[[vk::binding(3, 0)]] Texture2D<float>          shadow2;
[[vk::binding(4, 0)]] Texture2D<float>          shadow3;
[[vk::binding(5, 0)]] Texture2D<float4>         radianceMap;
[[vk::binding(6, 0)]] Texture2D<float4>         diffuseMap;
[[vk::binding(7, 0)]] Texture2D<float4>         specularMap;
[[vk::binding(8, 0)]] Texture2D<float4>         brdfLut;
[[vk::binding(9, 0)]] Texture2D<float4>         hdrColor;
[[vk::binding(10, 0)]] SamplerState             environmentSampler;
