#pragma once

#include "lib/space.slangh"

struct ScreenVertex
{
    float4 position : SV_Position;
    float2 uv : TEXCOORD0;
};

[shader("vertex")] ScreenVertex screenVertex(uint id
                                             : SV_VertexID)
{
    ScreenVertex result;
    result.uv       = float2((id << 1) & 2, id & 2);
    result.position = float4(uvToClip(result.uv), 0, 1);
    return result;
}
