includes("../scripts/bc7_ispc.lua")

target("vultra")
    set_kind("static")
    add_includedirs("include", {public = true})
    add_headerfiles("include/(vultra/**.hpp)")
    add_files("src/core/**.cpp", "src/platform/windows/**.cpp", "src/platform/glfw/**.cpp")
    add_syslinks("comdlg32")
    add_files("src/function/app/**.cpp", "src/function/rendergraph/**.cpp", "src/function/research/**.cpp")
    add_files("src/function/camera/**.cpp")
    add_files("src/function/renderer/gui*.cpp", "src/function/renderer/texture_blit.cpp")
    add_includedirs("../external/FileWatch")
    add_packages("vri", "glfw", "imgui", "slang-prebuilt", "argparse", "spdlog", "glm", {public = true})
    add_packages("stb")
    add_defines("NOMINMAX", "WIN32_LEAN_AND_MEAN", {public = true})
    if has_config("libvultra_with_openxr") then
        add_defines("VULTRA_WITH_OPENXR", {public = true})
        add_files("src/function/openxr/**.cpp")
        add_packages("openxr", "vulkan-headers", {public = true})
    end
target_end()

target("vultra-renderer")
    set_kind("static")
    set_default(false)
    add_deps("vultra", {public = true})
    add_packages("glm", {public = true})
    add_packages("tinygltf", "tinyobjloader", "stb", "xxhash", "vtask", "openfbx", "directxtex", "ispc", "meshoptimizer")
    add_rules("vultra.bc7-ispc")
    add_files("../external/bc7enc/bc7e.ispc")
    add_syslinks("ole32") -- DirectXTex's CPU utilities share its WIC initialization object.
    add_includedirs("../external/openpbr", {system = true})
    add_files("src/function/renderer/**.cpp")
    add_files("src/function/asset/**.cpp")
    remove_files("src/function/renderer/gui*.cpp", "src/function/renderer/texture_blit.cpp")
    add_headerfiles("include/(vultra/function/renderer/**.hpp)")
target_end()
