// Generated by scripts/codegen.py. Do not edit.
#pragma once
#include <vultra/assets/material_parameters.hpp>
#include <vultra/core/base/property.hpp>

namespace vultra
{
    const ObjectTypeInfo& materialParametersType();
} // namespace vultra
