// Generated by scripts/codegen.py. Do not edit.
#pragma once

#include <vultra/api/vultra_scene.generated.h>

extern "C"
{
#include <lauxlib.h>
#include <lua.h>
}

namespace vultra::scripting::detail
{
    inline float luaFloatField(lua_State* state, int index, const char* name)
    {
        lua_getfield(state, index, name);
        const auto value = static_cast<float>(luaL_checknumber(state, -1));
        lua_pop(state, 1);
        return value;
    }

    inline void pushLuaValue(lua_State* state, const VultraCameraSettings& value)
    {
        lua_newtable(state);
        lua_pushnumber(state, value.verticalFov);
        lua_setfield(state, -2, "vertical_fov");
        lua_pushnumber(state, value.nearPlane);
        lua_setfield(state, -2, "near_plane");
        lua_pushnumber(state, value.farPlane);
        lua_setfield(state, -2, "far_plane");
    }

    inline VultraCameraSettings readLuaCameraSettings(lua_State* state, int index)
    {
        luaL_checktype(state, index, LUA_TTABLE);
        index = lua_absindex(state, index);
        return {
            luaFloatField(state, index, "vertical_fov"),
            luaFloatField(state, index, "near_plane"),
            luaFloatField(state, index, "far_plane"),
        };
    }

    inline void pushLuaValue(lua_State* state, const VultraEnvironmentSettings& value)
    {
        lua_newtable(state);
        lua_pushnumber(state, value.intensity);
        lua_setfield(state, -2, "intensity");
    }

    inline VultraEnvironmentSettings readLuaEnvironmentSettings(lua_State* state, int index)
    {
        luaL_checktype(state, index, LUA_TTABLE);
        index = lua_absindex(state, index);
        return {
            luaFloatField(state, index, "intensity"),
        };
    }

    inline void pushLuaValue(lua_State* state, const VultraLightSettings& value)
    {
        lua_newtable(state);
        lua_pushnumber(state, value.red);
        lua_setfield(state, -2, "red");
        lua_pushnumber(state, value.green);
        lua_setfield(state, -2, "green");
        lua_pushnumber(state, value.blue);
        lua_setfield(state, -2, "blue");
        lua_pushnumber(state, value.intensity);
        lua_setfield(state, -2, "intensity");
        lua_pushnumber(state, value.range);
        lua_setfield(state, -2, "range");
        lua_pushnumber(state, value.innerCone);
        lua_setfield(state, -2, "inner_cone");
        lua_pushnumber(state, value.outerCone);
        lua_setfield(state, -2, "outer_cone");
    }

    inline VultraLightSettings readLuaLightSettings(lua_State* state, int index)
    {
        luaL_checktype(state, index, LUA_TTABLE);
        index = lua_absindex(state, index);
        return {
            luaFloatField(state, index, "red"),
            luaFloatField(state, index, "green"),
            luaFloatField(state, index, "blue"),
            luaFloatField(state, index, "intensity"),
            luaFloatField(state, index, "range"),
            luaFloatField(state, index, "inner_cone"),
            luaFloatField(state, index, "outer_cone"),
        };
    }

    inline void pushLuaValue(lua_State* state, const VultraMaterialParameters& value)
    {
        lua_newtable(state);
        lua_pushnumber(state, value.baseRed);
        lua_setfield(state, -2, "base_red");
        lua_pushnumber(state, value.baseGreen);
        lua_setfield(state, -2, "base_green");
        lua_pushnumber(state, value.baseBlue);
        lua_setfield(state, -2, "base_blue");
        lua_pushnumber(state, value.baseAlpha);
        lua_setfield(state, -2, "base_alpha");
        lua_pushnumber(state, value.baseWeight);
        lua_setfield(state, -2, "base_weight");
        lua_pushnumber(state, value.baseMetalness);
        lua_setfield(state, -2, "base_metalness");
        lua_pushnumber(state, value.baseDiffuseRoughness);
        lua_setfield(state, -2, "base_diffuse_roughness");
        lua_pushnumber(state, value.specularWeight);
        lua_setfield(state, -2, "specular_weight");
        lua_pushnumber(state, value.specularRed);
        lua_setfield(state, -2, "specular_red");
        lua_pushnumber(state, value.specularGreen);
        lua_setfield(state, -2, "specular_green");
        lua_pushnumber(state, value.specularBlue);
        lua_setfield(state, -2, "specular_blue");
        lua_pushnumber(state, value.specularRoughness);
        lua_setfield(state, -2, "specular_roughness");
        lua_pushnumber(state, value.specularIor);
        lua_setfield(state, -2, "specular_ior");
        lua_pushnumber(state, value.coatWeight);
        lua_setfield(state, -2, "coat_weight");
        lua_pushnumber(state, value.coatRoughness);
        lua_setfield(state, -2, "coat_roughness");
        lua_pushnumber(state, value.coatIor);
        lua_setfield(state, -2, "coat_ior");
        lua_pushnumber(state, value.emissionRed);
        lua_setfield(state, -2, "emission_red");
        lua_pushnumber(state, value.emissionGreen);
        lua_setfield(state, -2, "emission_green");
        lua_pushnumber(state, value.emissionBlue);
        lua_setfield(state, -2, "emission_blue");
        lua_pushnumber(state, value.emissionLuminance);
        lua_setfield(state, -2, "emission_luminance");
        lua_pushnumber(state, value.normalScale);
        lua_setfield(state, -2, "normal_scale");
        lua_pushnumber(state, value.occlusionStrength);
        lua_setfield(state, -2, "occlusion_strength");
        lua_pushnumber(state, value.alphaCutoff);
        lua_setfield(state, -2, "alpha_cutoff");
    }

    inline VultraMaterialParameters readLuaMaterialParameters(lua_State* state, int index)
    {
        luaL_checktype(state, index, LUA_TTABLE);
        index = lua_absindex(state, index);
        return {
            luaFloatField(state, index, "base_red"),
            luaFloatField(state, index, "base_green"),
            luaFloatField(state, index, "base_blue"),
            luaFloatField(state, index, "base_alpha"),
            luaFloatField(state, index, "base_weight"),
            luaFloatField(state, index, "base_metalness"),
            luaFloatField(state, index, "base_diffuse_roughness"),
            luaFloatField(state, index, "specular_weight"),
            luaFloatField(state, index, "specular_red"),
            luaFloatField(state, index, "specular_green"),
            luaFloatField(state, index, "specular_blue"),
            luaFloatField(state, index, "specular_roughness"),
            luaFloatField(state, index, "specular_ior"),
            luaFloatField(state, index, "coat_weight"),
            luaFloatField(state, index, "coat_roughness"),
            luaFloatField(state, index, "coat_ior"),
            luaFloatField(state, index, "emission_red"),
            luaFloatField(state, index, "emission_green"),
            luaFloatField(state, index, "emission_blue"),
            luaFloatField(state, index, "emission_luminance"),
            luaFloatField(state, index, "normal_scale"),
            luaFloatField(state, index, "occlusion_strength"),
            luaFloatField(state, index, "alpha_cutoff"),
        };
    }

    inline void pushLuaValue(lua_State* state, const VultraSceneTranslation& value)
    {
        lua_newtable(state);
        lua_pushnumber(state, value.x);
        lua_setfield(state, -2, "x");
        lua_pushnumber(state, value.y);
        lua_setfield(state, -2, "y");
        lua_pushnumber(state, value.z);
        lua_setfield(state, -2, "z");
    }

    inline VultraSceneTranslation readLuaSceneTranslation(lua_State* state, int index)
    {
        luaL_checktype(state, index, LUA_TTABLE);
        index = lua_absindex(state, index);
        return {
            luaFloatField(state, index, "x"),
            luaFloatField(state, index, "y"),
            luaFloatField(state, index, "z"),
        };
    }

} // namespace vultra::scripting::detail
