#pragma once

struct SurfaceData
{
    float3 worldPosition;
    float3 normal;
    float3 geometricNormal;
    float3 baseColor;
    float  baseWeight;
    float  metallic;
    float  roughness;
    float3 emission;
    float  occlusion;
    float3 specularColor;
    float  specularWeight;
    float  specularIor;
    float  coatWeight;
    float  coatRoughness;
    float  coatIor;
    float  baseDiffuseRoughness;
};
